import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture,createBot,createTask } from './helpers.mjs';
import { Ledger } from '../src/ledger.mjs';
import { Host } from '../src/host.mjs';

test('bot policy and session mode are independent version fields; native mode fails closed',()=>{const f=fixture(),b=createBot(f),cfg=f.ledger.get('config',b.configVersion);assert.deepEqual(cfg.sessionModes,{plan:null,permissions:null});assert.equal(cfg.autonomy.enabled,false);assert.throws(()=>f.cmd('updateBotConfig',{botId:b.botId,config:{contact:cfg.contact,sessionModes:{plan:true,permissions:null}}},b.revision),{code:'unsupported_session_mode'});const next=f.cmd('updateBotConfig',{botId:b.botId,config:{contact:cfg.contact,autonomy:{enabled:true,maxSteps:4,maxRetries:1,observationDeadline:null,reportMilestonesOnly:true}}},b.revision).result;assert.deepEqual(f.ledger.get('config',next.configVersion).contact,cfg.contact);assert.equal(f.ledger.get('config',next.configVersion).autonomy.enabled,true);f.ledger.close();});
test('autonomous plan persists bounded next step and waits on native gate without dispatch',()=>{let calls=0;const f=fixture({capabilities:()=>({}),dispatch:()=>{calls++;}}),b=createBot(f),t=createTask(f,b);const p=f.cmd('createProgressPlan',{taskId:t.taskId,steps:[{title:'produce artifact',evidence:'digest'},{title:'validate artifact',evidence:'human check'}]},t.revision).result;const r=f.cmd('advanceTask',{planId:p.planId,eventId:'event-1',cursor:1,trigger:'user'},p.revision).result;assert.equal(r.state,'waiting_native');assert.equal(r.nextStepId,p.steps[0].stepId);assert.equal(calls,0);assert.equal(r.steps[0].state,'pending');f.ledger.close();const l=new Ledger(f.path);assert.equal(l.get('progress',p.planId).eventCursor,1);l.close();});
test('unknown progress checkpoint never advances or retries effect; events are idempotent',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b),p=f.cmd('createProgressPlan',{taskId:t.taskId,steps:[{title:'work',evidence:'digest'}]},t.revision).result;f.ledger.put('progress',p.planId,{...p,state:'reconciling_unknown'});const r=f.cmd('advanceTask',{planId:p.planId,eventId:'unknown-event',cursor:1,trigger:'recovery'},p.revision).result;assert.equal(r.state,'reconciling_unknown');assert.equal(r.retryCount,0);assert.equal(f.ledger.list('attempt').length,0);const repeat=f.cmd('advanceTask',{planId:p.planId,eventId:'unknown-event',cursor:1,trigger:'recovery'},r.revision).result;assert.equal(repeat.revision,r.revision);f.ledger.close();});
test('task stop fences checkpoint and pending plan cannot claim delivered',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b),p=f.cmd('createProgressPlan',{taskId:t.taskId,steps:[{title:'work',evidence:'digest'}]},t.revision).result;f.cmd('stopTask',{taskId:t.taskId},t.revision);assert.throws(()=>f.cmd('advanceTask',{planId:p.planId,eventId:'late',cursor:1,trigger:'result'},p.revision),{code:'epoch_conflict'});assert.notEqual(f.ledger.get('task',t.taskId).responsibility,'verified');f.ledger.close();});
test('plan bounds, frozen policy and bot epoch survive setting changes but reject archive resurrection',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b),cfg=f.ledger.get('config',b.configVersion);const next=f.cmd('updateBotConfig',{botId:b.botId,config:{contact:cfg.contact,autonomy:{maxSteps:1,maxRetries:0}}},b.revision).result;assert.throws(()=>f.cmd('createProgressPlan',{taskId:t.taskId,steps:[{title:'A',evidence:'digest'},{title:'B',evidence:'digest'}]},t.revision),{code:'invalid_plan'});const p=f.cmd('createProgressPlan',{taskId:t.taskId,steps:[{title:'A',evidence:'digest'}]},t.revision).result;f.cmd('updateBotConfig',{botId:b.botId,config:{contact:{...cfg.contact,model:'B'},autonomy:{maxSteps:5,maxRetries:2}}},next.revision);assert.equal(f.ledger.get('progress',p.planId).configSnapshot.contact.model,'model-A');assert.equal(f.ledger.get('progress',p.planId).policySnapshot.maxSteps,1);const current=f.ledger.get('bot',b.botId),arch=f.cmd('archive',{kind:'bot',id:b.botId},current.revision).result;f.cmd('restore',{kind:'bot',id:b.botId},arch.revision);assert.throws(()=>f.cmd('advanceTask',{planId:p.planId,eventId:'late',cursor:1,trigger:'recovery'},p.revision),{code:'epoch_conflict'});f.ledger.close();});
test('cursor gaps and altered event identity are rejected; elapsed window remains unverified',()=>{const f=fixture(),b=createBot(f),cfg=f.ledger.get('config',b.configVersion);f.cmd('updateBotConfig',{botId:b.botId,config:{contact:cfg.contact,autonomy:{observationDeadline:'2020-01-01T00:00:00Z'}}},b.revision);const t=createTask(f,b),p=f.cmd('createProgressPlan',{taskId:t.taskId,steps:[{title:'A',evidence:'digest'}]},t.revision).result;assert.throws(()=>f.cmd('advanceTask',{planId:p.planId,eventId:'gap',cursor:2,trigger:'user'},p.revision),{code:'cursor_conflict'});const r=f.cmd('advanceTask',{planId:p.planId,eventId:'first',cursor:1,trigger:'authorized_check'},p.revision).result;assert.equal(r.state,'blocked');assert.equal(r.blockers[0].code,'observation_window_ended');assert.throws(()=>f.cmd('advanceTask',{planId:p.planId,eventId:'first',cursor:1,trigger:'result'},r.revision),{code:'event_conflict'});assert.equal(f.ledger.get('task',t.taskId).responsibility,'open');f.ledger.close();});
