import{coldResultDiagnostic}from'./cold-result-diagnostic.mjs';
import test from'node:test';import assert from'node:assert/strict';import{readFile,mkdtemp,mkdir,writeFile}from'node:fs/promises';import{join}from'node:path';import{createChainRequestGuard}from'../src/bot-chain-request-guard.mjs';import*as app from'../src/bot-chain-owner-app.mjs';import{stockRuntime}from'./bot-producer-fixture.mjs';import Preset from'@deepseek-ai/dsh-agent-preset';import{digest}from'../src/errors.mjs';
/** From-zero deterministic synthetic history; never actual API or Home evidence. */
globalThis.__offlineIO={model:0};const fixture=JSON.parse(await readFile(new URL('./chain-continuation-fixture.json',import.meta.url),'utf8'));assert.equal(fixture.synthetic,true);const copy=()=>structuredClone(fixture),ids=fixture.requests.map(r=>r.requestId).sort(),historyDigest='2b3a4ed564ed0c15de195f587e679cffaff5471d891ed4081ff56e8b5ae32568';assert.equal(digest([...fixture.requests].sort((a,b)=>a.requestId.localeCompare(b.requestId))),historyDigest);
const opts={provider:'deepseek-official',model:'deepseek-flash',maxTokens:256,reasoningEffort:'off',sessionId:'new-work',messages:[{role:'user',content:[{type:'text',text:'harmless'}]}]};
test('four original confirmed rows remain immutable and five new attempts exhaust global nine',async()=>{let effects=0;const target={fetch:()=>{effects++;assert.fail('no wire dispatched');}},saved=[],original=JSON.stringify(fixture.requests);const guard=createChainRequestGuard({fetchTarget:target,save:r=>saved.push(r),confirmedHistory:fixture.requests,expectedHistoryDigest:historyDigest});try{assert.equal(guard.snapshot().requests.length,4);guard.bind('new-work',{kind:'work',isCurrent:()=>true});for(let i=0;i<5;i++)await assert.rejects(async()=>{for await(const c of guard.wrap(opts,()=>({async *[Symbol.asyncIterator](){throw Error('fixture pre-effect denial');}}))){};});assert.equal(guard.snapshot().requests.length,9);await assert.rejects(async()=>{for await(const c of guard.wrap(opts,()=>({async *[Symbol.asyncIterator](){assert.fail('tenth dispatch');}}))){};},{code:'chain_request_limit'});assert.equal(saved.some(r=>ids.includes(r.requestId)),false);assert.equal(effects,0);assert.equal(JSON.stringify(fixture.requests),original);}finally{guard.dispose();}});
for(const [name,alter]of[['duplicate IDs',r=>r[1].requestId=r[0].requestId],['pending',r=>r[0].outcome='pending'],['unknown',r=>r[0].outcome='unresolved'],['raw translated mismatch',r=>r[0].rawUsage.input_tokens++],['output overflow',r=>{r[0].usage.outputTokens=257;r[0].rawUsage.output_tokens=257;}],['missing original',r=>r.pop()],['self-consistent altered accounting',r=>{r[0].usage.inputTokens++;r[0].rawUsage.input_tokens++;r[0].usageUpperCny=(2*(r[0].usage.inputTokens+(r[0].usage.cacheReadTokens??0)+(r[0].usage.cacheWriteTokens??0))+8*r[0].usage.outputTokens)/1000000;}]])test(`history seed rejects ${name} before fetch installation`,()=>{const rows=structuredClone(fixture.requests);alter(rows);const original=()=>assert.fail('fetch forbidden'),target={fetch:original};assert.throws(()=>createChainRequestGuard({fetchTarget:target,save:()=>{},confirmedHistory:rows,expectedHistoryDigest:historyDigest}),{code:'chain_history_invalid'});assert.equal(target.fetch,original);});
function verify(f){assert.equal(typeof app.verifyChainContinuation,'function','continuation eligibility missing');return app.verifyChainContinuation(f,{botId:fixture.entry.botId,mainSessionId:fixture.entry.mainSessionId,cwd:fixture.entry.cwd,requestIds:ids,historyDigest});}
test('eligible continuation reconstructs exact original source task marker ACK without activating old work',()=>{const result=verify(copy());assert.equal(result.acknowledgment.turn,2);assert.equal(result.oldWorkHeld,true);assert.equal(result.task_id,'fixture-one');});
for(const [name,alter]of[['wrong route identity',f=>f.route.taskId='wrong-task'],['wrong ACK marker',f=>f.mainLog.events.find(e=>e.type==='assistant/message'&&e.data.turn===2).data.message.content[0].text='fixture-one CHAIN_TWO_946'],['pending inbox',f=>f.mainLog.events.push({type:'agent/inbox/spliced',data:{target:'next-turn',start:0,removedCount:0,inserted:[{id:'synthetic-pending'}]}})],['old work pending inbox',f=>f.workLog.events.push({type:'agent/inbox/spliced',data:{target:'next-step',start:0,inserted:[{id:'synthetic-pending'}]}})],['fenced old generation',f=>f.generation.fence={reason:'terminate'}]])test(`resume eligibility rejects ${name}`,()=>{const f=copy();alter(f);assert.throws(()=>verify(f),{code:'chain_resume_ineligible'});});
test('actual stock Controller resolves existing main only and leaves model IO zero',async t=>{verify(copy());const dir=await mkdtemp(join(process.env.DSH_BOT_TEST_ROOT,'resume-'));const sessionDir=join(dir,'sessions','--'+fixture.entry.cwd.replace(/^\//,'').replaceAll('/','-')+'--',fixture.entry.mainSessionId);await mkdir(sessionDir,{recursive:true});await writeFile(join(sessionDir,'session.v4.jsonl'),[fixture.mainLog.header,...fixture.mainLog.events].map(e=>JSON.stringify(e)).join('\n')+'\n');const before=globalThis.__offlineIO.model;const ctx=await stockRuntime(dir);t.after(()=>ctx.fiber.dispose());ctx.attachments.imageLimits=Object.freeze({maxImageBytes:1,maxImagesPerMessage:1,maxMessageImageBytes:1,maxImagePixels:1,maxImageDimension:1,mediaTypes:[]});await ctx.plugin(Preset,{id:'chain/empty',plugins:[]});const result=await ctx.sessionController.resolveAgent(fixture.entry.mainSessionId);t.diagnostic(JSON.stringify(coldResultDiagnostic(result)));assert.equal('agent'in result,true,'stock existing resolve must succeed');assert.equal(result.agent.id,fixture.entry.mainSessionId);assert.equal(result.agent.status,'idle');assert.equal(ctx.agents.get(fixture.work.sessionId),undefined);const inbox=ctx.sessionProjections.stateOf(result.agent.session,'inbox');assert.equal(inbox['next-turn'].length+inbox['next-step'].length,0);assert.equal(globalThis.__offlineIO.model,before);assert.equal(result.agent.session.snapshotEvents().filter(e=>e.type==='turn/end').at(-1).data.turn,2);});
const humanQuestion='Which completed task and exact marker did you receive, and are you ready for the next harmless goal?';function checkinEvents(){const f=copy(),id=f.route.resultInputMessageId;const input=f.mainLog.events.find(e=>e.type==='user/message'&&e.data.id===id);input.data.source={kind:'user'};input.data.content=[{type:'text',text:humanQuestion}];return {events:f.mainLog.events,id};}
test('substantive checkin requires actual user input and exact same-turn completed task marker response',()=>{const f=checkinEvents();assert.equal(app.deriveChainCheckinAcknowledgment(f.events,f.id,humanQuestion)?.turn,2);});
for(const [name,change]of[['wrong marker',e=>e.data.message.content[0].text='fixture-one CHAIN_TWO_946'],['tool-only response',e=>e.data.message.content=[{type:'tool-call',name:'dsh_bot_delegate',id:'synthetic-call',arguments:'{}'}]]])test(`substantive checkin rejects ${name}`,()=>{const f=checkinEvents();change(f.events.find(e=>e.type==='assistant/message'&&e.data.turn===2));assert.equal(app.deriveChainCheckinAcknowledgment(f.events,f.id,humanQuestion),null);});
