import test from'node:test';import assert from'node:assert/strict';import{createChainRequestGuard}from'../src/bot-chain-request-guard.mjs';
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms)),enc=s=>new TextEncoder().encode(s);
const frames=[{type:'message_start',message:{model:'deepseek-flash',usage:{input_tokens:7,output_tokens:0}}},{type:'message_delta',delta:{stop_reason:'end_turn'},usage:{output_tokens:2}},{type:'message_stop'}].map(e=>`data: ${JSON.stringify(e)}\n\n`);
const wire=()=>({model:'deepseek-flash',max_tokens:256,thinking:{type:'disabled'},stream:true,messages:[{role:'user',content:[{type:'text',text:'harmless'}]}]});
const opts=signal=>({provider:'deepseek-official',model:'deepseek-flash',maxTokens:256,reasoningEffort:'off',sessionId:'work',messages:[{role:'user',content:[{type:'text',text:'harmless'}]}],signal});
function setup(t,fetch,timeoutMs=200){const saved=[],target={fetch},guard=createChainRequestGuard({fetchTarget:target,timeoutMs,save:r=>saved.push(structuredClone(r))});guard.bind('work',{kind:'work',isCurrent:()=>true});t.after(()=>guard.dispose());return{saved,target,guard};}
const complete=()=>new Response(frames.join(''));
async function drain(f,signal){const terminal=[];try{for await(const chunk of f.guard.wrap(opts(signal),()=>({async *[Symbol.asyncIterator](){await f.guard.prepareWire({body:wire(),sessionId:'work',signal:signal??new AbortController().signal});const r=await f.target.fetch(new Proxy({},{get(){assert.fail('request inspected');}}),new Proxy({},{get(){assert.fail('headers inspected');}}));for await(const unused of r.body){}yield{type:'usage',usage:{inputTokens:7,outputTokens:2}};yield{type:'finish',reason:{kind:'stop'}};}})))terminal.push(chunk.type);}finally{f.terminal=terminal;}}
test('absolute effect deadline covers delayed headers and cancels a late response without terminal publication',async t=>{let cancelled=false,closeTimer;const f=setup(t,async()=>{await wait(60);return new Response(new ReadableStream({start(c){for(const x of frames)c.enqueue(enc(x));closeTimer=setTimeout(()=>c.close(),5);},cancel(){cancelled=true;clearTimeout(closeTimer);}}));},20);await assert.rejects(()=>drain(f),{code:'chain_response_timeout'});const row=f.saved.at(-1);assert.equal(row.outcome,'unresolved');assert.equal(f.guard.snapshot().halted,true);assert.equal(row.elapsedMs>=15,true);assert.equal(row.elapsedMs<60,true);assert.deepEqual(f.terminal,[]);await wait(65);assert.equal(cancelled,true);assert.equal(f.saved.at(-1).outcome,'unresolved');});
test('healthy continuously arriving SSE cannot extend the absolute effect deadline',async t=>{let interval;const f=setup(t,async()=>{await wait(50);return new Response(new ReadableStream({start(c){c.enqueue(enc(frames[0]));let n=0;interval=setInterval(()=>{c.enqueue(enc(': harmless heartbeat\n\n'));if(++n===10){clearInterval(interval);c.enqueue(enc(frames[1]+frames[2]));c.close();}},5);},cancel(){clearInterval(interval);}}));},80);t.after(()=>clearInterval(interval));await assert.rejects(()=>drain(f),{code:'chain_response_timeout'});assert.equal(f.saved.at(-1).outcome,'unresolved');assert.equal(f.saved.at(-1).elapsedMs>=70,true);assert.deepEqual(f.terminal,[]);});
for(const kind of['transport','raw','cancel'])test(`${kind} effect failure always records elapsed time and fixed safe category`,async t=>{const ac=new AbortController();let c;const f=setup(t,async()=>{await wait(10);if(kind==='transport')throw Error('UNSAFE_TRANSPORT_TEXT');if(kind==='raw')return new Response('data: {"type":"error"}\n\n');setTimeout(()=>ac.abort(),10);return new Response(new ReadableStream({start(value){c=value;c.enqueue(enc(frames[0]));}}));});await assert.rejects(()=>drain(f,ac.signal));assert.equal(f.saved.at(-1).outcome,'unresolved');assert.equal(f.saved.at(-1).elapsedMs>=5,true);assert.equal(JSON.stringify(f.saved).includes('UNSAFE_TRANSPORT_TEXT'),false);assert.deepEqual(f.terminal,[]);c?.close();});
test('HTTP403 records exact integer status and fixed HTTP layer without provider body',async t=>{const f=setup(t,async()=>new Response('UNSAFE_RESPONSE_BODY',{status:403}));await assert.rejects(()=>drain(f),{code:'chain_http_403'});const row=f.saved.at(-1);assert.equal(row.responseStatus,403);assert.equal(row.outcome,'unresolved');assert.equal(Number.isFinite(row.elapsedMs),true);assert.equal(JSON.stringify(f.saved).includes('UNSAFE_RESPONSE_BODY'),false);assert.deepEqual(f.terminal,[]);});
test('successful effect records HTTP200 and elapsed time',async t=>{const f=setup(t,async()=>{await wait(10);return complete();});await drain(f);const row=f.saved.at(-1);assert.equal(row.responseStatus,200);assert.equal(row.outcome,'confirmed');assert.equal(row.elapsedMs>=5,true);});
