/** Actual stock AgentLoop with explicit synthetic chunks; no provider or network. */
import test from'node:test';import assert from'node:assert/strict';import{stockFixture,envelope}from'./bot-producer-fixture.mjs';import{installOwnedBotProducer}from'../src/bot-producer.mjs';import{deriveMainAcknowledgment}from'../src/bot-chain-response.mjs';
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));const until=async fn=>{for(let n=0;n<200;n++){const r=fn();if(r)return r;await wait(5);}assert.fail('bounded offline identity evidence timeout');};
async function* chunks(text){yield{type:'block-start',index:0,blockType:'text'};yield{type:'text-delta',index:0,text};yield{type:'block-end',index:0,block:{type:'text',text}};yield{type:'usage',usage:{inputTokens:7,outputTokens:2}};yield{type:'finish',reason:{kind:'stop'}};}
test('authorized generation fence during observed work flush prevents any new main route',async t=>{const f=await stockFixture(t),release=Promise.withResolvers();f.ctx.llm.prepareCall=async config=>({config:{...config,provider:'deepseek-official',model:'deepseek-flash',maxTokens:256,reasoningEffort:'off'},retryPolicy:{maxRetries:0},adapterDefaults:{},stream:o=>({async *[Symbol.asyncIterator](){if(o.sessionId!==f.originAgent.id)await release.promise;yield*chunks('one ONE');}})});const p=installOwnedBotProducer({...f.options,execution:{beforeExecute:async()=>({expectedMarker:'ONE'})}});t.after(()=>p.dispose());await p.delegate({operationId:crypto.randomUUID(),nonce:crypto.randomUUID(),task_id:'one',goal:'Return ONE',completion_condition:'Only ONE'});const w=await p.execute({task_id:'one',generation:1});const port=f.host.openOwnedWorkSessionPort(f.caller,{botId:f.bot.botId,botEpoch:f.bot.epoch,authorityEpoch:1});t.after(()=>port.dispose());const sessions=f.ctx.sessions,original=sessions.flush;let fenced=false;sessions.flush=async function(session){if(session.id===w.sessionId&&!fenced&&session.snapshotEvents().some(e=>e.type==='turn/end')){fenced=true;const q=port.query({task_ids:['one']}).work[0],payload={task_id:'one',generation:1,reason:'terminate'};try{port.fence(envelope('fenceWorkSession',payload,q.revision,{nativeOwner:1,bot:f.bot.epoch,task:q.taskEpoch}),payload);}catch(error){t.diagnostic(JSON.stringify({fenceErrorCode:error.code}));throw error;}}return original.call(sessions,session);};f.restores.push(()=>{sessions.flush=original;});release.resolve();await until(()=>fenced);assert.equal(port.query({}).work[0].fence?.reason,'terminate');await wait(100);const routes=f.originAgent.session.snapshotEvents().flatMap(e=>e.type==='agent/inbox/spliced'?e.data.inserted:[]).filter(m=>m.source.kind==='dsh-bot-work-result');assert.equal(routes.length,0);assert.equal(p.acknowledged({task_id:'one',generation:1}),null);assert.equal(port.query({}).work[0].held,true);});
const expected={source:{kind:'dsh-bot-work-result',botId:'bot',taskId:'internal-task-one',sessionId:'work-one',generation:1,task_id:'one'},task_id:'one',expectedMarker:'ONE_731',forbiddenMarkers:['TWO_946']};
function evidence(text='one ONE_731',source=expected.source){return[{type:'turn/start',data:{turn:1}},{type:'user/message',data:{id:'routed',source,content:[{type:'text',text:'Observed work result (one): ONE_731'}]}},{type:'assistant/message',seq:3,data:{turn:1,message:{id:'ack',content:[{type:'text',text}]},stream:[{chunk:{type:'finish',reason:{kind:'stop'}}}]}},{type:'turn/end',data:{turn:1,reason:{kind:'completed'}}}];}
test('main acknowledgment binds routed task identity and expected harmless marker',()=>{assert.equal(deriveMainAcknowledgment(evidence(),'routed',expected)?.responseMessageId,'ack');});
for(const kind of['wrong-source-task','wrong-marker','wrong-reply-task','second-marker'])test(`${kind} cannot satisfy source-bearing main acknowledgment`,()=>{const es=evidence();if(kind==='wrong-source-task')es[1].data.source={...expected.source,taskId:'foreign-task'};if(kind==='wrong-marker')es[2].data.message.content[0].text='one WRONG';if(kind==='wrong-reply-task')es[2].data.message.content[0].text='two ONE_731';if(kind==='second-marker')es[2].data.message.content[0].text='one ONE_731 TWO_946';assert.equal(deriveMainAcknowledgment(es,'routed',expected),null);});
