import{packageSnapshotOptions}from'./package-snapshot-fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readdir,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {installBotNativePhaseProfile} from '../scripts/install-bot-native-phase-profile.mjs';
// Synthetic metadata only. No SDK, model, existing Home, or historical ledger is opened.
async function fixture(){const root=await mkdtemp(join(process.env.DSH_BOT_TEST_ROOT,'native-profile-options-'));const args={homeDirectory:join(root,'home'),productRoot:join(root,'product'),runtimeRoot:join(root,'runtime'),cwd:join(root,'cwd')};for(const p of Object.values(args))await mkdir(p);await mkdir(join(args.homeDirectory,'profiles'));return args;}
const baseline=()=>({botId:randomUUID(),mainSessionId:'session-'+randomUUID(),historyDigest:createHash('sha256').update('synthetic-not-runtime-history').digest('hex')});
async function snapshot(args){return Object.fromEntries(await Promise.all(Object.entries(args).map(async([k,p])=>[k,await readdir(p,{recursive:true})])));}
test('native profile requires explicit baseline before any profile write',async()=>{const args=await fixture(),before=await snapshot(args);await assert.rejects(()=>installBotNativePhaseProfile(args),{message:'chain_native_baseline_required'});assert.deepEqual(await snapshot(args),before);});
test('malformed native baseline is rejected before any profile write',async()=>{const args=await fixture(),before=await snapshot(args),good=baseline();for(const value of [null,{}, {...good,botId:'not-an-id'}, {...good,mainSessionId:'session-invalid'}, {...good,historyDigest:'not-a-digest'}, {...good,extra:true}]){await assert.rejects(()=>installBotNativePhaseProfile({...args,baseline:value}),{message:'chain_native_baseline_invalid'});assert.deepEqual(await snapshot(args),before);}});
test('native profile serializes only caller supplied synthetic baseline',async()=>{const args=await fixture(),expected=baseline();const result=await installBotNativePhaseProfile({...args,productRoot:join(import.meta.dirname,'..'),...(await packageSnapshotOptions()),baseline:expected});const rows=JSON.parse(await readFile(join(args.homeDirectory,'profiles',result.profile,'cordis.patch.yml'),'utf8'))[0].insert;assert.deepEqual(rows.find(r=>r.id==='native-app').config.baseline,expected);const provider=rows.find(r=>r.id==='provider');assert.equal(provider.config.apiKeyEnv,'DEEPSEEK_API_KEY');assert.equal(provider.config.maxTokens,256);assert.equal(provider.config.retryPolicy.maxRetries,0);assert.equal(result.dsh,join(args.runtimeRoot,'node_modules','@deepseek-ai','dsh','lib','bin.js'));assert.equal(result.credentialsCreated,false);});
test('native baseline is captured before asynchronous filesystem preparation',async()=>{const args=await fixture(),input=baseline(),expected={...input};const pending=installBotNativePhaseProfile({...args,productRoot:join(import.meta.dirname,'..'),...(await packageSnapshotOptions()),baseline:input});Object.assign(input,baseline());const result=await pending;const rows=JSON.parse(await readFile(join(args.homeDirectory,'profiles',result.profile,'cordis.patch.yml'),'utf8'))[0].insert;assert.deepEqual(rows.find(r=>r.id==='native-app').config.baseline,expected);});
