import test from 'node:test';import assert from 'node:assert/strict';import {createChainRequestGuard} from '../src/bot-chain-request-guard.mjs';
async function phase(){const m=await import('../src/bot-chain-native-phase.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return{};});assert.equal(typeof m.createNativePhaseAdmission,'function','missing private8-purpose admission');return m.createNativePhaseAdmission();}
const tool={name:'dsh_bot_test_wait',description:'Harmless exact A-only wait',parameters:{type:'object',properties:{gate:{type:'string'}},required:['gate'],additionalProperties:false}};
const options=tools=>({provider:'deepseek-official',model:'deepseek-flash',reasoningEffort:'off',maxTokens:256,sessionId:'new-a',messages:[{role:'user',content:[{type:'text',text:'Harmless exact A wait'}]}],tools});
const body=tools=>({model:'deepseek-flash',stream:true,max_tokens:256,messages:[{role:'user',content:[{type:'text',text:'Harmless exact A wait'}]}],thinking:{type:'disabled'},tools:tools.map(t=>({name:t.name,description:t.description,input_schema:t.parameters}))});
async function fixture(t,config={}){const saved=[];let fetches=0;const target={fetch:async()=>{fetches++;return new Response('data: '+JSON.stringify({type:'message_start',message:{model:'deepseek-flash',usage:{input_tokens:7,output_tokens:0}}})+'\n\ndata: '+JSON.stringify({type:'message_delta',delta:{stop_reason:'end_turn'},usage:{output_tokens:2}})+'\n\ndata: {"type":"message_stop"}\n\n');}};const guard=createChainRequestGuard({save:r=>saved.push(r),fetchTarget:target,maxRequests:config.maxRequests??8});t.after(()=>guard.dispose());guard.bind('new-a',{kind:'work',isCurrent:()=>true,...config.binding});return{guard,saved,target,fetches:()=>fetches};}
async function run(f,neutral=[],wire=body(neutral)){for await(const unused of f.guard.wrap(options(neutral),()=>({async *[Symbol.asyncIterator](){await f.guard.prepareWire({body:wire,sessionId:'new-a',signal:new AbortController().signal});const r=await f.target.fetch(new Proxy({}, {get(){throw Error('request_must_not_be_inspected');}}));for await(const chunk of r.body){}yield{type:'usage',usage:{inputTokens:7,outputTokens:2}};yield{type:'finish',reason:{kind:'stop'}};}}))){}return f.saved.at(-1);}
test('guard admits only exact A neutral/wire wait schema in the private binding',async t=>{const f=await fixture(t,{binding:{toolPolicy:{gate:'EXACT_GATE',neutralTools:[tool]}}});assert.equal((await run(f,[tool])).outcome,'confirmed');assert.equal(f.fetches(),1);});
test('guard refuses changed A schema and any B wait before dispatch',async t=>{const f=await fixture(t,{binding:{toolPolicy:{gate:'EXACT_GATE',neutralTools:[tool]}}});await assert.rejects(()=>run(f,[{...tool,description:'Different'}]));assert.equal(f.fetches(),0);const b=await fixture(t);await assert.rejects(()=>run(b,[tool]));assert.equal(b.fetches(),0);});
test('new stage8 maximum has no spare ninth dispatch',async t=>{const f=await fixture(t);for(let i=0;i<8;i++)await run(f);await assert.rejects(()=>run(f));assert.equal(f.fetches(),8);});
test('private admitted purpose is recorded and automatic post-tool retry cannot use next purpose',async t=>{const p=await phase(),agent={},f=await fixture(t,{binding:{admit:()=>p.admit(agent)}});p.allow('main-A',agent,()=>true);assert.equal((await run(f)).scenario,'main-A');await assert.rejects(()=>run(f));assert.equal(f.fetches(),1);});
test('failed purpose and wrong Agent close the private continuation latch',async()=>{const p=await phase(),a={};p.allow('main-A',a,()=>true);assert.throws(()=>p.admit({}));assert.equal(p.snapshot().failed,true);assert.throws(()=>p.allow('A-wait',a,()=>true));});
test('eight ordered purposes each admit once and no purpose is available after completion',async()=>{const p=await phase(),agent={};for(const purpose of['main-A','A-wait','main-status','main-B','B-result','main-B-ACK','A-result','main-A-ACK']){p.allow(purpose,agent,()=>true);assert.equal(p.admit(agent),purpose);}assert.equal(p.snapshot().attempts.length,8);assert.throws(()=>p.allow('main-A',agent,()=>true));});
