/** Synthetic port contract tests; actual stock proof is separate. */
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {Host} from '../src/host.mjs';import {Ledger} from '../src/ledger.mjs';import {DshAdapter} from '../src/adapter.mjs';import {digest} from '../src/errors.mjs';
const wait=()=>new Promise(r=>setImmediate(r));const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
async function fixture(t,{create,inspect,runtime,producer}={}){const ledger=new Ledger(':memory:'),caller={},adapter=new DshAdapter({agentPresets:{list:()=>[{id:'fixture/empty'}],defaultId:'fixture/empty'}}),host=new Host({ledger,caller,ownerHumanId:'fixture',ownerCapability:caller,adapter,workSessionRuntime:runtime}),calls=[],store=new Map();t.after(()=>ledger.close());
 const command=(name,p,revision=null,epochs={})=>host.executeOwned(caller,env(name,p,revision,epochs),p).result;
 await adapter.refreshSessionModeCatalog();const bot=command('createBot',{name:'B',config:{contact:{provider:'unused',model:'unused'},agentPreset:'fixture/empty'}});
 const proof=i=>({sessionId:i.sessionId,agentPreset:i.agentPreset,blank:true,globalTools:0,scopedTools:0,proofKind:'stock-session-durable'});
 const creation={cwd:'/fixture',port:{async createOwnedSession(i){calls.push(i.sessionId);store.set(i.sessionId,proof(i));if(create)return create(i);return {sessionId:i.sessionId};},async inspectOwnedCreation(i){if(inspect)return inspect(i,store);return store.get(i.sessionId)??null;}}};
 const open=(extra={})=>host.openOwnedWorkSessionPort(caller,{botId:bot.botId,botEpoch:1,authorityEpoch:1,creation,...producer?{producer}:{},...extra});
 const port=open();const state=()=>port.query({}).work[0];const call=(method,p)=>{const w=state();return port[method](env({delegate:'delegateWorkSession',createSession:'prepareWorkSessionCreation',queueMessage:'prepareWorkSessionDelivery',admit:'admitWorkSession',collect:'collect',resume:'resumeWorkSession',fence:'fenceWorkSession'}[method],p,w?.revision??null,{nativeOwner:1,bot:1,...w?{task:1}:{}}),p);};
 const delegate=()=>call('delegate',{task_id:'w',goal:'Harmless work',completion_condition:'Inspect only'}).result;
 return {ledger,caller,host,bot,adapter,creation,port,calls,store,open,state,call,delegate,command};}
function env(command,p,revision,expectedEpochs){return {command,operationId:randomUUID(),nonce:randomUUID(),payloadDigest:digest(p),expectedRevision:revision,expectedEpochs,authorizationRef:'native-owner',rootHumanInstructionRef:'explicit-offline-fixture',createdAt:new Date().toISOString(),deadline:null};}
test('reserved original-ID creation reuses one intent and cannot forge stock proof with a fixture label',async t=>{const f=await fixture(t);await f.adapter.refreshSessionModeCatalog();const before=f.delegate();const after=await f.call('createSession',{task_id:'w',generation:1});assert.equal(after.sessionId,before.sessionId);assert.equal(after.sessionCreation.state,'created');assert.equal(after.sessionCreation.proofKind,'fixture-contract');assert.equal(after.state,'queued');assert.equal(after.held,false);assert.equal(after.creationState,'reserved');await f.call('createSession',{task_id:'w',generation:1});assert.deepEqual(f.calls,[before.sessionId]);assert.equal(f.ledger.list('creation').length,1);});
test('commit then throw recovers only original ID, mismatch never retries',async t=>{const f=await fixture(t,{create:()=>{throw Error('ambiguous');}});await f.adapter.refreshSessionModeCatalog();const w=f.delegate();assert.equal((await f.call('createSession',{task_id:'w',generation:1})).sessionCreation.state,'created');assert.deepEqual(f.calls,[w.sessionId]);});
test('different-ID creation receipt stays unknown across a second createSession call',async t=>{const f=await fixture(t,{create:()=>({sessionId:'wrong'})});await f.adapter.refreshSessionModeCatalog();f.delegate();assert.equal((await f.call('createSession',{task_id:'w',generation:1})).sessionCreation.state,'unknown');assert.equal((await f.call('createSession',{task_id:'w',generation:1})).sessionCreation.state,'unknown');assert.equal(f.calls.length,1);});
test('fence during native creation prevents late confirmed mapping',async t=>{const gate=deferred(),f=await fixture(t,{create:async i=>{await gate.promise;return {sessionId:i.sessionId};}});await f.adapter.refreshSessionModeCatalog();f.delegate();const pending=f.call('createSession',{task_id:'w',generation:1});await wait();f.call('fence',{task_id:'w',generation:1,reason:'terminate'});gate.resolve();await assert.rejects(pending);assert.equal(f.ledger.list('nativeSession').length,0);assert.equal(f.calls.length,1);});
test('disposed port during native creation prevents late mapping',async t=>{const gate=deferred(),f=await fixture(t,{create:async i=>{await gate.promise;return {sessionId:i.sessionId};}});await f.adapter.refreshSessionModeCatalog();f.delegate();const p=f.call('createSession',{task_id:'w',generation:1});await wait();f.port.dispose();gate.resolve();await assert.rejects(p);assert.equal(f.ledger.list('nativeSession').length,0);});
test('fixture historical creation field survives synthetic receipts and generation2 reuse without driver call',async t=>{let binding,seq=1;const runtime={kind:'offline-synthetic',sourceId:'synthetic-only',async start(b){binding=b;return {receiptId:'r1',sourceId:this.sourceId,sourceSeq:seq,binding:b,state:'waiting',execution:'quiescent',creation:'unknown'};},async inspect(){return null;}};const f=await fixture(t,{runtime});await f.adapter.refreshSessionModeCatalog();f.delegate();const created=await f.call('createSession',{task_id:'w',generation:1});f.call('admit',{task_id:'w',generation:1});await wait();assert.deepEqual(f.state().sessionCreation,created.sessionCreation);f.call('resume',{task_id:'w',generation:1});const original=structuredClone(f.ledger.list('creation')[0]);const reused=await f.call('createSession',{task_id:'w',generation:2});assert.equal(reused.sessionId,created.sessionId);assert.equal(f.calls.length,1);assert.deepEqual(f.ledger.list('creation')[0],original);assert.deepEqual(reused.sessionCreation,created.sessionCreation);assert.equal(reused.generation,2);});
test('producer export exists for explicitly installed private owner only',async()=>{let product;try{product=await import('../src/bot-producer.mjs');}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}assert.equal(typeof product?.installOwnedBotProducer,'function','missing private producer feature');});

function producerFixture({failSend=false,failRead=false}={}){const log=new Map(),calls=[];return {log,calls,provenance:{producerId:'fixture-producer',ingress:'owner',originSessionId:'fixture-contact'},isCurrent:()=>true,createMessage:(b,provenance,text)=>({id:randomUUID(),role:'user',source:{kind:'dsh-bot',...provenance,...b},content:[{type:'text',text}]}),async send(b,message){calls.push(message.id);log.set(message.id,structuredClone(message));if(failSend)throw Error('ambiguous send');},async inspect(b,message){return !failRead&&JSON.stringify(log.get(message.id))===JSON.stringify(message);}};}
for(const failSend of [false,true])test(`queue original identity reconciles without resend after ambiguous=${failSend}`,async t=>{const producer=producerFixture({failSend}),f=await fixture(t,{producer});f.delegate();await f.call('createSession',{task_id:'w',generation:1});const first=await f.call('queueMessage',{task_id:'w',generation:1});assert.equal(first.delivery.state,'durably-queued');const repeated=await f.call('queueMessage',{task_id:'w',generation:1});assert.equal(repeated.delivery.messageId,first.delivery.messageId);assert.equal(producer.calls.length,1);assert.equal(repeated.held,false);assert.equal(repeated.state,'queued');});
test('failed delivery read stays unknown then reconciles only original message',async t=>{const producer=producerFixture({failRead:true}),f=await fixture(t,{producer});f.delegate();await f.call('createSession',{task_id:'w',generation:1});const first=await f.call('queueMessage',{task_id:'w',generation:1});assert.equal(first.delivery.state,'unknown');assert.equal((await f.call('queueMessage',{task_id:'w',generation:1})).delivery.state,'unknown');assert.equal(producer.calls.length,1);});
test('one retained creation factory across owner ports and retries after uncertainty',async t=>{const f=await fixture(t,{inspect:()=>null});let factoryCalls=0;const creation={cwd:'/fixture',portFor:()=>{factoryCalls++;return f.creation.port;}};const a=f.open({creation}),b=f.open({creation});f.delegate();const payload={task_id:'w',generation:1};for(const port of [a,b]){const w=port.query({}).work[0];await port.createSession(env('prepareWorkSessionCreation',payload,w.revision,{nativeOwner:1,bot:1,task:1}),payload);}assert.equal(factoryCalls,1);assert.equal(f.calls.length,1);});
test('new delivery never projects success after owner revocation during awaited inspection',async t=>{const gate=deferred(),producer=producerFixture();producer.inspect=async()=>{await gate.promise;return true;};const f=await fixture(t,{producer});f.delegate();await f.call('createSession',{task_id:'w',generation:1});const pending=f.call('queueMessage',{task_id:'w',generation:1});await wait();const grant=f.ledger.get('grant','native-owner');f.ledger.put('grant','native-owner',{...grant,active:false});gate.resolve();await assert.rejects(pending);assert.equal(f.ledger.list('workDelivery')[0].state,'unknown');assert.equal(producer.calls.length,1);});
test('invalid asynchronous creation factory is retained once and cannot be retried',async t=>{const f=await fixture(t);let calls=0;const port=f.open({creation:{cwd:'/fixture',portFor:()=>{calls++;return Promise.resolve(f.creation.port);}}});f.delegate();const target={task_id:'w',generation:1};for(let n=0;n<2;n++)await assert.rejects(()=>port.createSession(env('prepareWorkSessionCreation',target,f.state().revision,{nativeOwner:1,bot:1,task:1}),target),{code:'invalid_creation_port'});assert.equal(calls,1);assert.equal(f.calls.length,0);});
test('open-time fixture port methods cannot be swapped before creation',async t=>{const f=await fixture(t);f.creation.port.createOwnedSession=async()=>{throw Error('replacement must not run');};f.delegate();const created=await f.call('createSession',{task_id:'w',generation:1});assert.equal(created.sessionCreation.state,'created');assert.equal(f.calls.length,1);});
