/** Product producer with actual native SDK loop and synthetic SSE; model I/O is zero. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {scopeOf} from '@deepseek-ai/dsh-scope';
import {SessionCreationDriver} from '../src/session-creation.mjs';
import {installOwnedBotProducer,prepareOwnedBotProducer} from '../src/bot-producer.mjs';
import {generationFixture,syntheticResponse,tick,observeUntil} from './work-generation-fixture.mjs';

test('restored definition registration requires an exact private lifecycle grant before touching the native registry',async t=>{
 const f=await generationFixture(t),i=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},1),p=f.host.adapter.ownedGenerationCreationPort([i.sessionId],{scopeOf,role:'main',prepareGeneration:x=>f.prepareGeneration(x,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:p}).run(f.caller,i.operationId),agent=f.ctx.agents.get(i.sessionId);
 const preparation=prepareOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originSessionId:i.sessionId,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'synthetic-restored-registration'});
 assert.equal(typeof preparation.bindRestoredDelegate,'function');assert.throws(()=>preparation.bindRestoredDelegate(agent,created,p),{code:'unsupported_owned_bot_restore'});
 assert.equal(f.ctx.tools.schemas(agent).length,0);assert.equal(f.requests(),0);
});

test('actual SDK synthetic producer prepares work before create and routes original result through protected main',async t=>{
 const f=await generationFixture(t,()=>syntheticResponse()),intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision);
 const mainPort=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',prepareGeneration:i=>f.prepareGeneration(i,'main'),isCurrent:()=>true});
 const created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,intent.operationId);assert.equal(created.state,'created');const main=f.ctx.agents.get(intent.sessionId);
 let prepared=0;const done=Promise.withResolvers();
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:main,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'explicit-keyless-synthetic-generation',execution:{beforeExecute:async()=>{},onObserved:()=>done.resolve(),onFailure:code=>done.reject(Error(code)),generationControl:{prepareWorkGeneration:i=>{prepared++;return f.prepareGeneration(i);},bindMainDelegateTool:d=>f.host.adapter.bindOwnedMainGeneration(mainPort,created,d)}}});t.after(()=>producer.dispose());
 const work=await producer.delegate({operationId:'producer-generation',nonce:'producer-generation',task_id:'producer-work',goal:'Return synthetic work result',completion_condition:'Observe original native receipt'});assert.equal(work.sessionCreation.state,'created');assert.equal(prepared,1);
 await producer.execute({task_id:work.task_id,generation:work.generation});
 let timeout;try{await Promise.race([done.promise,new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('synthetic_result_route_timeout')),2000);})]);}finally{clearTimeout(timeout);}
 await f.waitRequest(2);assert.equal(f.requests(),2);
 const workGeneration=f.ledger.list('workGeneration')[0];assert.equal(workGeneration.generationObservation.settlementVerified,true);assert.equal(workGeneration.held,false);assert.equal(workGeneration.state,'waiting');
 const rows=f.ledger.list('ownedMainGeneration');assert.equal(rows.length,1);assert.equal(rows[0].binding.kind,'work-result');assert.equal(rows[0].binding.parentWorkBinding.sessionId,work.sessionId);assert.equal(f.ledger.list('workObservedResponse')[0].generationBinding.inputMessageId,rows[0].binding.inputMessageId);
});

test('actual protected work continuation keeps original session and never repeats an original operation',async t=>{
 const f=await generationFixture(t,()=>syntheticResponse()),intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),mainPort=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',prepareGeneration:i=>f.prepareGeneration(i,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,intent.operationId),main=f.ctx.agents.get(intent.sessionId);
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:main,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'keyless-native-continuation',execution:{beforeExecute:async()=>{},generationControl:{prepareWorkGeneration:i=>f.prepareGeneration(i),bindMainDelegateTool:d=>f.host.adapter.bindOwnedMainGeneration(mainPort,created,d)}}});t.after(()=>producer.dispose());const work=await producer.delegate({operationId:'continue-delegate',nonce:'continue-delegate',task_id:'continue-work',goal:'Synthetic original work',completion_condition:'Keep same native session'});await producer.execute({task_id:work.task_id,generation:1});await observeUntil(()=>producer.query({task_ids:['continue-work']}),value=>value.work[0].nativeRuntimeVerified);
 const original=f.ledger.list('workGeneration')[0],request={operationId:'continue-original-one',nonce:'continue-original-one',taskId:work.taskId,sessionId:work.sessionId,generation:1};assert.equal(producer.canContinueOriginalWork(request),true);const continued=await producer.continueOriginalWork(request);assert.equal(continued.state,'accepted');assert.equal(continued.originalGeneration,1);assert.equal(continued.generation,2);assert.equal(continued.sessionId,work.sessionId);const next=f.ledger.list('workGeneration').find(g=>g.generation===2);assert.notEqual(next.binding.inputMessageId,original.binding.inputMessageId);assert.deepEqual(f.ledger.list('workGeneration').find(g=>g.generation===1).binding,original.binding);
 await observeUntil(()=>producer.inspectOriginalWorkContinuation(request),value=>value.preciseNativeSettlementVerified);const count=f.requests();const repeated=await producer.continueOriginalWork(request);assert.equal(repeated.generation,2);assert.equal(f.requests(),count);assert.equal(f.ledger.list('workGeneration').length,2);await assert.rejects(()=>producer.continueOriginalWork({...request,nonce:'replacement-nonce'}),e=>e.code==='work_continuation_conflict');assert.equal(f.requests(),count);
 const missing=await producer.inspectOriginalWorkContinuation({...request,operationId:'missing-original',nonce:'missing-original'});assert.equal(missing.state,'unknown');assert.equal(f.ledger.list('workContinuation').length,1);
});

test('original UNKNOWN work refuses continuation before allocating any operation or input',async t=>{
 const f=await generationFixture(t,()=>syntheticResponse({finish:false})),intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),mainPort=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',prepareGeneration:i=>f.prepareGeneration(i,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,intent.operationId),main=f.ctx.agents.get(intent.sessionId);
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:main,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'keyless-native-unknown-continuation',execution:{beforeExecute:async()=>{},generationControl:{prepareWorkGeneration:i=>f.prepareGeneration(i),bindMainDelegateTool:d=>f.host.adapter.bindOwnedMainGeneration(mainPort,created,d)}}});t.after(()=>producer.dispose());const work=await producer.delegate({operationId:'unknown-delegate',nonce:'unknown-delegate',task_id:'unknown-work',goal:'Synthetic UNKNOWN work',completion_condition:'Never repeat original'});await producer.execute({task_id:work.task_id,generation:1});await f.ctx.agents.get(work.sessionId).whenIdle();const request={operationId:'unknown-continue',nonce:'unknown-continue',taskId:work.taskId,sessionId:work.sessionId,generation:1};assert.equal(producer.canContinueOriginalWork(request),false);const before=f.ctx.sessions.get(work.sessionId).seq;await assert.rejects(()=>producer.continueOriginalWork(request),e=>e.code==='work_resume_unconfirmed');assert.equal(f.ledger.list('workContinuation').length,0);assert.equal(f.ledger.list('workGeneration').length,1);assert.equal(f.ctx.sessions.get(work.sessionId).seq,before);assert.equal(f.requests(),1);
});
