import test from 'node:test';import assert from 'node:assert/strict';
async function api(){const m=await import('../src/bot-chain-request-guard.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return {};});assert.equal(typeof m.createChainRequestGuard,'function','missing chain request guard');return m;}
const wire=()=>({model:'deepseek-flash',stream:true,max_tokens:256,messages:[{role:'user',content:[{type:'text',text:'Return harmless fixture ONE'}]}],thinking:{type:'disabled'}});
const options=()=>({provider:'deepseek-official',model:'deepseek-flash',reasoningEffort:'off',maxTokens:256,sessionId:'work',messages:[{role:'user',content:[{type:'text',text:'Return harmless fixture ONE'}]}]});
function sse({usage={input_tokens:7,output_tokens:0},final={output_tokens:2},model='deepseek-flash',stop=true}={}){return [`data: ${JSON.stringify({type:'message_start',message:{model,usage}})}\n\n`,`data: ${JSON.stringify({type:'message_delta',delta:{stop_reason:'end_turn'},usage:final})}\n\n`,...stop?[`data: ${JSON.stringify({type:'message_stop'})}\n\n`]:[]];}
async function fixture(t,config={}){const a=await api(),saved=[];let fetches=0;const target={fetch:async(...args)=>{fetches++;return new Response(new ReadableStream({start(c){for(const x of sse(config.response)){const bytes=new TextEncoder().encode(config.splitCrlf?x.replaceAll('\n','\r\n'):x);if(config.splitCrlf)for(const b of bytes)c.enqueue(Uint8Array.of(b));else c.enqueue(bytes);}c.close();}}));}};const g=a.createChainRequestGuard({save:row=>saved.push(structuredClone(row)),fetchTarget:target,timeoutMs:config.timeoutMs??200,...config.guard});t.after(()=>g.dispose());g.bind('work',{kind:'work',isCurrent:()=>true});return {g,saved,target,get fetches(){return fetches;}};}
async function run(f,body=wire(),opts=options(),usage={inputTokens:7,outputTokens:2}){const it=f.g.wrap(opts,()=>({async *[Symbol.asyncIterator](){await f.g.prepareWire({body,sessionId:'work',signal:new AbortController().signal});const response=await f.target.fetch(new Proxy({}, {get(){throw Error('REQUEST_ARGUMENT_INSPECTED');}}),new Proxy({}, {get(){throw Error('AUTH_HEADER_INSPECTED');}}));for await(const unused of response.body){}yield {type:'usage',usage};yield {type:'finish',reason:{kind:'stop'}};}}));for await(const unused of it){}return f.saved.at(-1);}
test('one lazy stock-type streaming request confirms raw model/usage and exact payload digest without inspecting request args',async t=>{const f=await fixture(t);const r=await run(f);assert.equal(r.outcome,'confirmed');assert.equal(r.actualResponseModel,'deepseek-flash');assert.equal(r.rawUsage.input_tokens,7);assert.equal(r.fetchAttempts,1);assert.equal(r.worstReservationCny,2.0992);assert.equal(r.usageUpperCny,0.00003);assert.equal(f.fetches,1);});
for(const missing of ['raw-input','raw-output','raw-model','terminal'])test(`${missing} globally halts new paid effects despite translated usage`,async t=>{const response={usage:{input_tokens:7,output_tokens:0},final:{output_tokens:2},model:'deepseek-flash',stop:true};if(missing==='raw-input')response.usage={};if(missing==='raw-output'){response.usage={input_tokens:7};response.final={};}if(missing==='raw-model')response.model='foreign-model';if(missing==='terminal')response.stop=false;const f=await fixture(t,{response});await assert.rejects(()=>run(f));assert.equal(f.saved.at(-1).outcome,'unresolved');assert.equal(f.g.snapshot().halted,true);await assert.rejects(()=>run(f));assert.equal(f.fetches,1);});
for(const bad of ['overflow','unsafe-block','wrong-cap','foreign-session','extra-body-field'])test(`denies ${bad} before paid effect`,async t=>{const f=await fixture(t),body=wire(),opts=options();if(bad==='overflow')body.messages[0].content[0].text='x'.repeat(65537);if(bad==='unsafe-block')body.messages[0].content=[{type:'image',source:{type:'base64',data:'private'}}];if(bad==='wrong-cap')body.max_tokens=257;if(bad==='foreign-session')opts.sessionId='foreign';if(bad==='extra-body-field')body.unapproved_field='UNSAFE_FIELD';await assert.rejects(()=>run(f,body,opts));assert.equal(f.fetches,0);assert.equal(JSON.stringify(f.saved).includes('UNSAFE_FIELD'),false);});
test('second fetch attempt in same lazy context is denied before effect',async t=>{const f=await fixture(t);await assert.rejects(async()=>{for await(const unused of f.g.wrap(options(),()=>({async *[Symbol.asyncIterator](){await f.g.prepareWire({body:wire(),sessionId:'work',signal:new AbortController().signal});const r=await f.target.fetch({});for await(const x of r.body){}await assert.rejects(()=>f.target.fetch({}));yield {type:'usage',usage:{inputTokens:7,outputTokens:2}};yield {type:'finish',reason:{kind:'stop'}};}}))){} });assert.equal(f.fetches,1);assert.equal(f.saved.at(-1).outcome,'unresolved');});
test('raw and translated disjoint cache counters must agree; count each once',async t=>{const f=await fixture(t,{response:{usage:{input_tokens:7,output_tokens:0,cache_read_input_tokens:3,cache_creation_input_tokens:5}}});const r=await run(f,wire(),options(),{inputTokens:7,outputTokens:2,cacheReadTokens:3,cacheWriteTokens:5});assert.equal(r.outcome,'confirmed');assert.equal(r.usageUpperCny,0.000046);});
test('tenth request is denied; nine completed requests are allowed',async t=>{const f=await fixture(t);for(let n=0;n<9;n++)assert.equal((await run(f)).outcome,'confirmed');await assert.rejects(()=>run(f));assert.equal(f.fetches,9);});
test('clone cancellation at message_stop does not wait on translator branch',async t=>{const a=await api();let source,cancelled=false;const target={fetch:async()=>new Response(new ReadableStream({start(c){source=c;},cancel(){cancelled=true;}}))};const saved=[],g=a.createChainRequestGuard({fetchTarget:target,save:r=>saved.push(r),timeoutMs:500});t.after(()=>g.dispose());g.bind('work',{kind:'work',isCurrent:()=>true});const work=(async()=>{for await(const unused of g.wrap(options(),()=>({async *[Symbol.asyncIterator](){await g.prepareWire({body:wire(),sessionId:'work',signal:new AbortController().signal});const r=await target.fetch({});const reader=r.body.getReader();for(const frame of sse())source.enqueue(new TextEncoder().encode(frame));for(let n=0;n<3;n++)await reader.read();yield {type:'usage',usage:{inputTokens:7,outputTokens:2}};yield {type:'finish',reason:{kind:'stop'}};void reader.cancel();reader.releaseLock();}}))){}return saved.at(-1);})();const r=await Promise.race([work,new Promise((_,reject)=>setTimeout(()=>reject(Error('TEE_DEADLOCK')),1000))]);assert.equal(r.outcome,'confirmed');await new Promise(resolve=>setImmediate(resolve));assert.equal(cancelled,true);});
test('stalled complete SSE observation times out without awaiting original branch',async t=>{const a=await api();let controller,cancelled=false;const target={fetch:async()=>new Response(new ReadableStream({start(c){controller=c;c.enqueue(new TextEncoder().encode(sse()[0]));},cancel(){cancelled=true;}}))};const saved=[],g=a.createChainRequestGuard({fetchTarget:target,save:r=>saved.push(r),timeoutMs:20});t.after(()=>g.dispose());g.bind('work',{kind:'work',isCurrent:()=>true});await assert.rejects(async()=>{for await(const unused of g.wrap(options(),()=>({async *[Symbol.asyncIterator](){await g.prepareWire({body:wire(),sessionId:'work',signal:new AbortController().signal});const r=await target.fetch({});for await(const x of r.body){}yield {type:'finish',reason:{kind:'stop'}};}}))){} });assert.equal(saved.at(-1).outcome,'unresolved');assert.equal(saved.at(-1).errorCategory,'chain_response_timeout');assert.equal(g.snapshot().halted,true);controller.close();await new Promise(resolve=>setImmediate(resolve));});
test('unknown raw accounting rejects stock loop completion with fixed category',async t=>{const f=await fixture(t,{response:{usage:{},final:{output_tokens:2}}});await assert.rejects(()=>run(f),e=>typeof e.code==='string'&&e.message===e.code);assert.equal(f.g.snapshot().requests.at(-1).outcome,'unresolved');assert.equal(f.g.snapshot().halted,true);});
test('raw server output over 256 remains unresolved and rejects completion',async t=>{const f=await fixture(t,{response:{final:{output_tokens:257}}});await assert.rejects(()=>run(f,wire(),options(),{inputTokens:7,outputTokens:257}));assert.equal(f.saved.at(-1).outcome,'unresolved');assert.equal(f.g.snapshot().halted,true);});
test('unconfirmed accounting never publishes usage or finish chunks',async t=>{const f=await fixture(t,{response:{usage:{},final:{output_tokens:2}}}),seen=[];await assert.rejects(async()=>{for await(const chunk of f.g.wrap(options(),()=>({async *[Symbol.asyncIterator](){await f.g.prepareWire({body:wire(),sessionId:'work',signal:new AbortController().signal});const r=await f.target.fetch({});for await(const x of r.body){}yield{type:'usage',usage:{inputTokens:0,outputTokens:2}};yield{type:'finish',reason:{kind:'stop'}};}})))seen.push(chunk.type);});assert.deepEqual(seen,[]);});
test('usage and finish publication follows durable confirmed accounting',async t=>{const f=await fixture(t);for await(const chunk of f.g.wrap(options(),()=>({async *[Symbol.asyncIterator](){await f.g.prepareWire({body:wire(),sessionId:'work',signal:new AbortController().signal});const r=await f.target.fetch({});for await(const x of r.body){}yield{type:'usage',usage:{inputTokens:7,outputTokens:2}};yield{type:'finish',reason:{kind:'stop'}};}}))){assert.equal(f.saved.at(-1).outcome,'confirmed');}assert.equal(f.saved.at(-1).outcome,'confirmed');});

test('raw CRLF SSE split across response chunks confirms bounded accounting',async t=>{const f=await fixture(t,{splitCrlf:true});assert.equal((await run(f)).outcome,'confirmed');});

async function rejectedUsage(f){const seen=[];await assert.rejects(async()=>{for await(const chunk of f.g.wrap(options(),()=>({async *[Symbol.asyncIterator](){await f.g.prepareWire({body:wire(),sessionId:'work',signal:new AbortController().signal});const r=await f.target.fetch({});for await(const x of r.body){}yield{type:'usage',usage:{inputTokens:7,outputTokens:2}};yield{type:'finish',reason:{kind:'stop'}};}})))seen.push(chunk.type);},{code:'chain_raw_usage'});const row=f.saved.at(-1);assert.equal(row.outcome,'unresolved');assert.equal(row.errorCategory,'chain_raw_usage');assert.equal(row.rawTerminalObserved,false);assert.equal(row.fetchAttempts,1);assert.equal(row.worstReservationCny,2.0992);assert.equal(row.usage,undefined);assert.equal(row.usageUpperCny,undefined);assert.equal(f.g.snapshot().halted,true);assert.deepEqual(seen,[]);await assert.rejects(()=>run(f));assert.equal(f.fetches,1);return row;}
test('synthetic decreasing raw input retains bounded rejection facts while accounting stays unknown',async t=>{const f=await fixture(t,{response:{final:{input_tokens:6,output_tokens:2}}});const row=await rejectedUsage(f);assert.equal(row.rawUsage.input_tokens,7);assert.deepEqual(row.rawUsageRejection,{eventType:'message_delta',eventIndex:2,reason:'decreasing',key:'input_tokens',value:6,prior:7});assert.deepEqual(f.g.snapshot().requests.at(-1).rawUsageRejection,row.rawUsageRejection);});
for(const [label,final,expected]of[
 ['negative',{output_tokens:-1},{reason:'negative',key:'output_tokens',value:-1,prior:0}],
 ['string',{input_tokens:'PRIVATE_USAGE_STRING_DO_NOT_SAVE'},{reason:'invalid-integer',key:'input_tokens',valueType:'string',prior:7}],
 ['object',{input_tokens:{note:'PRIVATE_USAGE_OBJECT_DO_NOT_SAVE'}},{reason:'invalid-integer',key:'input_tokens',valueType:'object',prior:7}],
 ['invalid-usage-object','PRIVATE_USAGE_OBJECT_SHAPE_DO_NOT_SAVE',{reason:'invalid-object',valueType:'string'}],
 ['unsafe-number',{input_tokens:1e100},{reason:'invalid-integer',key:'input_tokens',valueType:'number',prior:7}],
])test(`raw ${label} rejection saves only fixed categories and bounded values`,async t=>{const f=await fixture(t,{response:{final}});const row=await rejectedUsage(f);assert.deepEqual(row.rawUsageRejection,{eventType:'message_delta',eventIndex:2,...expected});assert.equal(JSON.stringify(f.saved).includes('PRIVATE_USAGE_'),false);assert.equal(JSON.stringify(f.saved).includes('1e+100'),false);});
