/** Product producer with actual native SDK loop and synthetic SSE; model I/O is zero. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {scopeOf} from '@deepseek-ai/dsh-scope';
import {createUserMessage} from '@deepseek-ai/dsh-llm';
import {SessionCreationDriver} from '../src/session-creation.mjs';
import {installOwnedBotProducer,prepareOwnedBotProducer} from '../src/bot-producer.mjs';
import {generationFixture,syntheticResponse,tick,observeUntil} from './work-generation-fixture.mjs';
import {createOwnedMainGenerationBridge} from '../src/owned-main-generation.mjs';

for(const known of [true,false])test(`Continue coordinates an exact in-flight original lookup under official modes (${known?'known':'UNKNOWN'})`,async t=>{
 const initialization=Object.freeze({permissionPreset:'workspace-write',sandboxMode:'workspace-write',approvalPolicy:'ask'}),f=await generationFixture(t,()=>syntheticResponse({finish:known}),{initialization}),intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),mainPort=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',initialization,prepareGeneration:i=>f.prepareGeneration(i,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,intent.operationId);
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:f.ctx.agents.get(intent.sessionId),botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'synthetic-original-lookup-coordination',execution:{beforeExecute:async()=>{},generationControl:{initialization,prepareWorkGeneration:i=>f.prepareGeneration(i),bindMainDelegateTool:d=>f.host.adapter.bindOwnedMainGeneration(mainPort,created,d)}}});t.after(()=>producer.dispose());
 const work=await producer.delegate({operationId:'lookup-work-'+known,nonce:'lookup-work-'+known,task_id:'lookup-work',goal:'Original work while a read is already inspecting it',completion_condition:'Continue only after genuine known proof'});await producer.execute({task_id:work.task_id,generation:1});
 const request={operationId:'lookup-continue-'+known,nonce:'lookup-continue-'+known,taskId:work.taskId,sessionId:work.sessionId,generation:1};if(known)await observeUntil(()=>producer.canContinueOriginalWork(request),value=>value===true);else await f.ctx.agents.get(work.sessionId).whenIdle();
 const reader=f.host.openOwnedWorkSessionPort(f.caller,{botId:f.bot.botId,botEpoch:1,authorityEpoch:1}),beforeGenerations=f.ledger.list('workGeneration'),beforeInputs=f.ledger.list('workInput'),beforeRequests=f.requests(),read=reader.collect({task_id:work.task_id,generation:1});t.after(()=>reader.dispose());
 // collect retains the real SDK lookup synchronously; Continue arrives before its microtask finishes.
 const continuation=producer.continueOriginalWork(request);continuation.catch(()=>{});const original=await read;assert.equal(original.generation,1);assert.equal(original.nativeRuntimeVerified,known);
 if(known){const result=await continuation;assert.equal(result.state,'accepted');assert.equal(result.generation,2);assert.equal(result.sessionId,work.sessionId);await observeUntil(()=>producer.inspectOriginalWorkContinuation(request),value=>value.preciseNativeSettlementVerified);assert.equal(f.ledger.list('workContinuation').length,1);assert.equal(f.ledger.list('workGeneration').length,2);assert.equal(f.ledger.list('workDelivery').filter(row=>row.generation===2).length,1);assert.equal(f.ledger.list('workGeneration').find(g=>g.generation===1).binding.inputMessageId,beforeGenerations[0].binding.inputMessageId);}else{await assert.rejects(()=>continuation,{code:'work_resume_unconfirmed'});assert.equal(f.ledger.list('workContinuation').length,0);const immutable=rows=>rows.map(({binding,slotLease,generation,held})=>({binding,slotLease,generation,held}));assert.deepEqual(immutable(f.ledger.list('workGeneration')),immutable(beforeGenerations));assert.equal(producer.query({}).work[0].generationObservation.remote,'UNKNOWN');assert.deepEqual(f.ledger.list('workInput'),beforeInputs);assert.equal(f.requests(),beforeRequests);}
});

test('Continue waits for the original work result to enter main before allocating a new operation',async t=>{
 let source;
 const f=await generationFixture(t,()=>syntheticResponse()),intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),mainPort=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',prepareGeneration:i=>f.prepareGeneration(i,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,intent.operationId);
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:f.ctx.agents.get(intent.sessionId),botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'synthetic-result-before-continue',execution:{beforeExecute:async()=>{},generationControl:{prepareWorkGeneration:i=>f.prepareGeneration(i),bindMainDelegateTool:d=>{source=f.host.adapter.bindOwnedMainGeneration(mainPort,created,d);return source;}}}});t.after(()=>producer.dispose());
 const bridge=createOwnedMainGenerationBridge({host:f.host,ownerCtx:f.ctx,source,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,sessionId:intent.sessionId,configVersion:f.bot.configVersion}),admission=await bridge.admit(()=>{}),prior=admission.start({kind:'contact',taskId:f.bot.botId,taskEpoch:1,taskRevision:1,operationId:'prior-main-contact',nonce:'prior-main-contact',message:createUserMessage({content:[{type:'text',text:'Prior actual main receipt'}],source:{kind:'user'}})},()=>{});admission.release();await observeUntil(()=>bridge.inspect(prior.binding,()=>{}),r=>r.generationObservation.settlementVerified);
 const work=await producer.delegate({operationId:'before-route-work',nonce:'before-route-work',task_id:'before-route-work',goal:'Original work before asynchronous result routing',completion_condition:'Deliver its exact original result to main'}),blocked=Promise.withResolvers(),release=Promise.withResolvers();t.after(()=>release.resolve());
 // Hold the real durable flush after the SDK receipt, without changing its return value or evidence.
 const sessions=f.ctx.sessions,flush=sessions.flush;let didBlock=false;
 sessions.flush=async function(session){if(!didBlock&&session.id===work.sessionId&&f.ledger.list('workGeneration').some(g=>g.sessionId===work.sessionId&&g.generationObservation.settlementVerified)&&new Error().stack.includes('/src/bot-producer.mjs')){didBlock=true;blocked.resolve();await release.promise;}return flush.call(this,session);};t.after(()=>{sessions.flush=flush;});
 await producer.execute({task_id:work.task_id,generation:1});let timer;try{await Promise.race([blocked.promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('SYNTHETIC_PRE_ROUTE_BARRIER_NOT_REACHED')),2000);})]);}finally{clearTimeout(timer);}
 const request={operationId:'before-route-continue',nonce:'before-route-continue',taskId:work.taskId,sessionId:work.sessionId,generation:1},beforeGenerations=f.ledger.list('workGeneration'),beforeInputs=f.ledger.list('workInput'),beforeRequests=f.requests();
 try{assert.equal(producer.query({}).work[0].nativeRuntimeVerified,true);assert.equal(f.ledger.list('workObservedResponse').length,0);assert.equal(producer.canContinueOriginalWork(request),false);await assert.rejects(()=>producer.continueOriginalWork(request),{code:'work_result_route_unconfirmed'});assert.equal(f.ledger.list('workContinuation').length,0);assert.deepEqual(f.ledger.list('workGeneration'),beforeGenerations);assert.deepEqual(f.ledger.list('workInput'),beforeInputs);assert.equal(f.requests(),beforeRequests);}finally{release.resolve();}
 await observeUntil(async()=>{const route=f.ledger.list('workObservedResponse')[0];return route?.generationBinding&&route.routing==='durably-queued'?bridge.inspect(route.generationBinding,()=>{}):null;},r=>r?.generationObservation.settlementVerified);
 assert.equal(producer.canContinueOriginalWork(request),true);assert.equal((await producer.continueOriginalWork(request)).generation,2);
});

test('Continue waits for the exact pending main result receipt before allocating a new work generation',async t=>{
 const mainResponse=Promise.withResolvers();t.after(()=>mainResponse.resolve(syntheticResponse()));let calls=0,source;
 const f=await generationFixture(t,()=>++calls===2?mainResponse.promise:syntheticResponse()),i=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},1),p=f.host.adapter.ownedGenerationCreationPort([i.sessionId],{scopeOf,role:'main',prepareGeneration:x=>f.prepareGeneration(x,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:p}).run(f.caller,i.operationId);
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:f.ctx.agents.get(i.sessionId),botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'synthetic-main-before-continue',execution:{beforeExecute:async()=>{},generationControl:{prepareWorkGeneration:x=>f.prepareGeneration(x),bindMainDelegateTool:d=>{source=f.host.adapter.bindOwnedMainGeneration(p,created,d);return source;}}}});t.after(()=>producer.dispose());
 const work=await producer.delegate({operationId:'pending-main-work',nonce:'pending-main-work',task_id:'pending-main-work',goal:'Synthetic work before main receipt',completion_condition:'Keep original main result protected'});await producer.execute({task_id:work.task_id,generation:1});await f.waitRequest(2);await observeUntil(()=>producer.query({}),s=>s.work[0].nativeRuntimeVerified);
 const request={operationId:'pending-main-continue',nonce:'pending-main-continue',taskId:work.taskId,sessionId:work.sessionId,generation:1},before=f.ledger.list('workGeneration');assert.equal(producer.canContinueOriginalWork(request),false);await assert.rejects(()=>producer.continueOriginalWork(request),{code:'main_generation_unsettled'});assert.deepEqual(f.ledger.list('workGeneration'),before);assert.equal(f.ledger.list('workContinuation').length,0);assert.equal(f.requests(),2);
 mainResponse.resolve(syntheticResponse());const binding=f.ledger.list('ownedMainGeneration')[0].binding,bridge=createOwnedMainGenerationBridge({host:f.host,ownerCtx:f.ctx,source,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,sessionId:i.sessionId,configVersion:f.bot.configVersion});await observeUntil(()=>bridge.inspect(binding,()=>{}),r=>r.generationObservation.settlementVerified);assert.equal(producer.canContinueOriginalWork(request),true);assert.equal((await producer.continueOriginalWork(request)).generation,2);
});

test('restored definition registration requires an exact private lifecycle grant before touching the native registry',async t=>{
 const f=await generationFixture(t),i=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},1),p=f.host.adapter.ownedGenerationCreationPort([i.sessionId],{scopeOf,role:'main',prepareGeneration:x=>f.prepareGeneration(x,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:p}).run(f.caller,i.operationId),agent=f.ctx.agents.get(i.sessionId);
 const preparation=prepareOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originSessionId:i.sessionId,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'synthetic-restored-registration'});
 assert.equal(typeof preparation.bindRestoredDelegate,'function');assert.throws(()=>preparation.bindRestoredDelegate(agent,created,p),{code:'unsupported_owned_bot_restore'});
 assert.equal(f.ctx.tools.schemas(agent).length,0);assert.equal(f.requests(),0);
});

test('actual SDK synthetic producer prepares work before create and routes original result through protected main',async t=>{
 const f=await generationFixture(t,()=>syntheticResponse()),intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision);
 const mainPort=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',prepareGeneration:i=>f.prepareGeneration(i,'main'),isCurrent:()=>true});
 const created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,intent.operationId);assert.equal(created.state,'created');const main=f.ctx.agents.get(intent.sessionId);
 let prepared=0;const done=Promise.withResolvers();
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:main,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'explicit-keyless-synthetic-generation',execution:{beforeExecute:async()=>{},onObserved:()=>done.resolve(),onFailure:code=>done.reject(Error(code)),generationControl:{prepareWorkGeneration:i=>{prepared++;return f.prepareGeneration(i);},bindMainDelegateTool:d=>f.host.adapter.bindOwnedMainGeneration(mainPort,created,d)}}});t.after(()=>producer.dispose());
 const work=await producer.delegate({operationId:'producer-generation',nonce:'producer-generation',task_id:'producer-work',goal:'Return synthetic work result',completion_condition:'Observe original native receipt'});assert.equal(work.sessionCreation.state,'created');assert.equal(prepared,1);
 await producer.execute({task_id:work.task_id,generation:work.generation});
 let timeout;try{await Promise.race([done.promise,new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('synthetic_result_route_timeout')),2000);})]);}finally{clearTimeout(timeout);}
 await f.waitRequest(2);assert.equal(f.requests(),2);
 const workGeneration=f.ledger.list('workGeneration')[0];assert.equal(workGeneration.generationObservation.settlementVerified,true);assert.equal(workGeneration.held,false);assert.equal(workGeneration.state,'waiting');
 const rows=f.ledger.list('ownedMainGeneration');assert.equal(rows.length,1);assert.equal(rows[0].binding.kind,'work-result');assert.equal(rows[0].binding.parentWorkBinding.sessionId,work.sessionId);assert.equal(f.ledger.list('workObservedResponse')[0].generationBinding.inputMessageId,rows[0].binding.inputMessageId);
});

test('actual protected work continuation keeps original session and never repeats an original operation',async t=>{
 const f=await generationFixture(t,()=>syntheticResponse()),intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),mainPort=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',prepareGeneration:i=>f.prepareGeneration(i,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,intent.operationId),main=f.ctx.agents.get(intent.sessionId);
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:main,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'keyless-native-continuation',execution:{beforeExecute:async()=>{},generationControl:{prepareWorkGeneration:i=>f.prepareGeneration(i),bindMainDelegateTool:d=>f.host.adapter.bindOwnedMainGeneration(mainPort,created,d)}}});t.after(()=>producer.dispose());const work=await producer.delegate({operationId:'continue-delegate',nonce:'continue-delegate',task_id:'continue-work',goal:'Synthetic original work',completion_condition:'Keep same native session'});await producer.execute({task_id:work.task_id,generation:1});await observeUntil(()=>producer.query({task_ids:['continue-work']}),value=>value.work[0].nativeRuntimeVerified);
 const original=f.ledger.list('workGeneration')[0],request={operationId:'continue-original-one',nonce:'continue-original-one',taskId:work.taskId,sessionId:work.sessionId,generation:1};await observeUntil(()=>producer.canContinueOriginalWork(request),v=>v===true);assert.equal(producer.canContinueOriginalWork(request),true);const continued=await producer.continueOriginalWork(request);assert.equal(continued.state,'accepted');assert.equal(continued.originalGeneration,1);assert.equal(continued.generation,2);assert.equal(continued.sessionId,work.sessionId);const next=f.ledger.list('workGeneration').find(g=>g.generation===2);assert.notEqual(next.binding.inputMessageId,original.binding.inputMessageId);assert.deepEqual(f.ledger.list('workGeneration').find(g=>g.generation===1).binding,original.binding);
 await observeUntil(()=>producer.inspectOriginalWorkContinuation(request),value=>value.preciseNativeSettlementVerified);const count=f.requests();const repeated=await producer.continueOriginalWork(request);assert.equal(repeated.generation,2);assert.equal(f.requests(),count);assert.equal(f.ledger.list('workGeneration').length,2);await assert.rejects(()=>producer.continueOriginalWork({...request,nonce:'replacement-nonce'}),e=>e.code==='work_continuation_conflict');assert.equal(f.requests(),count);
 const missing=await producer.inspectOriginalWorkContinuation({...request,operationId:'missing-original',nonce:'missing-original'});assert.equal(missing.state,'unknown');assert.equal(f.ledger.list('workContinuation').length,1);
});

test('original UNKNOWN work refuses continuation before allocating any operation or input',async t=>{
 const f=await generationFixture(t,()=>syntheticResponse({finish:false})),intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),mainPort=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',prepareGeneration:i=>f.prepareGeneration(i,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,intent.operationId),main=f.ctx.agents.get(intent.sessionId);
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:main,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'keyless-native-unknown-continuation',execution:{beforeExecute:async()=>{},generationControl:{prepareWorkGeneration:i=>f.prepareGeneration(i),bindMainDelegateTool:d=>f.host.adapter.bindOwnedMainGeneration(mainPort,created,d)}}});t.after(()=>producer.dispose());const work=await producer.delegate({operationId:'unknown-delegate',nonce:'unknown-delegate',task_id:'unknown-work',goal:'Synthetic UNKNOWN work',completion_condition:'Never repeat original'});await producer.execute({task_id:work.task_id,generation:1});await f.ctx.agents.get(work.sessionId).whenIdle();const request={operationId:'unknown-continue',nonce:'unknown-continue',taskId:work.taskId,sessionId:work.sessionId,generation:1};assert.equal(producer.canContinueOriginalWork(request),false);const before=f.ctx.sessions.get(work.sessionId).seq;await assert.rejects(()=>producer.continueOriginalWork(request),e=>e.code==='work_resume_unconfirmed');assert.equal(f.ledger.list('workContinuation').length,0);assert.equal(f.ledger.list('workGeneration').length,1);assert.equal(f.ctx.sessions.get(work.sessionId).seq,before);assert.equal(f.requests(),1);
});
