import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture,createBot } from './helpers.mjs';
function setup() { const f=fixture(); const bots=['A','B','C'].map(n=>createBot(f,n)); const g1=f.cmd('createGroup',{name:'G1',members:bots.map(b=>b.botId),coordinatorBotId:bots[0].botId,namespace:'G1'}).result; const g2=f.cmd('createGroup',{name:'G2',members:[bots[0].botId,bots[1].botId],coordinatorBotId:bots[0].botId,namespace:'G2'}).result; return {...f,bots,g1,g2}; }
test('F16 canonical aliases deduplicate to one delivery and preserve group context',()=>{const f=setup(); const r=f.cmd('sendMessage',{groupId:f.g1.groupId,content:'quoted @C does not route',recipients:['A','a',f.bots[0].botId]}).result; assert.equal(r.deliveries.length,1); assert.equal(r.deliveries[0].botId,f.bots[0].botId); assert.equal(r.message.namespace,'G1'); assert.equal(r.message.producer.kind,'human'); assert.equal(r.deliveries[0].state,'blocked_native'); f.ledger.close();});
test('ordinary group input only targets configured coordinator',()=>{const f=setup();const r=f.cmd('sendMessage',{groupId:f.g2.groupId,content:'ordinary new topic @C in quotation',recipients:[]}).result;assert.deepEqual(r.deliveries.map(x=>x.botId),[f.bots[0].botId]);f.ledger.close();});
test('F16 removal revokes only that member and rejoining gets new generation',()=>{const f=setup();const r=f.cmd('sendMessage',{groupId:f.g1.groupId,content:'hi',recipients:['A','B']}).result;let g=f.cmd('changeMembership',{groupId:f.g1.groupId,remove:[f.bots[0].botId],add:[]},f.g1.revision).result;assert.equal(f.ledger.get('delivery',r.deliveries[0].deliveryId).state,'revoked');assert.equal(f.ledger.get('delivery',r.deliveries[1].deliveryId).state,'blocked_native');g=f.cmd('changeMembership',{groupId:g.groupId,remove:[],add:[f.bots[0].botId]},g.revision).result;assert.equal(g.members[f.bots[0].botId].generation,2);f.ledger.close();});
test('F18 two meetings retain independent topics and sealed opinions',()=>{const f=setup();const a=f.cmd('startMeeting',{groupId:f.g1.groupId,topic:'TOPIC-ONE',materials:[{namespace:'G1',text:'MARKER-G1',version:'1'}],maxOpinions:3}).result;const b=f.cmd('startMeeting',{groupId:f.g1.groupId,topic:'TOPIC-TWO',materials:[{namespace:'G1',text:'OTHER',version:'2'}],maxOpinions:3}).result;const o=f.cmd('submitOpinion',{meetingId:a.meetingId,botId:f.bots[0].botId,content:'manual independent opinion'},a.revision).result;assert.equal(o.sealed,true);assert.equal(o.producer.kind,'human');assert.equal(f.host.publicMeeting(a.meetingId).opinions.length,0);assert.equal(f.host.publicMeeting(b.meetingId).topic,'TOPIC-TWO');assert.equal(f.host.publicMeeting(b.meetingId).received,0);f.ledger.close();});
test('F17 empty topic and cross-namespace materials are rejected',()=>{const f=setup();assert.throws(()=>f.cmd('startMeeting',{groupId:f.g1.groupId,topic:' ',materials:[],maxOpinions:3}),{code:'invalid_payload'});assert.throws(()=>f.cmd('startMeeting',{groupId:f.g1.groupId,topic:'real',materials:[{namespace:'G2',text:'forbidden',version:'1'}],maxOpinions:3}),{code:'scope_denied'});f.ledger.close();});
test('F18 reveal requires complete sealed phase and never invents missing opinions',()=>{const f=setup();let m=f.cmd('startMeeting',{groupId:f.g2.groupId,topic:'decide',materials:[],maxOpinions:2}).result;assert.throws(()=>f.cmd('revealOpinions',{meetingId:m.meetingId},m.revision),{code:'waiting_opinions'});for(const botId of Object.keys(m.participants)){f.cmd('submitOpinion',{meetingId:m.meetingId,botId,content:'manually entered'},m.revision);m=f.ledger.get('meeting',m.meetingId);}const visible=f.cmd('revealOpinions',{meetingId:m.meetingId},m.revision).result;assert.equal(visible.opinions.length,2);assert.equal(visible.nativeMeetingVerified,false);f.ledger.close();});
test('F19 duplicate obligation never consumes a second opinion budget',()=>{const f=setup();const m=f.cmd('startMeeting',{groupId:f.g2.groupId,topic:'decide',materials:[],maxOpinions:2}).result;f.cmd('submitOpinion',{meetingId:m.meetingId,botId:f.bots[0].botId,content:'one'},m.revision);const now=f.ledger.get('meeting',m.meetingId);assert.throws(()=>f.cmd('submitOpinion',{meetingId:m.meetingId,botId:f.bots[0].botId,content:'two'},now.revision),{code:'obligation_conflict'});assert.equal(f.ledger.get('meeting',m.meetingId).budget.usedOpinions,1);f.ledger.close();});
test('F05 late opinion after membership removal cannot be sealed',()=>{const f=setup();const m=f.cmd('startMeeting',{groupId:f.g1.groupId,topic:'decide',materials:[],maxOpinions:3}).result;f.cmd('changeMembership',{groupId:f.g1.groupId,remove:[f.bots[0].botId],add:[]},f.g1.revision);assert.throws(()=>f.cmd('submitOpinion',{meetingId:m.meetingId,botId:f.bots[0].botId,content:'late'},m.revision),{code:'membership_revoked'});f.ledger.close();});
