/** Exact SDK window projection with actual native activity, synthetic SSE only. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {scopeOf} from '@deepseek-ai/dsh-scope';
import {defineTool} from '@deepseek-ai/dsh-tools';
import {createUserMessage} from '@deepseek-ai/dsh-llm';
import {SessionCreationDriver} from '../src/session-creation.mjs';
import {createOwnedMainGenerationBridge} from '../src/owned-main-generation.mjs';
import {projectOwnedGenerationEvents} from '../src/owned-generation-input-window.mjs';
import {generationFixture,observeUntil} from './work-generation-fixture.mjs';

test('genuine receipt window ends before the next original input and cannot be copied',async t=>{const f=await generationFixture(t);assert.equal(typeof f.Native.getOwnedGenerationReceiptInputWindow,'function','M2_NATIVE_INPUT_WINDOW_REQUIRED');const intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),port=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',prepareGeneration:i=>f.prepareGeneration(i,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port}).run(f.caller,intent.operationId),agent=f.ctx.agents.get(intent.sessionId),definition=defineTool({name:'dsh_bot_delegate',description:'Synthetic exact window delegate',parameters:{},output:{schema:{type:'object'},render:()=>[]},async execute(){return{};}});agent.ctx.tools.register(definition);const source=f.host.adapter.bindOwnedMainGeneration(port,created,definition),bridge=createOwnedMainGenerationBridge({host:f.host,ownerCtx:f.ctx,source,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,sessionId:intent.sessionId,configVersion:f.bot.configVersion});const send=async id=>{const admission=await bridge.admit(()=>{});try{return admission.start({kind:'contact',taskId:id,taskEpoch:1,taskRevision:1,operationId:id,nonce:id,message:createUserMessage({source:{kind:'user'},content:[{type:'text',text:id}]})},()=>{});}finally{admission.release();}};const first=await send('window-first');await observeUntil(()=>bridge.inspect(first.binding,()=>{}),v=>v.generationObservation.settlementVerified);const window=await bridge.ownedEventWindow(first.binding,()=>{});const second=await send('window-second'),events=agent.session.snapshotEvents(),projected=projectOwnedGenerationEvents(window,events);assert.equal(projected.every(e=>e.seq<window.endSeq),true);assert.equal(projected.some(e=>e.type==='agent/inbox/spliced'&&e.data.inserted.some(m=>m.id===second.binding.inputMessageId)),false);assert.deepEqual(projected.filter(e=>e.type==='user/message').map(e=>e.data.id),[first.binding.inputMessageId]);assert.throws(()=>projectOwnedGenerationEvents({...window},events),{code:'owned_input_window_required'});});
