/** Product full-tree lifecycle over actual SDK handles/journals; keyless synthetic SSE only. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {mkdtemp} from 'node:fs/promises';
import {scopeOf} from '@deepseek-ai/dsh-scope';
import {symbols} from '@deepseek-ai/cordis';
import {HostConnectionService} from '@deepseek-ai/dsh-client-connection';
import {Ledger} from '../src/ledger.mjs';
import {SessionCreationDriver} from '../src/session-creation.mjs';
import {prepareOwnedBotProducer} from '../src/bot-producer.mjs';
import {installSelectedBotContactOwner} from '../src/selected-bot-contact-owner.mjs';
import {canonical} from '../src/errors.mjs';
import {isOwnedBotLifecycleRestoreGrant,describeOwnedBotLifecycleRestore} from '../src/owned-bot-lifecycle.mjs';
import {generationFixture,route,syntheticResponse,observeUntil} from './work-generation-fixture.mjs';

function toolResponse(){const events=[{type:'message_start',message:{usage:{input_tokens:5}}},{type:'content_block_start',index:0,content_block:{type:'tool_use',id:crypto.randomUUID(),name:'dsh_bot_delegate',input:{task_id:'lifecycle-child',goal:'lifecycle-child-work',completion_condition:'Keep original child provenance'}}},{type:'content_block_stop',index:0},{type:'message_delta',delta:{stop_reason:'tool_use'},usage:{output_tokens:3}},{type:'message_stop'}];return new Response(events.map(event=>'data: '+JSON.stringify(event)+'\n\n').join(''));}
function transport(unknownChild=false){return(_url,init)=>{const wire=JSON.stringify(JSON.parse(init.body).messages);if(wire.includes('Goal: lifecycle-parent-work')&&!wire.includes('tool_result'))return toolResponse();if(wire.includes('Goal: lifecycle-child-work'))return syntheticResponse({finish:!unknownChild});return syntheticResponse();};}
async function contact(f,source){
 if(!f.ctx.get('connection')){f.ctx.provide('webServer',{register(){return()=>{};}});await f.ctx.plugin(ctx=>{new HostConnectionService(ctx,[],null);}).await();}
 const traced=f.ctx.get('connection'),connection=traced[symbols.original]??traced;await connection.operator.ctx.fiber.await();let handler;const register=connection.register;
 connection.register=function(owner,channel,callback){if(channel==='/dsh-bot-owner')handler=callback;return register.call(this,owner,channel,callback);};const generation={};
 const owner=installSelectedBotContactOwner({ownerCtx:f.ctx,expectedHost:f.host,connection,peer:connection.operator,connectionGeneration:generation,getConnectionGeneration:()=>generation,selectedBotId:f.bot.botId,botEpoch:f.host.object('bot',f.bot.botId).epoch,authorityEpoch:1,contactAgent:f.ctx.agents.get(f.host.object('bot',f.bot.botId).contactSessionId),requireOwnedGeneration:true,generationSource:source});connection.register=register;
 return{dispose:owner.dispose,call:(endpoint,payload)=>handler(endpoint,{command:endpoint,botId:f.bot.botId,payload},new AbortController().signal,connection.operator)};
}
const coordinates=(f,b)=>{const bot=f.host.object('bot',f.bot.botId),g=b.sessionId===bot.contactSessionId?f.ledger.list('ownedMainGeneration').find(g=>canonical(g.binding)===canonical(b)):f.ledger.list('workGeneration').find(g=>canonical(g.binding)===canonical(b));return Boolean(f.ctx.fiber.state===2&&bot.lifecycle==='active'&&b.botId===bot.botId&&b.botEpoch===bot.epoch&&b.configVersion===bot.configVersion&&g);};

function composition(f,originals,journals){
 const N=f.Native;let mainPort,mainIntent,mainSource,producer,preparation;
 const lifetime=()=>f.ctx.fiber.state===2&&f.host.object('bot',f.bot.botId).configVersion===f.bot.configVersion;
 const authority={isAuthorized:lifetime,isDispatchFenced:()=>f.host.object('bot',f.bot.botId).lifecycle==='archived'};
 const dispatch=b=>{if(!coordinates(f,b))return false;const bot=f.host.object('bot',f.bot.botId);if(b.sessionId===bot.contactSessionId)return f.ledger.list('ownedMainGeneration').find(g=>canonical(g.binding)===canonical(b))?.fence===null;const w=f.ledger.list('workTask').find(w=>w.sessionId===b.sessionId),g=f.ledger.list('workGeneration').find(g=>canonical(g.binding)===canonical(b));return w?.generation===b.generation&&g?.fence===null;};
 async function journal(i,role,create,policy,original){const j=await N.openOwnedGenerationJournal({ownerCtx:f.ctx,directory:join(f.directory,'journals',i.sessionId),create,sessionId:i.sessionId,role,route,session:{cwd:i.cwd,agentPreset:i.agentPreset},toolPolicy:policy,creationIntent:original});journals.set(i.sessionId,j);return j;}
 async function prepare(i,o,role='work'){
  const original={binding:structuredClone(i),operationId:i.operationId,nonce:i.nonce};originals.set(i.operationId,original);
  const j=await journal(i,role,true,role==='main'||o.delegateTool?'delegate':'zero',original),common={ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup(route.provider),sessionId:i.sessionId,route,journal:j,isCurrent:b=>coordinates(f,b),canDispatch:dispatch};
  const prepared=o.parentSource?N.prepareOwnedChildGenerationSource(o.parentSource,o.parentGeneration,{...common,plannedBinding:o.plannedBinding}):N.prepareOwnedGenerationSource({...common,role,...role==='work'?{workDelegate:{plannedBinding:o.plannedBinding,delegateTool:o.delegateTool}}:{}});
  return{route,prepared,creationIntent:original};
 }
 const producerOptions=(epoch,grant)=>({ownerCtx:f.ctx,host:f.host,caller:f.caller,originSessionId:f.host.object('bot',f.bot.botId).contactSessionId??mainIntent.sessionId,botId:f.bot.botId,botEpoch:epoch,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'actual-keyless-full-tree-lifecycle',...grant?{lifecycleRestoreGrant:grant}:{},execution:{isCurrent:lifetime,beforeExecute:async()=>{},generationControl:{prepareWorkGeneration:(i,o)=>prepare(i,o),prepareChildGeneration:(i,o)=>prepare(i,o),bindMainDelegateTool:d=>{mainSource=f.host.adapter.bindOwnedMainGeneration(mainPort,mainIntent,d);return mainSource;}}}});
 async function fresh(){mainIntent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},1);preparation=prepareOwnedBotProducer(producerOptions(1));mainPort=f.host.adapter.ownedGenerationCreationPort([mainIntent.sessionId],{scopeOf,role:'main',prepareGeneration:(i,o)=>prepare(i,o,'main'),isCurrent:lifetime});mainIntent=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,mainIntent.operationId);producer=preparation.attach(f.ctx.agents.get(mainIntent.sessionId));return producer;}
 async function read(i,{purpose,role,originalCreationIntent}){assert.equal(['archive-restore','active-recovery'].includes(purpose),true);const j=await journal(i,role,false,role==='main'||i.workDepth===0?'delegate':'zero',originalCreationIntent);return{journal:j,selectHistory:b=>N.selectOwnedGenerationHistory(j,f.ctx,b,authority)};}
 async function restore(i,o){
  const desc=describeOwnedBotLifecycleRestore(o.grant,f.host,f.caller,i);assert.equal(isOwnedBotLifecycleRestoreGrant(o.grant,f.host,f.caller,i),true);
  if(o.role==='main'){mainIntent=f.ledger.get('creation',i.operationId);preparation=prepareOwnedBotProducer(producerOptions(desc.botEpoch,o.grant));}
  const definition=o.role==='main'?preparation.delegateTool:i.workDepth===0?preparation.workDelegateFor(i):undefined,j=o.historyProof?.journal??await journal(i,o.role,false,definition?'delegate':'zero',o.originalCreationIntent);
  const select=b=>N.selectOwnedGenerationHistory(j,f.ctx,b,authority),historicalPlan=o.plannedBinding?o.historyProof?.selectors.find(row=>canonical(row.binding)===canonical(o.plannedBinding))?.selector??await select(o.plannedBinding):undefined;
  const port=f.host.adapter.ownedGenerationCreationPort([i.sessionId],{scopeOf,role:o.role,...definition?{delegateTool:definition}:{},isCurrent:()=>isOwnedBotLifecycleRestoreGrant(o.grant,f.host,f.caller,i),prepareGeneration:async()=>{const common={ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup(route.provider),sessionId:i.sessionId,route,journal:j,isCurrent:b=>coordinates(f,b),canDispatch:dispatch,...historicalPlan?{historicalPlan}:{}};const prepared=o.parentSource?await N.prepareOwnedKnownChildGenerationSource(o.parentSource,o.parentGeneration,{...common,plannedBinding:o.plannedBinding}):N.prepareOwnedGenerationSource({...common,role:o.role,...o.role==='main'?{delegateTool:definition}:definition?{workDelegate:{plannedBinding:o.plannedBinding,delegateTool:definition}}:{plannedBinding:o.plannedBinding}});return{route,prepared,creationIntent:o.originalCreationIntent,selectHistory:select};}});
  if(o.role==='main')mainPort=port;
  return{port,...definition?{delegateTool:definition,bindDelegate:()=>preparation.bindRestoredDelegate(f.ctx.agents.get(i.sessionId),i,port)}:{}};
 }
 async function lifecycle(cold=false){return f.host.openOwnedBotLifecyclePort(f.caller,{botId:f.bot.botId,botEpoch:f.host.object('bot',f.bot.botId).epoch,authorityEpoch:1,isOwnerCurrent:lifetime,...!cold?{mainCreationPort:mainPort,mainCreationIntent:mainIntent}:{},readOriginalCreation:i=>originals.get(i.operationId),inspectOriginalHistory:read,releaseArchivedSessions:async grant=>{await f.host.adapter.closeOwnedGenerationSession(mainPort,mainIntent,grant);producer?.dispose();for(const j of journals.values())await j.close();journals.clear();},prepareRestore:restore});}
 return{fresh,lifecycle,source:()=>mainSource,attach:()=>{producer=preparation.attach(f.ctx.agents.get(f.host.object('bot',f.bot.botId).contactSessionId));return producer;},close:async()=>{producer?.dispose();await f.ctx.fiber.dispose();for(const j of journals.values())await j.close();journals.clear();}};
}

async function restoredTree(t,responder=transport()){
 const directory=await mkdtemp(join(process.env.DSH_BOT_TEST_ROOT,'bot-tree-')),ledger=new Ledger(join(directory,'product.sqlite'));t.after(()=>ledger.close());const f=await generationFixture(t,responder,{directory,ledger,realWorkspace:true}),N=f.Native;assert.equal(typeof N.prepareOwnedKnownChildGenerationSource,'function','M2_NATIVE_TREE_HISTORY_REQUIRED');await N.mountOwnedGenerationArchiveGate(f.ctx);
 const originals=new Map(),journals=new Map(),c=composition(f,originals,journals),producer=await c.fresh(),firstContact=await contact(f,c.source()),contactPayload={operationId:'tree-original-contact',nonce:'tree-original-contact',text:'Synthetic original contact before lifecycle'};assert.equal((await firstContact.call('sendContactText',contactPayload)).ok,true);const originalContact=await observeUntil(()=>firstContact.call('inspectContactReceipt',{operationId:contactPayload.operationId,nonce:contactPayload.nonce}),r=>r.value?.preciseNativeSettlementVerified);const parent=await producer.delegate({operationId:'tree-lifecycle-parent',nonce:'tree-lifecycle-parent',task_id:'lifecycle-parent',goal:'lifecycle-parent-work',completion_condition:'Same native original task and child'});await producer.execute({task_id:parent.task_id,generation:1});
 await observeUntil(()=>producer.query({}),s=>s.work.length===2&&s.work.every(w=>w.nativeRuntimeVerified)).catch(error=>{throw Error(error.message+' '+JSON.stringify({work:producer.query({}),requests:f.requests(),creation:f.ledger.list('creation').map(i=>({taskId:i.taskId,state:i.state,sessionId:i.sessionId,unsupported:i.unsupported})),events:f.ctx.sessions.get(parent.sessionId).snapshotEvents()}));});await observeUntil(()=>f.ledger.list('ownedMainGeneration'),rows=>rows.length===3&&rows.every(r=>r.generationObservation.settlementVerified));const child=producer.query({task_ids:['lifecycle-child']}).work[0],oldBindings=f.ledger.list('workGeneration').map(g=>g.binding),mainId=f.host.object('bot',f.bot.botId).contactSessionId;firstContact.dispose();
 const lifecycle=await c.lifecycle(),archived=await lifecycle.archiveOriginalBot({operationId:'tree-native-archive',nonce:'tree-native-archive',botId:f.bot.botId,botEpoch:1});assert.equal(archived.nativeArchiveVerified,true);assert.equal(archived.state,'accepted');assert.equal(lifecycle.query().canRestore,true);for(const id of [mainId,parent.sessionId,child.sessionId])assert.equal(f.ctx.workspaceRegistry.archivedSessionIds.includes(id),true);
 const restored=await lifecycle.restoreOriginalBot({operationId:'tree-native-restore',nonce:'tree-native-restore',botId:f.bot.botId,botEpoch:2});assert.equal(restored.nativeRestoreVerified,true);assert.equal(restored.botEpoch,3);assert.deepEqual(f.ledger.list('workGeneration').map(g=>g.binding),oldBindings);const p2=c.attach();assert.equal(p2.assertWorkAgentTools(f.ctx.agents.get(parent.sessionId)),true);assert.equal(f.ctx.tools.schemas(f.ctx.agents.get(child.sessionId)).length,0);assert.equal(f.ctx.agents.isOwnedBy(child.sessionId,f.ctx.agents.get(parent.sessionId)),true);
 const restoredContact=await contact(f,c.source()),beforeQuery=f.requests(),readOriginal=await restoredContact.call('inspectContactReceipt',{operationId:contactPayload.operationId,nonce:contactPayload.nonce});assert.equal(readOriginal.ok,true);assert.equal(readOriginal.value.messageId,originalContact.value.messageId);assert.equal(readOriginal.value.preciseNativeSettlementVerified,true);assert.equal((await restoredContact.call('sendContactText',contactPayload)).value.messageId,originalContact.value.messageId);assert.equal((await restoredContact.call('requestContactStop',{operationId:'old-contact-stop-denied',nonce:'old-contact-stop-denied',contactOperationId:contactPayload.operationId})).ok,false);assert.equal(f.requests(),beforeQuery);restoredContact.dispose();
 return{directory,ledger,f,c,originals,p2,parent,child,mainId,oldBindings};
}

test('actual native tree restore adopts original receipts and historical contact queries without granting old stop authority',async t=>{const tree=await restoredTree(t);await tree.c.close();});

test('a known-restored child cannot allocate a continuation while its actual parent latest generation is UNKNOWN',async t=>{
 const parentResponse=Promise.withResolvers(),base=transport();t.after(()=>parentResponse.resolve(syntheticResponse()));
 const {f,c,p2,parent,child}=await restoredTree(t,(url,init)=>{const wire=JSON.stringify(JSON.parse(init.body).messages);return(wire.match(/Goal: lifecycle-parent-work/g)??[]).length>1?parentResponse.promise:base(url,init);});
 await observeUntil(()=>p2.canContinueOriginalWork({taskId:parent.taskId,sessionId:parent.sessionId,generation:1}),v=>v===true);
 const beforeRequests=f.requests();await p2.continueOriginalWork({operationId:'parent-latest-pending',nonce:'parent-latest-pending',taskId:parent.taskId,sessionId:parent.sessionId,generation:1});await f.waitRequest(beforeRequests+1);
 const request={operationId:'child-after-pending-parent',nonce:'child-after-pending-parent',taskId:child.taskId,sessionId:child.sessionId,generation:1},beforeContinuations=f.ledger.list('workContinuation'),beforeGenerations=f.ledger.list('workGeneration'),beforeInputs=f.ledger.list('workInput'),beforeDispatches=f.requests();
 try{const latest=p2.query({task_ids:[parent.task_id]}).work[0];assert.equal(latest.generation,2);assert.equal(latest.held,true);assert.equal(latest.generationObservation.remote,'UNKNOWN');assert.equal(p2.query({task_ids:[child.task_id]}).work[0].nativeRuntimeVerified,true);assert.equal(p2.canContinueOriginalWork(request),false);await assert.rejects(()=>p2.continueOriginalWork(request),{code:'work_resume_unconfirmed'});assert.deepEqual(f.ledger.list('workContinuation'),beforeContinuations);assert.deepEqual(f.ledger.list('workGeneration'),beforeGenerations);assert.deepEqual(f.ledger.list('workInput'),beforeInputs);assert.equal(f.requests(),beforeDispatches);}finally{parentResponse.resolve(syntheticResponse());}
 await observeUntil(()=>p2.canContinueOriginalWork({taskId:parent.taskId,sessionId:parent.sessionId,generation:2}),v=>v===true);await c.close();
});

test('aborting restored-child continuation during fresh parent inspection leaves the original inputs and leases unchanged',async t=>{
 const {f,c,p2,parent,child}=await restoredTree(t);await p2.continueOriginalWork({operationId:'parent-before-child-inspection',nonce:'parent-before-child-inspection',taskId:parent.taskId,sessionId:parent.sessionId,generation:1});await observeUntil(()=>p2.canContinueOriginalWork({taskId:parent.taskId,sessionId:parent.sessionId,generation:2}),v=>v===true);
 const request={operationId:'abort-child-fresh-parent-inspection',nonce:'abort-child-fresh-parent-inspection',taskId:child.taskId,sessionId:child.sessionId,generation:1},signal=new AbortController(),blocked=Promise.withResolvers(),release=Promise.withResolvers(),persistence=f.ctx.sessionPersistence,open=persistence.open;let didBlock=false;t.after(()=>release.resolve());
 persistence.open=async function(id,mode){if(!didBlock&&id===parent.sessionId&&mode==='read'&&new Error().stack.includes('/src/work-sessions.mjs')){didBlock=true;blocked.resolve();await release.promise;}return open.call(this,id,mode);};t.after(()=>{persistence.open=open;});
 const beforeContinuations=f.ledger.list('workContinuation'),beforeGenerations=f.ledger.list('workGeneration'),beforeInputs=f.ledger.list('workInput'),beforeDispatches=f.requests(),beforeSeq=f.ctx.sessions.get(child.sessionId).seq,continuation=p2.continueOriginalWork(request,signal.signal);continuation.catch(()=>{});
 let timer;try{await Promise.race([blocked.promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('SYNTHETIC_PARENT_INSPECTION_BARRIER_NOT_REACHED')),2000);})]);signal.abort();}finally{clearTimeout(timer);release.resolve();}
 await assert.rejects(()=>continuation,{code:'cancelled'});assert.deepEqual(f.ledger.list('workContinuation'),beforeContinuations);assert.deepEqual(f.ledger.list('workGeneration'),beforeGenerations);assert.deepEqual(f.ledger.list('workInput'),beforeInputs);assert.equal(f.requests(),beforeDispatches);assert.equal(f.ctx.sessions.get(child.sessionId).seq,beforeSeq);await c.close();
});

test('restored parent and child continue with new full bindings and survive ACTIVE cold recovery at the current epoch',async t=>{
 const {directory,ledger,f,c,originals,p2,parent,child,mainId,oldBindings}=await restoredTree(t);
 for(const w of [parent,child]){await observeUntil(()=>p2.canContinueOriginalWork({taskId:w.taskId,sessionId:w.sessionId,generation:1}),v=>v===true);const response=await p2.continueOriginalWork({operationId:'after-restore-'+w.taskId,nonce:'after-restore-'+w.taskId,taskId:w.taskId,sessionId:w.sessionId,generation:1});assert.equal(response.generation,2);await observeUntil(()=>p2.canContinueOriginalWork({taskId:w.taskId,sessionId:w.sessionId,generation:2}),v=>v===true);}
 await observeUntil(()=>p2.query({}),s=>s.work.every(w=>w.nativeRuntimeVerified)).catch(error=>{throw Error(error.message+' WORK '+JSON.stringify(p2.query({})));});await observeUntil(()=>f.ledger.list('ownedMainGeneration'),rows=>rows.length===5&&rows.every(r=>r.generationObservation.settlementVerified)).catch(error=>{throw Error(error.message+' MAIN '+JSON.stringify({main:f.ledger.list('ownedMainGeneration'),routes:f.ledger.list('workObservedResponse')}));});assert.equal(f.ledger.list('workGeneration').filter(g=>g.generation===2).every(g=>g.binding.botEpoch===3&&g.binding.slotLease.generation===2&&g.binding.inputMessageId!==oldBindings.find(b=>b.taskId===g.taskId).inputMessageId),true);await c.close();
 const next=await generationFixture(t,transport(),{directory,ledger,botId:f.bot.botId,realWorkspace:true});await next.Native.mountOwnedGenerationArchiveGate(next.ctx);const nc=composition(next,originals,new Map()),active=await nc.lifecycle(true),beforeBot=next.ledger.list('bot'),beforeTasks=next.ledger.list('task'),beforeGenerations=next.ledger.list('workGeneration').map(g=>g.binding);const recovered=await active.recoverOriginalBot();assert.equal(recovered.nativeRecoveryVerified,true);assert.equal(recovered.botEpoch,3);assert.equal(next.requests(),0);assert.deepEqual(next.ledger.list('bot'),beforeBot);assert.deepEqual(next.ledger.list('task'),beforeTasks);assert.deepEqual(next.ledger.list('workGeneration').map(g=>g.binding),beforeGenerations);assert.equal(next.host.object('bot',f.bot.botId).contactSessionId,mainId);
 const p3=nc.attach();for(const w of [parent,child]){await observeUntil(()=>p3.canContinueOriginalWork({taskId:w.taskId,sessionId:w.sessionId,generation:2}),v=>v===true);const response=await p3.continueOriginalWork({operationId:'after-cold-'+w.taskId,nonce:'after-cold-'+w.taskId,taskId:w.taskId,sessionId:w.sessionId,generation:2});assert.equal(response.generation,3);assert.equal(response.sessionId,w.sessionId);await observeUntil(()=>p3.canContinueOriginalWork({taskId:w.taskId,sessionId:w.sessionId,generation:3}),v=>v===true);}await observeUntil(()=>p3.query({}),s=>s.work.every(w=>w.nativeRuntimeVerified));await nc.close();
});
