/** Actual native archive/history machinery, keyless synthetic SSE only; no remote model evidence. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {scopeOf} from '@deepseek-ai/dsh-scope';
import {defineTool} from '@deepseek-ai/dsh-tools';
import {SessionCreationDriver} from '../src/session-creation.mjs';
import {isOwnedBotLifecycleRestoreGrant,describeOwnedBotLifecycleRestore} from '../src/owned-bot-lifecycle.mjs';
import {generationFixture,route} from './work-generation-fixture.mjs';

test('genuine blank original archives and resumes the same native/main identity under a new Bot epoch',async t=>{
 const f=await generationFixture(t,undefined,{realWorkspace:true}),N=f.Native;assert.equal(typeof N.admitOwnedBlankSessionControl,'function','M2_NATIVE_CONTROLS_REQUIRED');await N.mountOwnedGenerationArchiveGate(f.ctx);
 let journal,original;const definition=defineTool({name:'dsh_bot_delegate',description:'Bounded synthetic lifecycle delegate',parameters:{},output:{schema:{type:'object'},render:()=>[]},async execute(){return{};}});
 const prepare=async(i,options)=>{original??=Object.freeze({binding:structuredClone(i),operationId:i.operationId,nonce:i.nonce});journal=await N.openOwnedGenerationJournal({ownerCtx:f.ctx,directory:join(f.directory,'main-journal'),create:options.mode==='create',sessionId:i.sessionId,role:'main',route,session:{cwd:i.cwd,agentPreset:i.agentPreset},creationIntent:original});return{prepared:N.prepareOwnedGenerationSource({ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup(route.provider),sessionId:i.sessionId,role:'main',route,journal,isCurrent:()=>true,canDispatch:()=>false,...options.mode==='resume'?{delegateTool:definition}:{}}),route,creationIntent:original};};
 const intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),port=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',prepareGeneration:prepare,isCurrent:()=>true});const created=await new SessionCreationDriver({host:f.host,caller:f.caller,port}).run(f.caller,intent.operationId);const register=p=>{const agent=f.ctx.agents.get(intent.sessionId);agent.ctx.tools.register(definition);return f.host.adapter.bindOwnedMainGeneration(p,created,definition);};register(port);let resumedPort;
 const lifecycle=await f.host.openOwnedBotLifecyclePort(f.caller,{botId:f.bot.botId,botEpoch:1,authorityEpoch:1,isOwnerCurrent:()=>true,mainCreationPort:port,mainCreationIntent:created,releaseArchivedSessions:async grant=>{assert.equal(isOwnedBotLifecycleRestoreGrant(grant,f.host,f.caller,created),true);await f.host.adapter.closeOwnedGenerationSession(port,created,grant);await journal.close();},prepareRestore:async(i,{grant,role,originalCreationIntent})=>{assert.equal(role,'main');assert.deepEqual(originalCreationIntent,original);assert.equal(describeOwnedBotLifecycleRestore(grant,f.host,f.caller,i).botEpoch,3);resumedPort=f.host.adapter.ownedGenerationCreationPort([i.sessionId],{scopeOf,role,delegateTool:definition,prepareGeneration:prepare,isCurrent:()=>isOwnedBotLifecycleRestoreGrant(grant,f.host,f.caller,i)});return{port:resumedPort,delegateTool:definition,bindDelegate:()=>register(resumedPort)};}});
 assert.equal(lifecycle.query().canArchive,true);const request={operationId:'archive-native',nonce:'archive-native',botId:f.bot.botId,botEpoch:1},archived=await lifecycle.archiveOriginalBot(request);assert.equal(archived.state,'accepted');assert.equal(archived.botEpoch,2);assert.equal(archived.nativeArchiveVerified,true);assert.equal(lifecycle.query().canRestore,true);assert.equal(f.ctx.workspaceRegistry.archivedSessionIds.includes(intent.sessionId),true);assert.deepEqual(await lifecycle.archiveOriginalBot(request),archived);
 const restored=await lifecycle.restoreOriginalBot({operationId:'restore-native',nonce:'restore-native',botId:f.bot.botId,botEpoch:2});assert.equal(restored.state,'accepted');assert.equal(restored.botEpoch,3);assert.equal(restored.nativeRestoreVerified,true);assert.equal(f.host.object('bot',f.bot.botId).contactSessionId,intent.sessionId);assert.equal(f.ctx.agents.get(intent.sessionId).id,intent.sessionId);assert.equal(f.ctx.tools.schemas(f.ctx.agents.get(intent.sessionId)).length,1);assert.equal(f.ctx.workspaceRegistry.archivedSessionIds.includes(intent.sessionId),false);assert.equal(f.requests(),0);assert.equal(isOwnedBotLifecycleRestoreGrant({},f.host,f.caller,created),false);
});
