import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture,human } from './helpers.mjs';
import { createHandler } from '../src/server.mjs';
import { prepareCommand } from '../ui/command.mjs';
import * as commands from '../ui/command.mjs';
import { apply } from '../src/plugin.mjs';
import { records } from '../ui/records.mjs';
import { DshAdapter } from '../src/adapter.mjs';
const origin='http://127.0.0.1:8787';
async function call(handler,{method='GET',url='/api/snapshot',headers={},body=''}={}) { const req={method,url,headers:{host:'127.0.0.1:8787',origin,'x-dsh-token':'test-only',...headers},async *[Symbol.asyncIterator](){yield Buffer.from(body);}}; const res={headers:{},setHeader(k,v){this.headers[k]=v;},writeHead(status,h){this.status=status;Object.assign(this.headers,h);},end(value){this.body=value;}};await handler(req,res);return {...res,json:JSON.parse(res.body)}; }
test('HTTP trusted entry rejects origin, rebinding and spoofed actor before side effects',async()=>{const f=fixture(),handler=createHandler({host:f.host,origin,token:'test-only',assets:{}});for(const headers of [{origin:'https://evil.invalid'},{host:'evil.invalid'},{'x-dsh-token':'wrong'}]) {const r=await call(handler,{headers});assert.equal(r.status,403);}const r=await call(handler,{method:'POST',url:'/api/command',headers:{'content-type':'application/json'},body:JSON.stringify({actor:{kind:'human',id:human.id}})});assert.equal(r.status,400);assert.equal(f.ledger.list('bot').length,0);f.ledger.close();});
test('client persists exact operation before submit, supports lookup after restart and never silently renonces',async()=>{const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};const f=fixture();const input={ledgerInstanceId:f.host.ledgerInstanceId,command:'createBot',payload:{name:'UI',config:{contact:{provider:'synthetic',model:'A'}}},expectedRevision:null,expectedEpochs:{}};const locks={request:(_name,_options,fn)=>fn()};const first=await prepareCommand(storage,input,locks);const recovered=await prepareCommand(storage,input,locks);assert.deepEqual(recovered,first);assert.equal(JSON.parse(values.get('dsh-bot-pending')).envelope.operationId,first.envelope.operationId);await assert.rejects(()=>prepareCommand(storage,{...input,payload:{...input.payload,name:'changed'}},locks),{code:'pending_operation'});const handler=createHandler({host:f.host,origin,token:'test-only',assets:{}});const post=()=>call(handler,{method:'POST',url:'/api/command',headers:{'content-type':'application/json'},body:JSON.stringify(first)});const a=await post(),b=await post();assert.equal(a.status,200);assert.deepEqual(a.json,b.json);assert.equal(f.ledger.list('bot').length,1);f.ledger.close();});
test('Cordis seam provides only control ledger and disposes it; fake context is not live proof',async()=>{const f=fixture();f.ledger.close();let cleanup,service,provided;const ctx={provide:(name,value)=>{provided=name;ctx[name]=value;},effect:fn=>{cleanup=fn();}};service=apply(ctx,{databasePath:f.path,ownerHumanId:human.id});assert.equal(provided,'dshBot');assert.equal(ctx.dshBot,service);assert.equal(service.snapshot(human).nativeRuntimeVerified,false);await cleanup();assert.throws(()=>service.snapshot(human));});
test('Cordis public service cannot claim a human caller or expose private ledger records',async()=>{const f=fixture();f.ledger.close();let dispose;const ctx={provide(){},effect:fn=>{dispose=fn();}};const service=apply(ctx,{databasePath:f.path,ownerHumanId:human.id});assert.throws(()=>service.execute(human,{},{}),{code:'unsupported_host_identity'});assert.equal(service.ledger,undefined);assert.equal(service.snapshot(human).bot,undefined);await dispose();});
test('two tabs cannot create distinct operations before persistence completes',async()=>{const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)},input={ledgerInstanceId:'test-ledger',command:'createBot',payload:{name:'race',config:{contact:{provider:'synthetic',model:'A'}}},expectedRevision:null,expectedEpochs:{}};let tail=Promise.resolve();const locks={request(_name,_options,fn){const work=tail.then(fn);tail=work.catch(()=>{});return work;}};const [a,b]=await Promise.all([prepareCommand(storage,input,locks),prepareCommand(storage,input,locks)]);assert.deepEqual(a,b);assert.equal(JSON.parse(values.get('dsh-bot-pending')).envelope.operationId,a.envelope.operationId);});
test('late receipt cleanup preserves a newer tab operation',async()=>{const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};let tail=Promise.resolve();const locks={request(_name,_options,fn){const work=tail.then(fn);tail=work.catch(()=>{});return work;}};assert.equal(typeof commands.clearPending,'function');const input={ledgerInstanceId:'test-ledger',command:'createBot',payload:{name:'old'},expectedRevision:null,expectedEpochs:{}};const old=await prepareCommand(storage,input,locks);assert.equal(await commands.clearPending(storage,old.envelope,locks),true);const next=await prepareCommand(storage,{...input,payload:{name:'next'}},locks);assert.equal(await commands.clearPending(storage,old.envelope,locks),false);assert.equal(JSON.parse(storage.getItem('dsh-bot-pending')).envelope.operationId,next.envelope.operationId);assert.equal(await commands.clearPending(storage,next.envelope,locks),true);});
test('browser without origin-wide identity locks refuses to create a command',async()=>{const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};await assert.rejects(()=>prepareCommand(storage,{command:'createBot',payload:{name:'unsupported'},expectedRevision:null,expectedEpochs:{}},null),{code:'identity_lock_unavailable'});assert.equal(values.size,0);});
test('unknown execution is visible outside collapsed details with all status dimensions',()=>{const node=(tag,text,className)=>({tag,text,className,children:[],append(...children){this.children.push(...children);}}),parent=node('section');records(node,parent,[{attemptId:'attempt-one',execution:'outcome_unknown',responsibility:'submitted',stop:{state:'unknown'}}]);const visible=parent.children.filter(n=>n.tag!=='details').map(n=>n.text).join(' ');assert.match(visible,/outcome_unknown/);assert.match(visible,/查回/);const summary=parent.children.find(n=>n.tag==='details').children.find(n=>n.tag==='summary').text;assert.match(summary,/outcome_unknown/);assert.match(summary,/submitted/);assert.match(summary,/unknown/);assert.doesNotMatch(summary,/undefined/);});
test('pending browser operation cannot execute against a replacement ledger instance',async()=>{const a=fixture(),b=fixture(),values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)},locks={request:(_n,_o,fn)=>fn()},input={command:'createBot',payload:{name:'bound ledger',config:{contact:{provider:'synthetic',model:'A'}}},expectedRevision:null,expectedEpochs:{},ledgerInstanceId:a.host.snapshot(human).ledgerInstanceId};const body=await prepareCommand(storage,input,locks),options={method:'POST',url:'/api/command',headers:{'content-type':'application/json'},body:JSON.stringify(body)};assert.equal((await call(createHandler({host:a.host,origin,token:'test-only',assets:{}}),options)).status,200);const replacement=await call(createHandler({host:b.host,origin,token:'test-only',assets:{}}),options);assert.equal(replacement.status,400);assert.equal(replacement.json.code,'ledger_identity_conflict');assert.equal(b.ledger.list('bot').length,0);assert.ok(storage.getItem('dsh-bot-pending'));a.ledger.close();b.ledger.close();});
test('retry only recovers an existing frozen identity and never recreates a cleared operation',async()=>{const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},locks={request:(_n,_o,fn)=>fn()},input={ledgerInstanceId:'original-ledger',command:'createBot',payload:{name:'retry'},expectedRevision:null,expectedEpochs:{}};assert.equal(typeof commands.recoverPending,'function');const body=await prepareCommand(storage,input,locks);assert.deepEqual(await commands.recoverPending(storage,locks),body);await commands.clearPending(storage,body.envelope,locks);assert.equal(await commands.recoverPending(storage,locks),null);assert.equal(values.size,0);});

test('authenticated mode metadata endpoint reads only the trusted dynamic roster',async()=>{
 let calls=0;const a=new DshAdapter({agentPresets:{list:async()=>{calls++;return [{id:'custom',name:'创造'}];},defaultId:'custom'},sessionController:{create(){throw Error('native write forbidden');}}});
 const f=fixture(a),handler=createHandler({host:f.host,origin,token:'test-only',assets:{}});
 const refused=await call(handler,{url:'/api/agent-presets',headers:{'x-dsh-token':'wrong'}});assert.equal(refused.status,403);assert.equal(calls,0);
 const response=await call(handler,{url:'/api/agent-presets'});assert.equal(response.status,200);assert.deepEqual(response.json.options,[{id:'custom',name:'创造',isDefault:true}]);assert.equal(calls,1);
 assert.equal(f.ledger.list('bot').length,0);assert.equal(f.host.snapshot(human).nativeRuntimeVerified,false);f.ledger.close();
});
test('dynamic mode control displays custom names while encoded option values preserve opaque identities',async()=>{
 const mode=await import('../ui/session-mode.mjs');const node=(tag,text)=>({tag,text,children:[],append(...children){this.children.push(...children);}});
 const catalog={status:'available',options:[{id:'custom/v2',name:'创造'},{id:'keep',name:'Keep custom'},{id:'null',name:'Null custom'}]};
 const control=mode.createModeControl(node,catalog,{update:true});assert.equal(control.disabled,false);assert.equal(control.name,'agentPreset');assert.equal(control.children.length,5);
 const custom=control.children.find(row=>row.value===JSON.stringify('custom/v2'));assert.match(custom.text,/创造/);assert.match(custom.text,/custom\/v2/);
 assert.deepEqual(mode.modeConfigField(custom.value),{agentPreset:'custom/v2'});assert.deepEqual(mode.modeConfigField(JSON.stringify('keep')),{agentPreset:'keep'});assert.deepEqual(mode.modeConfigField(JSON.stringify('null')),{agentPreset:'null'});
});
test('unavailable mode control stays disabled and omitted update preserves stored choice',async()=>{
 const mode=await import('../ui/session-mode.mjs');const node=(tag,text)=>({tag,text,children:[],append(...children){this.children.push(...children);}});
 for(const catalog of [undefined,{status:'unavailable',options:[{id:'stale'}]},{status:'available',options:[]}]) {
  const control=mode.createModeControl(node,catalog,{update:true});assert.equal(control.disabled,true);assert.equal(control.children.length,2);
 }
 assert.deepEqual(mode.modeConfigField(null),{});assert.deepEqual(mode.modeConfigField('keep'),{});assert.deepEqual(mode.modeConfigField('null'),{agentPreset:null});
 assert.throws(()=>mode.modeConfigField('{}'));assert.throws(()=>mode.modeConfigField(JSON.stringify(' ')));
});
