import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture,createBot,createTask,human } from './helpers.mjs';
import { reserveResources,settleResources } from '../src/resources.mjs';
import { observe } from '../src/observations.mjs';
import { guideInput,guideText,knownExecution } from './guide-fixture.mjs';
test('guide content acceptance reuses exact revision/digest/version while leaving native settled and unknown rows unchanged',async()=>{
 let api;try{api=await import('../src/guide-acceptance.mjs');}catch(error){if(error.code!=='ERR_MODULE_NOT_FOUND')throw error;api={};}
 assert.equal(typeof api.guideAcceptancePayloads,'function');
 for(const outcome of ['failed','inconclusive','passed']){const f=fixture();try{
  const b=createBot(f),t=createTask(f,b),native=knownExecution(),unknown={...knownExecution(),operationId:'original-unknown',state:'unknown',usage:null,receipt:null,reservationHeld:true};
  f.ledger.put('nativeOperation',native.operationId,native);f.ledger.put('nativeOperation',unknown.operationId,unknown);
  const input=guideInput({task:t,expectedAuthorityEpoch:f.ledger.get('grant','root').epoch,executionEvidence:unknown});input.semanticVerdict={outcome,artifactDigest:input.semanticVerdict.artifactDigest,acceptanceVersion:t.acceptanceVersion};
  const r=api.guideAcceptancePayloads(input),submitted=f.cmd('submitTask',r.submitTask,r.expectedRevisions.submit).result;
  for(const changed of [{...r.acceptTask,artifactDigest:'c'.repeat(64)},{...r.acceptTask,acceptanceVersion:t.acceptanceVersion+1}])assert.throws(()=>f.cmd('acceptTask',changed,submitted.revision),{code:'acceptance_conflict'});
  const accepted=f.cmd('acceptTask',r.acceptTask,r.expectedRevisions.accept).result;assert.equal(accepted.acceptanceCheck.outcome,outcome);assert.equal(accepted.responsibility,outcome==='passed'?'verified':'submitted');
  assert.deepEqual(f.ledger.get('nativeOperation',native.operationId),native);assert.deepEqual(f.ledger.get('nativeOperation',unknown.operationId),unknown);assert.notEqual(r.overallOutcome,'passed');
 }finally{f.ledger.close();}}
});
test('F25 resource plan is all or none and unknown remains occupied',()=>{const f=fixture();assert.equal(reserveResources(f.ledger,'A',['X','Y']).status,'reserved');assert.equal(reserveResources(f.ledger,'B',['Y','Z']).status,'blocked_resource');assert.equal(f.ledger.get('resource','Z'),null);f.ledger.put('resource','X',{id:'X',attemptId:'A',state:'unknown'});assert.throws(()=>settleResources(f.ledger,'A',{authority:'plugin',terminal:true}),{code:'invalid_evidence'});assert.equal(reserveResources(f.ledger,'B',['X']).status,'blocked_resource');f.ledger.close();});
test('F06 precise authority settlement releases only owning attempt',()=>{const f=fixture();reserveResources(f.ledger,'old',['X']);reserveResources(f.ledger,'new',['Y']);settleResources(f.ledger,'old',{authority:'synthetic-test',terminal:true,attemptId:'old'},e=>e.authority==='synthetic-test');assert.equal(f.ledger.get('resource','X').state,'settled');assert.equal(f.ledger.get('resource','Y').state,'reserved');f.ledger.close();});
test('F26 duplicate and late same-generation events cannot regress settled state',()=>{const f=fixture();const event=(id,seq,state)=>({eventId:id,source:'synthetic-runtime',sourceSeq:seq,entityId:'a',generation:'r1',state,observedAt:'2026-10-04T00:00:00Z'});observe(f.ledger,event('12',12,'settled'));observe(f.ledger,event('10',10,'running'));observe(f.ledger,event('12',12,'settled'));const p=f.ledger.get('projection','a');assert.equal(p.state,'settled');assert.equal(p.sourceSeq,12);assert.equal(p.freshness,'stale');f.ledger.close();});
test('F08 old generation never overwrites current projection',()=>{const f=fixture();observe(f.ledger,{eventId:'new',source:'synthetic-runtime',sourceSeq:1,entityId:'a',generation:'new',state:'running',observedAt:'now'});observe(f.ledger,{eventId:'old',source:'synthetic-runtime',sourceSeq:2,entityId:'a',generation:'old',state:'settled',observedAt:'later'});assert.equal(f.ledger.get('projection','a').generation,'new');assert.equal(f.ledger.get('projection','a').state,'running');f.ledger.close();});
test('F20 submitted never self-verifies and acceptance is bound to exact revision',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b);const s=f.cmd('submitTask',{taskId:t.taskId,artifactDigest:'a'.repeat(64),evidence:'manual artifact',expectedAuthorityEpoch:1},t.revision).result;assert.equal(s.responsibility,'submitted');const r=f.cmd('acceptTask',{taskId:t.taskId,artifactDigest:'a'.repeat(64),acceptanceVersion:1,outcome:'passed'},s.revision).result;assert.equal(r.responsibility,'verified');assert.throws(()=>f.cmd('acceptTask',{taskId:t.taskId,artifactDigest:'a'.repeat(64),acceptanceVersion:1,outcome:'passed'},s.revision),{code:'revision_conflict'});f.ledger.close();});
test('F05 revoked authority blocks submit but still permits inspectOperation',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b);const r=f.cmd('revoke',{grantId:'root'});assert.throws(()=>f.cmd('submitTask',{taskId:t.taskId,artifactDigest:'a'.repeat(64),evidence:'late',expectedAuthorityEpoch:1},t.revision),{code:'unauthorized'});assert.equal(f.cmd('inspectOperation',{operationId:r.operationId}).result.operationId,r.operationId);assert.equal(f.host.snapshot(human).releaseReady,false);f.ledger.close();});
test('same-generation nonterminal state cannot regress',()=>{const f=fixture();const e=(id,seq,state)=>({eventId:id,source:'synthetic-runtime',sourceSeq:seq,entityId:'r',generation:'g',state,observedAt:'now'});observe(f.ledger,e('running',1,'running'));observe(f.ledger,e('queued',2,'queued'));assert.equal(f.ledger.get('projection','r').state,'running');assert.equal(f.ledger.get('projection','r').freshness,'stale');f.ledger.close();});
test('stopped or archived-owner task rejects manual submission',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b);const s=f.cmd('stopTask',{taskId:t.taskId},t.revision).result;assert.throws(()=>f.cmd('submitTask',{taskId:t.taskId,artifactDigest:'a'.repeat(64),evidence:'late',expectedAuthorityEpoch:1},s.revision),{code:'task_stopped'});const t2=createTask(f,b);f.cmd('archive',{kind:'bot',id:b.botId},b.revision);assert.throws(()=>f.cmd('submitTask',{taskId:t2.taskId,artifactDigest:'a'.repeat(64),evidence:'late',expectedAuthorityEpoch:1},f.ledger.get('task',t2.taskId).revision),{code:'owner_unavailable'});f.ledger.close();});
test('trusted generation transition advances projection while old events remain historical',async()=>{const f=fixture(),api=await import('../src/observations.mjs');assert.equal(typeof api.activateGeneration,'function');observe(f.ledger,{eventId:'g1',source:'synthetic-runtime',sourceSeq:1,entityId:'r',generation:'old',state:'running',observedAt:'now'});assert.throws(()=>api.activateGeneration(f.ledger,{entityId:'r',source:'synthetic-runtime',generation:'new',priorGeneration:'old'}),{code:'invalid_evidence'});api.activateGeneration(f.ledger,{entityId:'r',source:'synthetic-runtime',generation:'new',priorGeneration:'old'},()=>true);observe(f.ledger,{eventId:'g2',source:'synthetic-runtime',sourceSeq:1,entityId:'r',generation:'new',state:'running',observedAt:'new'});observe(f.ledger,{eventId:'late',source:'synthetic-runtime',sourceSeq:99,entityId:'r',generation:'old',state:'settled',observedAt:'late'});assert.equal(f.ledger.get('projection','r').generation,'new');assert.equal(f.ledger.get('projection','r').state,'running');f.ledger.close();});
test('future database schema is refused before writer pragmas mutate it',async()=>{const { DatabaseSync }=await import('node:sqlite');const { readFileSync }=await import('node:fs');const { Ledger }=await import('../src/ledger.mjs');const f=fixture();f.ledger.close();const db=new DatabaseSync(f.path);db.exec('PRAGMA journal_mode=DELETE; PRAGMA user_version=99;');db.close();const before=readFileSync(f.path);assert.throws(()=>new Ledger(f.path),{code:'migration_required'});assert.equal(readFileSync(f.path).equals(before),true,'Unsupported schema bytes must be preserved');});
test('stopped submission cannot be accepted, cannot reach verified',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b),digest='c'.repeat(64);const submitted=f.cmd('submitTask',{taskId:t.taskId,artifactDigest:digest,evidence:'manual only',expectedAuthorityEpoch:1},t.revision).result;const stopped=f.cmd('stopTask',{taskId:t.taskId},submitted.revision).result;assert.throws(()=>f.cmd('acceptTask',{taskId:t.taskId,artifactDigest:digest,acceptanceVersion:1,outcome:'passed'},stopped.revision),{code:'task_stopped'});f.ledger.close();});
test('unknown projection never regresses to queued',()=>{const f=fixture();const event={eventId:'unknown',source:'synthetic',sourceSeq:1,entityId:'E',generation:'G',state:'outcome_unknown',observedAt:'2026-10-04T00:00:00Z'};observe(f.ledger,event);observe(f.ledger,{...event,eventId:'queued-late',sourceSeq:2,state:'queued'});assert.equal(f.ledger.get('projection','E').state,'outcome_unknown');f.ledger.close();});
test('archive and restore fences prepared task submission and old delivery generations',()=>{const f=fixture(),a=createBot(f,'A'),b=createBot(f,'B'),t=createTask(f,a),g=f.cmd('createGroup',{name:'G',namespace:'P',members:[a.botId,b.botId],coordinatorBotId:a.botId}).result;f.cmd('sendMessage',{groupId:g.groupId,recipients:[a.botId],content:'pending'});const archived=f.cmd('archive',{kind:'bot',id:a.botId},a.revision).result;f.cmd('restore',{kind:'bot',id:a.botId},archived.revision);assert.throws(()=>f.cmd('submitTask',{taskId:t.taskId,artifactDigest:'e'.repeat(64),evidence:'prepared before archive',expectedAuthorityEpoch:1},t.revision,{task:t.epoch}),{code:'revision_conflict'});assert.equal(f.ledger.list('delivery')[0].state,'revoked');assert.equal(f.ledger.list('outbox')[0].state,'revoked');assert.notEqual(f.ledger.get('task',t.taskId).responsibility,'verified');f.ledger.close();});
test('pending target adjustment cannot submit or accept old acceptance criteria',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b),adjusted=f.cmd('adjustTask',{taskId:t.taskId,title:'new target',acceptance:'new check'},t.revision).result;assert.throws(()=>f.cmd('submitTask',{taskId:t.taskId,artifactDigest:'e'.repeat(64),evidence:'old result',expectedAuthorityEpoch:1},adjusted.revision),{code:'revision_pending'});f.ledger.put('task',t.taskId,{...adjusted,responsibility:'submitted',artifactDigest:'e'.repeat(64)});assert.throws(()=>f.cmd('acceptTask',{taskId:t.taskId,artifactDigest:'e'.repeat(64),acceptanceVersion:1,outcome:'passed'},adjusted.revision),{code:'revision_pending'});f.ledger.close();});
test('restore does not authorize old submitted work even with a fresh task revision',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b),artifactDigest='f'.repeat(64);f.cmd('submitTask',{taskId:t.taskId,artifactDigest,evidence:'manual before archive',expectedAuthorityEpoch:1},t.revision);const archived=f.cmd('archive',{kind:'bot',id:b.botId},b.revision).result;f.cmd('restore',{kind:'bot',id:b.botId},archived.revision);const current=f.ledger.get('task',t.taskId);assert.throws(()=>f.cmd('acceptTask',{taskId:t.taskId,artifactDigest,acceptanceVersion:1,outcome:'passed'},current.revision),{code:'owner_epoch_conflict'});assert.throws(()=>f.cmd('submitTask',{taskId:t.taskId,artifactDigest,evidence:'late',expectedAuthorityEpoch:1},current.revision),{code:'owner_epoch_conflict'});assert.equal(f.ledger.list('acceptance').length,0);f.ledger.close();});
test('archive keeps unknown attempt execution and resource occupancy as evidence',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b),a=f.cmd('startAttempt',{taskId:t.taskId},t.revision).result;f.ledger.put('attempt',a.attemptId,{...a,execution:'outcome_unknown'});f.ledger.put('resource','r',{id:'r',state:'unknown',attemptId:a.attemptId});f.cmd('archive',{kind:'bot',id:b.botId},b.revision);const fenced=f.ledger.get('attempt',a.attemptId);assert.equal(fenced.execution,'outcome_unknown');assert.equal(fenced.fence,a.fence+1);assert.equal(fenced.stop.state,'unsupported');assert.equal(f.ledger.get('resource','r').state,'unknown');f.ledger.close();});
test('verified responsibility does not exempt unresolved native attempts from archive fencing',()=>{const f=fixture(),b=createBot(f),t=createTask(f,b),a=f.cmd('startAttempt',{taskId:t.taskId},t.revision).result;let current=f.ledger.get('task',t.taskId);current=f.cmd('submitTask',{taskId:t.taskId,artifactDigest:'a'.repeat(64),evidence:'human artifact does not settle native execution',expectedAuthorityEpoch:1},current.revision).result;const verified=f.cmd('acceptTask',{taskId:t.taskId,artifactDigest:'a'.repeat(64),acceptanceVersion:1,outcome:'passed'},current.revision).result;f.cmd('archive',{kind:'bot',id:b.botId},b.revision);assert.deepEqual(f.ledger.get('task',t.taskId),verified,'Historical acceptance is preserved');const fenced=f.ledger.get('attempt',a.attemptId);assert.equal(fenced.fence,a.fence+1);assert.equal(fenced.execution,a.execution);assert.equal(fenced.stop.state,'unsupported');f.ledger.close();});
