/** Actual stock Context/Connection/Agent/Session fixtures; no browser authentication or network claim. */
import test from'node:test';import assert from'node:assert/strict';import{createUserMessage}from'@deepseek-ai/dsh-llm';import{symbols}from'@deepseek-ai/cordis';import{HostConnectionService}from'@deepseek-ai/dsh-client-connection';import{stockFixture,envelope}from'./bot-producer-fixture.mjs';
globalThis.__offlineIO??={model:0};
async function installer(){const m=await import('../src/selected-bot-contact-owner.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return{};});assert.equal(typeof m.installSelectedBotContactOwner,'function','missing actual private contact owner installer');return m.installSelectedBotContactOwner;}
async function fixture(t,{cancelFailure=false,requireOwnedGeneration=false,canSend=()=>true,generationSource}={}){const install=await installer(),f=await stockFixture(t);const routes=new Map();f.ctx.provide('webServer',{register(route){assert.equal(routes.has(route.path),false);routes.set(route.path,route);return()=>routes.delete(route.path);}});const handle=f.ctx.plugin(ctx=>{new HostConnectionService(ctx,[],null);});await handle.await();const traced=f.ctx.get('connection'),connection=traced[symbols.original]??traced;await connection.operator.ctx.fiber.await();let currentGeneration={};const captured=new Map(),originalRegister=connection.register;connection.register=function(owner,channel,handler){captured.set(channel,handler);return originalRegister.call(this,owner,channel,handler);};t.after(()=>{connection.register=originalRegister;});const b=f.host.object('bot',f.bot.botId);const ioBefore=globalThis.__offlineIO.model;const gateSignals=[];f.ctx.on('agent/pre-step',event=>{gateSignals.push(event.signal);return new Promise((_,reject)=>{const abort=()=>reject(Object.assign(Error('offline_test_cancelled'),{code:'offline_test_cancelled'}));if(event.signal.aborted)abort();else event.signal.addEventListener('abort',abort,{once:true});});});let cancelCalls=0;if(cancelFailure){const nativeCancel=f.originAgent.cancel;f.originAgent.cancel=function(...args){cancelCalls++;nativeCancel.apply(this,args);throw Error('offline_cancel_outcome_unknown');};f.restores.push(()=>{f.originAgent.cancel=nativeCancel;});}const options={ownerCtx:f.ctx,expectedHost:f.host,connection,peer:connection.operator,connectionGeneration:currentGeneration,getConnectionGeneration:()=>currentGeneration,selectedBotId:b.botId,botEpoch:b.epoch,authorityEpoch:1,contactAgent:f.originAgent,requireOwnedGeneration,canSend,generationSource};const owner=install(options);t.after(()=>owner.dispose());const call=(endpoint,payload={},signal=new AbortController().signal,peer=connection.operator)=>captured.get('/dsh-bot-owner')(endpoint,{command:endpoint,botId:b.botId,payload},signal,peer);return{...f,connection,handle,routes,captured,owner,call,options,gateSignals,ioBefore,cancelCalls:()=>cancelCalls,reconnect(){currentGeneration={};}};}
const sendPayload=(id='contact-op-one',nonce='contact-nonce-one')=>({operationId:id,nonce,text:'Return only harmless GUI_MARKER_315'});
const inserted=(f,id)=>f.originAgent.session.snapshotEvents().flatMap(e=>e.type==='agent/inbox/spliced'?e.data.inserted:[]).filter(m=>!id||m.id===id);
const tick=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
test('private owner installs only its stock RPC channel and exposes selected work details without capabilities',async t=>{const f=await fixture(t);assert.equal(f.routes.has('/dsh-bot-owner'),true);assert.deepEqual([...f.captured.keys()],['/dsh-bot-owner']);const view=await f.call('selectedView');assert.equal(view.ok,true);assert.equal(view.value.botId,f.bot.botId);assert.equal(view.value.contact.sessionId,f.originAgent.id);assert.deepEqual(view.value.work,[]);for(const key of ['caller','peer','policy','host','config','ledger','execute'])assert.equal(JSON.stringify(view).includes('"'+key+'":'),false);assert.equal((await f.call('execute')).ok,false);assert.equal(globalThis.__offlineIO.model,f.ioBefore);});
test('actual contact send and duplicate receipt reconciliation preserve one original native wake',async t=>{const f=await fixture(t),payload=sendPayload(),first=await f.call('sendContactText',payload);assert.equal(first.ok,true);assert.equal(first.value.state,'durably-queued');assert.equal(first.value.messageId,inserted(f)[0].id);assert.equal(inserted(f,first.value.messageId).length,1);assert.deepEqual(inserted(f)[0].source,{kind:'user'});const again=await f.call('sendContactText',payload),lookup=await f.call('inspectContactReceipt',{operationId:payload.operationId,nonce:payload.nonce});assert.equal(again.value.messageId,first.value.messageId);assert.equal(lookup.value.messageId,first.value.messageId);assert.equal(inserted(f,first.value.messageId).length,1);assert.equal(globalThis.__offlineIO.model,f.ioBefore);});
test('malicious browser authority, wrong Bot, copied or forged peer cannot invoke contact action',async t=>{const f=await fixture(t),handler=f.captured.get('/dsh-bot-owner'),controller=new AbortController();for(const extra of [{caller:{}},{peer:{}},{provider:'foreign'},{connectionGeneration:{}},{cwd:'/private'}]){const r=await handler('sendContactText',{command:'sendContactText',botId:f.bot.botId,payload:{...sendPayload(),...extra}},controller.signal,f.connection.operator);assert.equal(r.ok,false);}const forged=Object.assign(Object.create(Object.getPrototypeOf(f.connection.operator)),f.connection.operator,{[symbols.original]:f.connection.operator});assert.equal((await f.call('sendContactText',sendPayload(),controller.signal,forged)).ok,false);assert.equal((await handler('sendContactText',{command:'sendContactText',botId:'foreign',payload:sendPayload()},controller.signal,f.connection.operator)).ok,false);assert.equal(inserted(f).length,0);});
for(const kind of ['connection-generation','abort','configuration','authority'])test('authority checkpoint blocks native send after awaited resolve changes '+kind,async t=>{const f=await fixture(t),started=Promise.withResolvers(),release=Promise.withResolvers(),service=f.ctx.get('sessionController'),original=service.resolveAgent;service.resolveAgent=async function(...args){started.resolve();await release.promise;return original.apply(this,args);};t.after(()=>{service.resolveAgent=original;});const abort=new AbortController(),pending=f.call('sendContactText',sendPayload(),abort.signal);await Promise.race([started.promise,new Promise((_,reject)=>setTimeout(()=>reject(Error('native_resolve_not_reached')),2000))]);if(kind==='connection-generation')f.reconnect();if(kind==='abort')abort.abort();if(kind==='configuration'){const b=f.host.object('bot',f.bot.botId);f.command('updateBotConfig',{botId:b.botId,config:{contact:{provider:'offline-blocked',model:'never-invoked'},agentPreset:'offline/empty'}},b.revision);}if(kind==='authority'){const grant=f.ledger.get('grant','native-owner');f.ledger.put('grant','native-owner',{...grant,epoch:grant.epoch+1});}release.resolve();assert.equal((await pending).ok,false);assert.equal(inserted(f).length,0);assert.equal(globalThis.__offlineIO.model,f.ioBefore);});
test('ambiguous post-send flush retains unknown receipt and lookup never resends original input',async t=>{const f=await fixture(t),store=f.ctx.get('sessions'),original=store.flush;let failed=false;store.flush=async function(...args){if(!failed){failed=true;return false;}return original.apply(this,args);};t.after(()=>{store.flush=original;});const payload=sendPayload(),first=await f.call('sendContactText',payload);assert.equal(first.ok,true);assert.equal(first.value.state,'unknown');assert.equal(inserted(f,first.value.messageId).length,1);const lookup=await f.call('inspectContactReceipt',{operationId:payload.operationId,nonce:payload.nonce});assert.equal(lookup.value.state,'durably-queued');assert.equal(lookup.value.messageId,first.value.messageId);assert.equal(inserted(f,first.value.messageId).length,1);});
test('contact stop calls the actual bound native cancel only as an accepted request',async t=>{const f=await fixture(t),payload=sendPayload(),sent=await f.call('sendContactText',payload);await tick();const stopped=await f.call('requestContactStop',{operationId:'contact-stop-one',nonce:'contact-stop-nonce',contactOperationId:payload.operationId});assert.equal(stopped.ok,true);assert.equal(stopped.value.state,'accepted');assert.equal(stopped.value.preciseNativeSettlementVerified,false);assert.equal(stopped.value.messageId,sent.value.messageId);assert.ok(f.gateSignals.length>=1);assert.equal(f.gateSignals[0].aborted,true);const again=await f.call('requestContactStop',{operationId:'contact-stop-one',nonce:'contact-stop-nonce',contactOperationId:payload.operationId});assert.equal(again.value.state,'accepted');assert.equal(globalThis.__offlineIO.model,f.ioBefore);});
test('work stop creates only exact product fence while held unknown and main contact remains writable',async t=>{const f=await fixture(t),port=f.host.openOwnedWorkSessionPort(f.caller,{botId:f.bot.botId,botEpoch:1,authorityEpoch:1});t.after(()=>port.dispose());const payload={task_id:'gui-work',goal:'Harmless work',completion_condition:'One marker'},w=port.delegate(envelope('delegateWorkSession',payload,null,{bot:1,nativeOwner:1}),payload).result;const key=JSON.stringify([w.botId,w.taskId,1]),g=f.ledger.get('workGeneration',key);f.ledger.put('workGeneration',key,{...g,state:'unknown',held:true});for(let i=0;i<14;i++){const p={task_id:'gui-cap-'+i,goal:'Harmless capacity fixture',completion_condition:'One marker'},other=port.delegate(envelope('delegateWorkSession',p,null,{bot:1,nativeOwner:1}),p).result,k=JSON.stringify([other.botId,other.taskId,1]),old=f.ledger.get('workGeneration',k);f.ledger.put('workGeneration',k,{...old,state:'unknown',held:true});}assert.equal(port.query({}).held,15);const service=f.ctx.get('sessionController'),beforeResolve=service.resolveAgent;let resolveCalls=0;service.resolveAgent=async function(...args){resolveCalls++;return beforeResolve.apply(this,args);};t.after(()=>{service.resolveAgent=beforeResolve;});const stopped=await f.call('requestWorkStop',{operationId:'work-stop-one',nonce:'work-stop-nonce',taskId:w.taskId,generation:1});assert.equal(stopped.ok,true);assert.equal(stopped.value.state,'accepted');assert.equal(stopped.value.preciseNativeSettlementVerified,false);assert.equal(resolveCalls,0);assert.equal(f.ledger.get('workGeneration',key).held,true);assert.equal(f.ledger.get('workGeneration',key).state,'unknown');assert.equal(f.ledger.get('workGeneration',key).fence.reason,'terminate');const view=await f.call('selectedView');assert.equal(view.value.work.find(r=>r.taskId===w.taskId).stop.state,'accepted');const sent=await f.call('sendContactText',sendPayload());assert.equal(sent.ok,true);assert.equal(sent.value.state,'durably-queued');});
test('conflicting nonce and owner disposal cannot cause a second native send',async t=>{const f=await fixture(t),payload=sendPayload(),first=await f.call('sendContactText',payload);assert.equal(first.ok,true);assert.equal((await f.call('sendContactText',{...payload,text:'Different harmless text'})).ok,false);assert.equal((await f.call('sendContactText',{...payload,operationId:'different-id'})).ok,false);f.owner.dispose();assert.equal((await f.call('sendContactText',sendPayload('new','new'))).ok,false);assert.equal(inserted(f).length,1);});

for(const kind of ['claimed-user','claimed-work-result','queued-user'])test('contact stop denies unrelated '+kind+' input rather than canceling shared native phase',async t=>{const f=await fixture(t),other=createUserMessage({content:[{type:'text',text:'Harmless unrelated B'}],source:{kind:kind==='claimed-work-result'?'dsh-bot-work-result':'user'}});if(kind!=='queued-user')f.originAgent.send(other,'next-step',false);const payload=sendPayload(),sent=await f.call('sendContactText',payload);assert.equal(sent.ok,true);await tick();if(kind==='queued-user')f.originAgent.send(other,'next-turn',false);const result=await f.call('requestContactStop',{operationId:'mixed-stop-'+kind,nonce:'mixed-stop-nonce-'+kind,contactOperationId:payload.operationId});assert.equal(result.ok,false);assert.equal(f.gateSignals[0].aborted,false);assert.equal(globalThis.__offlineIO.model,f.ioBefore);});
test('completed old contact operation cannot cancel a newer native request and original lookup never resends',async t=>{const f=await fixture(t),a=sendPayload(),first=await f.call('sendContactText',a);await tick();const stopped=await f.call('requestContactStop',{operationId:'a-stop',nonce:'a-stop-nonce',contactOperationId:a.operationId});assert.equal(stopped.ok,true);await f.originAgent.whenIdle();const b=sendPayload('contact-b','nonce-b'),second=await f.call('sendContactText',b);assert.equal(second.ok,true);await tick();const denied=await f.call('requestContactStop',{operationId:'stale-a-stop',nonce:'stale-a-stop-nonce',contactOperationId:a.operationId});assert.equal(denied.ok,false);assert.equal(f.gateSignals.at(-1).aborted,false);const lookup=await f.call('inspectContactReceipt',{operationId:a.operationId,nonce:a.nonce});assert.equal(lookup.value.messageId,first.value.messageId);assert.equal(inserted(f,first.value.messageId).length,1);assert.equal(inserted(f,second.value.messageId).length,1);assert.equal(globalThis.__offlineIO.model,f.ioBefore);});

test('selected view copies only bounded scoped main reply and actual input provenance from retained Session',async t=>{const f=await fixture(t),input=createUserMessage({content:[{type:'text',text:'Harmless main goal fixture'}],source:{kind:'user'}});f.originAgent.session.append('turn/start',{turn:1});f.originAgent.session.append('user/message',input,{surfaceOp:'append'});f.originAgent.session.append('assistant/message',{turn:1,step:1,message:{id:'offline-synthetic-main-response',role:'assistant',source:{kind:'model',provider:'offline-synthetic',model:'not-live'},content:[{type:'text',text:'Harmless bounded reply'}]},usage:{inputTokens:1,outputTokens:1,totalTokens:2},stream:[]},{surfaceOp:'append'});f.originAgent.session.append('turn/end',{turn:1,reason:{kind:'completed'}});const view=await f.call('selectedView');assert.equal(view.ok,true);assert.deepEqual(view.value.contact.reply,{messageId:'offline-synthetic-main-response',turn:1,text:'Harmless bounded reply',inputMessageId:input.id,inputKind:'user'});assert.equal(JSON.stringify(view).includes('not-live'),false);assert.equal(JSON.stringify(view).includes('Harmless main goal fixture'),false);assert.equal(globalThis.__offlineIO.model,f.ioBefore);});

test('ambiguous native contact cancel remains unknown and repeated original stop never cancels again',async t=>{const f=await fixture(t,{cancelFailure:true}),payload=sendPayload(),sent=await f.call('sendContactText',payload);assert.equal(sent.ok,true);await tick();const stop={operationId:'unknown-contact-stop',nonce:'unknown-contact-stop-nonce',contactOperationId:payload.operationId},first=await f.call('requestContactStop',stop);assert.equal(first.ok,false);assert.equal(f.cancelCalls(),1);assert.equal(f.gateSignals[0].aborted,true);const duplicate=await f.call('requestContactStop',stop),lookup=await f.call('inspectContactReceipt',{operationId:stop.operationId,nonce:stop.nonce});assert.equal(duplicate.ok,true);assert.equal(duplicate.value.state,'unknown');assert.equal(lookup.value.state,'unknown');assert.equal(f.cancelCalls(),1);assert.equal(duplicate.value.preciseNativeSettlementVerified,false);assert.equal(globalThis.__offlineIO.model,f.ioBefore);});

test('selected reply cannot assign singular input provenance when a native turn consumed multiple inputs',async t=>{const f=await fixture(t),a=createUserMessage({content:[{type:'text',text:'Harmless A'}],source:{kind:'user'}}),b=createUserMessage({content:[{type:'text',text:'Harmless B'}],source:{kind:'user'}});f.originAgent.session.append('turn/start',{turn:1});for(const message of[a,b])f.originAgent.session.append('user/message',message,{surfaceOp:'append'});f.originAgent.session.append('assistant/message',{turn:1,step:1,message:{id:'offline-synthetic-shared-response',role:'assistant',source:{kind:'model',provider:'offline-synthetic',model:'not-live'},content:[{type:'text',text:'Harmless shared observed reply'}]},usage:{inputTokens:1,outputTokens:1,totalTokens:2},stream:[]},{surfaceOp:'append'});f.originAgent.session.append('turn/end',{turn:1,reason:{kind:'completed'}});assert.equal((await f.call('selectedView')).value.contact.reply,null);assert.equal(globalThis.__offlineIO.model,f.ioBefore);});

// Stock bare Agent has no private generation authority, even for an authenticated operator.
test('required owned generation blocks contact RPC before original operation and native input allocation',async t=>{
 const f=await fixture(t,{requireOwnedGeneration:true});const before=f.originAgent.session.seq;
 const result=await f.call('sendContactText',sendPayload());assert.equal(result.ok,false);
 assert.equal(f.ledger.list('contactOwnerOperation').length,0);assert.equal(inserted(f).length,0);assert.equal(f.originAgent.session.seq,before);
 assert.equal((await f.call('selectedView')).ok,true);assert.equal(globalThis.__offlineIO.model,f.ioBefore);
});

for(const canSend of [()=>false,()=>Promise.resolve(true)])test('private contact admission refuses disabled or asynchronous model gate before original operation',async t=>{
 const f=await fixture(t,{canSend});const before=f.originAgent.session.seq;
 assert.equal((await f.call('sendContactText',sendPayload())).ok,false);assert.equal(f.ledger.list('contactOwnerOperation').length,0);assert.equal(inserted(f).length,0);assert.equal(f.originAgent.session.seq,before);assert.equal(globalThis.__offlineIO.model,f.ioBefore);
});

test('structural contact generation source never falls back to actual raw Agent send',async t=>{
 let calls=0;const generationSource={start(){calls++;},inspect(){calls++;},cancel(){calls++;}},f=await fixture(t,{generationSource});const before=f.originAgent.session.seq;
 assert.equal((await f.call('sendContactText',sendPayload())).ok,false);assert.equal(f.ledger.list('contactOwnerOperation').length,0);assert.equal(inserted(f).length,0);assert.equal(f.originAgent.session.seq,before);assert.equal(calls,0);assert.equal(globalThis.__offlineIO.model,f.ioBefore);
});
