import{symbols}from'@deepseek-ai/cordis';import test from'node:test';import assert from'node:assert/strict';import {stockFixture}from'./bot-producer-fixture.mjs';import {HostConnectionService}from'@deepseek-ai/dsh-client-connection';
async function api(){const m=await import('../src/selected-bot-owner-policy.mjs').catch(e=>{if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;return {};});assert.equal(typeof m.installSelectedBotOwnerPolicy,'function','missing selectedBot private owner seam');return m;}
test('write policy requires actual Host/connection/peer separately from read lease',async t=>{const a=await api(),f=await stockFixture(t);assert.throws(()=>a.installSelectedBotOwnerPolicy({...f.options,expectedHost:f.host,connection:{operator:{ctx:f.ctx}},peer:{},connectionGeneration:{},selectedBotId:f.bot.botId}));assert.throws(()=>a.installSelectedBotOwnerPolicy({...f.options,expectedHost:{...f.host},connection:{},peer:{},connectionGeneration:{},selectedBotId:f.bot.botId}));assert.equal(f.ledger.list('workTask').length,0);});
async function owned(t,actions={}){const a=await api(),f=await stockFixture(t);const connectionHandle=f.ctx.plugin(ctx=>{new HostConnectionService(ctx,[],null);});await connectionHandle.await();const traced=f.ctx.get('connection'),connection=traced[symbols.original]??traced;await connection.operator.ctx.fiber.await();let generation={};const options={ownerCtx:f.ctx,expectedHost:f.host,connection,peer:connection.operator,connectionGeneration:generation,getConnectionGeneration:()=>generation,selectedBotId:f.bot.botId,botEpoch:f.bot.epoch,authorityEpoch:1,actions};const policy=a.installSelectedBotOwnerPolicy(options);t.after(()=>policy.dispose());return {f,connection,connectionHandle,options,policy,reconnect(){generation={};}};}
test('actual operator private write policy admits selected owner action and denies copied peer, foreign Bot and disposal',async t=>{let calls=0;const q=await owned(t,{create:async payload=>{calls++;assert.equal(Object.isFrozen(payload),true);return 'accepted';}}),request={command:'create',botId:q.f.bot.botId,payload:{goal:'harmless'}};assert.equal(await q.policy.perform(q.connection.operator,request),'accepted');await assert.rejects(()=>q.policy.perform({...q.connection.operator},request),{code:'selected_bot_policy_stale'});await assert.rejects(()=>q.policy.perform(q.connection.operator,{...request,botId:'foreign'}),{code:'selected_bot_scope_denied'});q.policy.dispose();await assert.rejects(()=>q.policy.perform(q.connection.operator,request),{code:'selected_bot_policy_stale'});assert.equal(calls,1);});
test('selected owner policy rejects result after actual connection generation changes during await',async t=>{const started=Promise.withResolvers(),finish=Promise.withResolvers(),q=await owned(t,{create:async()=>{started.resolve();await finish.promise;return 'harmless';}});const pending=q.policy.perform(q.connection.operator,{command:'create',botId:q.f.bot.botId,payload:{}});await started.promise;q.reconnect();finish.resolve();await assert.rejects(()=>pending,{code:'selected_bot_policy_stale'});});
test('selected owner policy rechecks actual Bot configuration after await',async t=>{const started=Promise.withResolvers(),finish=Promise.withResolvers(),q=await owned(t,{create:async()=>{started.resolve();await finish.promise;return 'harmless';}});const pending=q.policy.perform(q.connection.operator,{command:'create',botId:q.f.bot.botId,payload:{}});await started.promise;const b=q.f.host.object('bot',q.f.bot.botId);q.f.command('updateBotConfig',{botId:b.botId,config:{contact:{provider:'offline-blocked',model:'never-invoked'},agentPreset:'offline/empty'}},b.revision);finish.resolve();await assert.rejects(()=>pending,{code:'selected_bot_binding_changed'});});

test('forged original-symbol peer and forged supplied connection cannot authenticate',async t=>{const q=await owned(t,{create:async()=>assert.fail('forged authority ran')});const forgedPeer=Object.assign(Object.create(Object.getPrototypeOf(q.connection.operator)),q.connection.operator,{[symbols.original]:q.connection.operator});await assert.rejects(()=>q.policy.perform(forgedPeer,{command:'create',botId:q.f.bot.botId,payload:{}}),{code:'selected_bot_policy_stale'});const forgedConnection=Object.assign(Object.create(HostConnectionService.prototype),{operator:q.connection.operator,[symbols.original]:q.connection});assert.throws(()=>installSelectedBotOwnerPolicyForTest(q.options,forgedConnection),{code:'selected_bot_actual_peer_required'});});
function installSelectedBotOwnerPolicyForTest(options,connection){return currentInstaller({...options,connection});}
let currentInstaller;await api().then(a=>{currentInstaller=a.installSelectedBotOwnerPolicy;});
test('actual owner connection service replacement invalidates retained policy',async t=>{const q=await owned(t,{create:async()=>assert.fail('replaced connection ran')});await q.connectionHandle.dispose();await q.f.ctx.plugin(ctx=>{new HostConnectionService(ctx,[],null);}).await();await assert.rejects(()=>q.policy.perform(q.connection.operator,{command:'create',botId:q.f.bot.botId,payload:{}}),{code:'selected_bot_policy_stale'});});
