import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture,human } from './helpers.mjs';
import { createHandler } from '../src/server.mjs';
import { prepareCommand } from '../ui/command.mjs';
import { apply } from '../src/plugin.mjs';
const origin='http://127.0.0.1:8787';
async function call(handler,{method='GET',url='/api/snapshot',headers={},body=''}={}) { const req={method,url,headers:{host:'127.0.0.1:8787',origin,'x-dsh-token':'test-only',...headers},async *[Symbol.asyncIterator](){yield Buffer.from(body);}}; const res={headers:{},setHeader(k,v){this.headers[k]=v;},writeHead(status,h){this.status=status;Object.assign(this.headers,h);},end(value){this.body=value;}};await handler(req,res);return {...res,json:JSON.parse(res.body)}; }
test('HTTP trusted entry rejects origin, rebinding and spoofed actor before side effects',async()=>{const f=fixture(),handler=createHandler({host:f.host,origin,token:'test-only',assets:{}});for(const headers of [{origin:'https://evil.invalid'},{host:'evil.invalid'},{'x-dsh-token':'wrong'}]) {const r=await call(handler,{headers});assert.equal(r.status,403);}const r=await call(handler,{method:'POST',url:'/api/command',headers:{'content-type':'application/json'},body:JSON.stringify({actor:{kind:'human',id:human.id}})});assert.equal(r.status,400);assert.equal(f.ledger.list('bot').length,0);f.ledger.close();});
test('client persists exact operation before submit, supports lookup after restart and never silently renonces',async()=>{const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};const f=fixture();const input={ledgerInstanceId:f.host.ledgerInstanceId,command:'createBot',payload:{name:'UI',config:{contact:{provider:'synthetic',model:'A'}}},expectedRevision:null,expectedEpochs:{}};const first=await prepareCommand(storage,input);const recovered=await prepareCommand(storage,input);assert.deepEqual(recovered,first);assert.equal(JSON.parse(values.get('dsh-bot-pending')).envelope.operationId,first.envelope.operationId);await assert.rejects(()=>prepareCommand(storage,{...input,payload:{...input.payload,name:'changed'}}),{code:'pending_operation'});const handler=createHandler({host:f.host,origin,token:'test-only',assets:{}});const post=()=>call(handler,{method:'POST',url:'/api/command',headers:{'content-type':'application/json'},body:JSON.stringify(first)});const a=await post(),b=await post();assert.equal(a.status,200);assert.deepEqual(a.json,b.json);assert.equal(f.ledger.list('bot').length,1);f.ledger.close();});
test('Cordis seam provides only control ledger and disposes it; fake context is not live proof',async()=>{const f=fixture();f.ledger.close();let cleanup,service,provided;const ctx={provide:(name,value)=>{provided=name;ctx[name]=value;},effect:fn=>{cleanup=fn();}};service=apply(ctx,{databasePath:f.path,ownerHumanId:human.id});assert.equal(provided,'dshBot');assert.equal(ctx.dshBot,service);assert.equal(service.snapshot(human).nativeRuntimeVerified,false);await cleanup();assert.throws(()=>service.snapshot(human));});
test('Cordis public service cannot claim a human caller or expose private ledger records',async()=>{const f=fixture();f.ledger.close();let dispose;const ctx={provide(){},effect:fn=>{dispose=fn();}};const service=apply(ctx,{databasePath:f.path,ownerHumanId:human.id});assert.throws(()=>service.execute(human,{},{}),{code:'unsupported_host_identity'});assert.equal(service.ledger,undefined);assert.equal(service.snapshot(human).bot,undefined);await dispose();});
test('two tabs cannot create distinct operations before persistence completes',async()=>{const f=fixture();const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)},input={ledgerInstanceId:f.host.ledgerInstanceId,command:'createBot',payload:{name:'race',config:{contact:{provider:'synthetic',model:'A'}}},expectedRevision:null,expectedEpochs:{}};let tail=Promise.resolve();const locks={request(_name,_options,fn){const work=tail.then(fn);tail=work.catch(()=>{});return work;}};const [a,b]=await Promise.all([prepareCommand(storage,input,locks),prepareCommand(storage,input,locks)]);assert.deepEqual(a,b);assert.equal(JSON.parse(values.get('dsh-bot-pending')).envelope.operationId,a.envelope.operationId);f.ledger.close();});
