/** Offline synthetic product contract. No Session/model/provider execution. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Host} from '../src/host.mjs';
import {Ledger} from '../src/ledger.mjs';
import {digest,canonical} from '../src/errors.mjs';
const tick=()=>new Promise(r=>setImmediate(r));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function synthetic(){const calls=[],answers=new Map();return {kind:'offline-synthetic',sourceId:'fixture-source',calls,answers,
 async start(b){calls.push(structuredClone(b));return receipt(b,'running',1);},
 async inspect(b){return answers.get(`${b.taskId}/${b.generation}`) ?? null;}};}
function receipt(b,state,sourceSeq=2,extra={}){return {receiptId:`${b.taskId}/${b.generation}/${sourceSeq}`,sourceId:'fixture-source',sourceSeq,binding:structuredClone(b),state,execution:['waiting','completed','failed','archived'].includes(state)?'quiescent':'may-execute',creation:'confirmed',...extra};}
function fixture(t,runtime){const ledger=new Ledger(':memory:'),caller={},host=new Host({ledger,ownerHumanId:'OFFLINE SYNTHETIC OWNER',ownerCapability:caller,workSessionRuntime:runtime});t.after(()=>ledger.close());
 const legacy=(command,payload,revision=null)=>host.executeOwned(caller,envelope(command,payload,revision,{}),payload).result;
 const bot=legacy('createBot',{name:'One Bot',config:{contact:{provider:'inert',model:'unused'}}});
 assert.equal(typeof host.openOwnedWorkSessionPort,'function','missing retained work-session contract');
 const ports=[];const open=(h=host,extra={})=>{const p=h.openOwnedWorkSessionPort(caller,{botId:bot.botId,botEpoch:bot.epoch,authorityEpoch:1,...extra});ports.push(p);return p;};t.after(()=>ports.forEach(p=>p.dispose()));
 const port=open();const state=(id,p=port)=>p.query({task_ids:[id]}).work[0];
 const call=(method,p,picked=port)=>{const w=p.task_id && picked.query({}).work.find(x=>x.task_id===p.task_id);const e=envelope({delegate:'delegateWorkSession',admit:'admitWorkSession',fence:'fenceWorkSession',resume:'resumeWorkSession'}[method],p,w?.revision ?? null,{nativeOwner:1,bot:bot.epoch,...w?{task:w.taskEpoch}: {}});return {e,p,result:picked[method](e,p).result};};
 const delegate=(id,p=port)=>call('delegate',{task_id:id,goal:`Goal ${id}`,completion_condition:'Inspect evidence'},p).result;
 const admit=(id,p=port)=>call('admit',{task_id:id,generation:state(id,p).generation},p).result;
 return {ledger,caller,host,bot,legacy,open,port,state,call,delegate,admit};}
function envelope(command,payload,expectedRevision,expectedEpochs){return {command,payloadDigest:digest(payload),operationId:randomUUID(),nonce:randomUUID(),expectedRevision,expectedEpochs,authorizationRef:'native-owner',rootHumanInstructionRef:'offline-synthetic-test',createdAt:new Date().toISOString(),deadline:null};}

test('default delegates stable reserved identities, reuses across ports, conflicts and never starts',t=>{const f=fixture(t),a=f.delegate('__proto__'),p=f.open(),b=f.delegate('__proto__',p);assert.equal(a.taskId,b.taskId);assert.equal(a.sessionId,b.sessionId);assert.equal(b.generation,1);assert.equal(b.creationState,'reserved');assert.equal(f.ledger.list('task').length,1);assert.equal(f.admit('__proto__').unsupported,'unsupported_work_generation_receipts');assert.equal(f.port.query({}).held,0);assert.equal(f.ledger.list('creation').length,0);
 assert.throws(()=>f.call('delegate',{task_id:'__proto__',goal:'changed',completion_condition:'Inspect evidence'}),{code:'work_task_conflict'});
 b.goal='mutated';assert.equal(f.state('__proto__').goal,'Goal __proto__');assert.equal(f.port.query({}).nativeCoverageVerified,false);
 for(const p of [{task_id:'x',goal:'x'},{task_id:'x',goal:'x',completion_condition:' '},{task_id:'x',goal:'x',completion_condition:'ok',extra:true}])assert.throws(()=>f.call('delegate',p));
 assert.throws(()=>f.port.query({task_ids:['__proto__','__proto__']}));assert.throws(()=>f.port.query({task_ids:['missing']}));assert.throws(()=>f.port.query({task_ids:Array(501).fill('x')}));});

test('15 shared reservations, duplicate reuse at saturation, 16th queued, separate Bot',async t=>{const runtime=synthetic(),f=fixture(t,runtime),p=f.open();for(let i=0;i<16;i++)f.delegate(`t${i}`,i%2?p:f.port);for(let i=0;i<14;i++)f.admit(`t${i}`);const raced=await Promise.all([Promise.resolve().then(()=>f.admit('t14',p)),Promise.resolve().then(()=>f.admit('t15'))]);assert.equal(f.port.query({}).held,15);assert.equal(raced[1].unsupported,'capacity_exhausted');assert.equal(f.delegate('t0',p).taskId,f.state('t0').taskId);f.admit('t0',p);await tick();assert.equal(runtime.calls.length,15);assert.equal(f.state('t15').state,'queued');
 const other=f.legacy('createBot',{name:'Other',config:{contact:{provider:'inert',model:'unused'}}});const q=f.host.openOwnedWorkSessionPort(f.caller,{botId:other.botId,botEpoch:1,authorityEpoch:1});try{assert.equal(q.query({}).held,0);assert.throws(()=>q.query({task_ids:['t0']}));}finally{q.dispose();}});

test('unresolved start stays queryable, ambiguous result preserves original identity and slot',async t=>{const pending=deferred(),runtime=synthetic();runtime.start=b=>{runtime.calls.push(b);return pending.promise;};const f=fixture(t,runtime),a=f.delegate('pending');f.admit('pending');await tick();assert.equal(f.state('pending').sessionId,a.sessionId);assert.equal(f.port.query({}).held,1);f.admit('pending');assert.equal(runtime.calls.length,1);pending.reject(Error('private diagnostic'));await tick();assert.equal(f.state('pending').state,'unknown');assert.equal(f.port.query({}).held,1);assert.equal(JSON.stringify(f.state('pending')).includes('private diagnostic'),false);});

test('source receipt exact binding, replay, conflict, waiting/resume and late generation isolation',async t=>{const runtime=synthetic(),f=fixture(t,runtime);f.delegate('a');f.admit('a');await tick();const b=runtime.calls[0],key=`${b.taskId}/1`,wait=receipt(b,'waiting');runtime.answers.set(key,wait);let w=await f.port.collect({task_id:'a',generation:1});assert.equal(w.state,'waiting');assert.equal(f.port.query({}).held,0);assert.deepEqual(await f.port.collect({task_id:'a',generation:1}),w);runtime.answers.set(key,{...wait,summary:'changed'});await assert.rejects(()=>f.port.collect({task_id:'a',generation:1}),{code:'work_receipt_conflict'});runtime.answers.set(key,wait);f.call('resume',{task_id:'a',generation:1});assert.equal(f.state('a').generation,2);assert.equal(f.state('a').sessionId,b.sessionId);f.admit('a');await tick();assert.equal(f.port.query({}).held,1);await f.port.collect({task_id:'a',generation:1});assert.equal(f.state('a').generation,2);assert.equal(f.state('a').state,'running');});

test('unconfirmed waiting and mismatched receipt never free held slot; fenced settlement only releases old reservation',async t=>{const runtime=synthetic(),f=fixture(t,runtime);f.delegate('a');f.admit('a');await tick();const b=runtime.calls[0],key=`${b.taskId}/1`;runtime.answers.set(key,receipt(b,'waiting',2,{execution:'may-execute'}));await f.port.collect({task_id:'a',generation:1});assert.equal(f.port.query({}).held,1);assert.throws(()=>f.call('resume',{task_id:'a',generation:1}));runtime.answers.set(key,receipt({...b,sessionId:'wrong'},'completed',3));await assert.rejects(()=>f.port.collect({task_id:'a',generation:1}));assert.equal(f.port.query({}).held,1);
 f.call('fence',{task_id:'a',generation:1,reason:'terminate'});const before=f.state('a');runtime.answers.set(key,receipt(b,'completed',4,{summary:'late completion'}));await f.port.collect({task_id:'a',generation:1});assert.equal(f.port.query({}).held,0);assert.equal(f.state('a').summary,before.summary);assert.notEqual(f.state('a').state,'completed');assert.throws(()=>f.call('resume',{task_id:'a',generation:1}));});

test('fresh Host cannot adopt old runtime with copied sourceId/quiescent receipt',async t=>{const runtime=synthetic(),f=fixture(t,runtime);f.delegate('a');f.admit('a');await tick();const original=f.state('a'),copy=synthetic();copy.answers.set(`${original.taskId}/1`,receipt(runtime.calls[0],'completed'));const other=new Host({ledger:f.ledger,ownerHumanId:'OFFLINE SYNTHETIC OWNER',ownerCapability:f.caller,workSessionRuntime:copy}),p=f.open(other);assert.equal(p.query({}).held,1);await assert.rejects(()=>p.collect({task_id:'a',generation:1}),{code:'work_source_continuity_unsupported'});assert.throws(()=>f.call('resume',{task_id:'a',generation:1},p),{code:'work_source_continuity_unsupported'});assert.deepEqual(f.state('a'),original);assert.equal(copy.calls.length,0);});

for(const action of ['terminate','dispose','revoke'])test(`deferred start rechecks ${action} and locally releases only proven never-started slot`,async t=>{const runtime=synthetic(),f=fixture(t,runtime);f.delegate('a');f.admit('a');if(action==='terminate')f.call('fence',{task_id:'a',generation:1,reason:'terminate'});else if(action==='dispose')f.port.dispose();else{const grant=f.ledger.get('grant','native-owner');f.ledger.put('grant','native-owner',{...grant,active:false});}await tick();assert.equal(runtime.calls.length,0);assert.equal(f.ledger.list('workGeneration').filter(g=>g.held).length,0);});

test('wrong authority, direct commands, disposed port and stale replay denied before mutation',t=>{const f=fixture(t),p={task_id:'a',goal:'Goal a',completion_condition:'Inspect evidence'},r=f.call('delegate',p);assert.throws(()=>f.host.openOwnedWorkSessionPort({}, {botId:f.bot.botId,botEpoch:1,authorityEpoch:1}));const read=f.host.createOwnedBotTaskReadPort(f.caller);assert.throws(()=>f.host.openOwnedWorkSessionPort(read,{botId:f.bot.botId,botEpoch:1,authorityEpoch:1}));assert.throws(()=>f.host.executeOwned(f.caller,r.e,p));assert.throws(()=>f.host.extensions?.delegateWorkSession.call(f.host,p,r.e,{kind:'host',id:f.host.ledgerInstanceId}));assert.deepEqual(f.port.delegate(r.e,p).result,r.result);const g=f.ledger.get('grant','native-owner');f.ledger.put('grant','native-owner',{...g,epoch:2});assert.throws(()=>f.port.delegate(r.e,p),{code:'unauthorized'});f.ledger.put('grant','native-owner',g);assert.throws(()=>f.port.query({}));});

test('late authority/config change cannot publish receipt or free reservation',async t=>{for(const mode of ['authority','config']){const runtime=synthetic(),pending=deferred();runtime.inspect=()=>pending.promise;const f=fixture(t,runtime);f.delegate(mode);f.admit(mode);await tick();const collecting=f.port.collect({task_id:mode,generation:1});if(mode==='authority'){const g=f.ledger.get('grant','native-owner');f.ledger.put('grant','native-owner',{...g,active:false});}else f.legacy('updateBotConfig',{botId:f.bot.botId,config:{contact:{provider:'changed',model:'unused'}}},f.ledger.get('bot',f.bot.botId).revision);pending.resolve(receipt(runtime.calls[0],'completed'));await assert.rejects(()=>collecting);assert.equal(f.ledger.list('workGeneration').filter(g=>g.held).length,1);}});

test('hard 2000ms collect bound ignores uncooperative AbortSignal without accumulating calls',async t=>{const runtime=synthetic(),pending=deferred();let lookups=0;runtime.inspect=()=>{lookups++;return pending.promise;};const f=fixture(t,runtime);f.delegate('a');f.admit('a');await tick();const start=performance.now();const v=await f.port.collect({task_id:'a',generation:1});assert.equal(v.state,'unknown');assert.ok(performance.now()-start<2300);assert.equal(f.port.query({}).held,1);await assert.rejects(()=>f.port.collect({task_id:'a',generation:1}),{code:'work_lookup_in_progress'});assert.equal(lookups,1);pending.resolve(receipt(runtime.calls[0],'completed'));await tick();assert.equal(f.port.query({}).held,1);assert.equal(f.state('a').state,'unknown');});

test('legacy actual execution shapes block; prepared creation and contact do not',async t=>{for(const state of ['prepared','admitting','admitted','driving','consumed','unknown']){const f=fixture(t,synthetic()),w=f.delegate(state);f.ledger.put('nativeBinding','protected-text-owner',{targets:{execution:{product:{botId:f.bot.botId,taskId:w.taskId},target:{id:'product-execution'}}}});f.ledger.put('nativeOperation','legacy',{operationId:'legacy',targetId:'product-execution',kind:'execution',state,native:null});const v=f.admit(state);assert.equal(v.unsupported,state==='prepared'?null:'legacy_work_unreconciled');await tick();}
 const f=fixture(t,synthetic()),w=f.delegate('contact');f.ledger.put('nativeOperation','contact',{operationId:'contact',kind:'contact',targetId:'product-contact',state:'running'});f.ledger.put('creation','unused',{kind:'execution',taskId:w.taskId,state:'prepared'});assert.equal(f.admit('contact').unsupported,null);await tick();});

test('actual child unsupported, pure policy permits multiple depth1 children and shared slots but no recursion',async t=>{const f=fixture(t);const a=f.delegate('parent');assert.equal(f.port.spawnChild({parentTaskId:a.taskId,parentSessionId:a.sessionId,parentGeneration:1,task_id:'child',goal:'Child',completion_condition:'Inspect'}).code,'child_spawn_unsupported');assert.equal(f.ledger.list('task').length,1);const {validateChildLineage,heldWorkSlots}=await import('../src/work-sessions.mjs');const parent={botId:a.botId,taskId:a.taskId,sessionId:a.sessionId,generation:1,depth:0};for(const id of ['c1','c2'])assert.doesNotThrow(()=>validateChildLineage(parent,{botId:a.botId,parentTaskId:a.taskId,parentSessionId:a.sessionId,parentGeneration:1,depth:1,taskId:id}));assert.throws(()=>validateChildLineage({...parent,depth:1},{botId:a.botId,parentTaskId:a.taskId,parentSessionId:a.sessionId,parentGeneration:1,depth:2}));assert.equal(heldWorkSlots([{botId:a.botId,held:true,depth:0},{botId:a.botId,held:true,depth:1},{botId:a.botId,held:true,depth:1}],a.botId),3);});

test('generation2 slot lease survives delayed generation1 settlement and keeps sixteenth queued',async t=>{const runtime=synthetic(),f=fixture(t,runtime);f.delegate('parent');const admitted=f.admit('parent');assert.equal(admitted.revision,f.state('parent').revision);await tick();const first=runtime.calls[0];runtime.answers.set(`${first.taskId}/1`,receipt(first,'waiting'));await f.port.collect({task_id:'parent',generation:1});f.call('resume',{task_id:'parent',generation:1});f.admit('parent');for(let i=0;i<14;i++){f.delegate(`fill${i}`);f.admit(`fill${i}`);}await tick();const current=f.state('parent');assert.deepEqual(current.slotLease,{taskId:current.taskId,sessionId:current.sessionId,generation:2,operationId:runtime.calls[1].operationId});assert.equal(f.port.query({}).held,15);runtime.answers.set(`${first.taskId}/1`,receipt(first,'completed',3));await f.port.collect({task_id:'parent',generation:1});assert.deepEqual(f.state('parent').slotLease,current.slotLease);assert.equal(f.port.query({}).held,15);f.delegate('sixteenth');assert.equal(f.admit('sixteenth').unsupported,'capacity_exhausted');assert.equal(runtime.calls.length,16);});

test('runtime invocation occurs in the validated start turn, not an extra unfenced microtask',async t=>{let live=true,observed=null;const runtime=synthetic();runtime.start=async b=>{observed=live;return receipt(b,'running',1);};const f=fixture(t,runtime),p=f.open(f.host,{isCurrent:()=>live});f.delegate('a',p);f.admit('a',p);queueMicrotask(()=>{live=false;});await tick();assert.equal(observed,true);});

test('receipt lookup rejection reports safe unknown and does not disclose adapter error',async t=>{const runtime=synthetic();runtime.inspect=async()=>{throw Error('PRIVATE ADAPTER CONTENT');};const f=fixture(t,runtime);f.delegate('a');f.admit('a');await tick();const v=await f.port.collect({task_id:'a',generation:1});assert.equal(v.state,'unknown');assert.equal(v.unsupported,'work_lookup_failed');assert.equal(f.port.query({}).held,1);assert.equal(JSON.stringify(v).includes('PRIVATE'),false);});

for(const mode of ['config','authority'])test(`fresh port cannot silently reauthorize old queued work after ${mode} change`,async t=>{const runtime=synthetic(),f=fixture(t,runtime),w=f.delegate('a');let epoch=1;if(mode==='config')f.legacy('updateBotConfig',{botId:f.bot.botId,config:{contact:{provider:'new',model:'unused'}}},f.ledger.get('bot',f.bot.botId).revision);else{const g=f.ledger.get('grant','native-owner');epoch=2;f.ledger.put('grant','native-owner',{...g,epoch});}const p=f.open(f.host,{authorityEpoch:epoch}),payload={task_id:'a',generation:1},e=envelope('admitWorkSession',payload,w.revision,{nativeOwner:epoch,bot:1,task:1});assert.throws(()=>p.admit(e,payload),{code:'work_binding_stale'});await tick();assert.equal(runtime.calls.length,0);assert.equal(f.ledger.list('workGeneration').filter(g=>g.held).length,0);});

test('cached delegation cannot return pre-fence or pre-resume generation as current success',async t=>{const runtime=synthetic(),f=fixture(t,runtime),r=f.call('delegate',{task_id:'a',goal:'Goal a',completion_condition:'Inspect evidence'});f.admit('a');await tick();f.call('fence',{task_id:'a',generation:1,reason:'handoff'});assert.throws(()=>f.port.delegate(r.e,r.p),{code:'work_replay_stale'});assert.equal(f.delegate('a').fence.reason,'handoff');});

test('receipt state cannot regress from settling to running on a higher source sequence',async t=>{const runtime=synthetic(),f=fixture(t,runtime);f.delegate('a');f.admit('a');await tick();const b=runtime.calls[0],k=`${b.taskId}/1`;runtime.answers.set(k,receipt(b,'settling',2));await f.port.collect({task_id:'a',generation:1});runtime.answers.set(k,receipt(b,'running',3));await assert.rejects(()=>f.port.collect({task_id:'a',generation:1}),{code:'work_receipt_transition_conflict'});assert.equal(f.state('a').state,'settling');});

test('legacy unsettled reservation blocks even when product state says settled',async t=>{const f=fixture(t,synthetic()),w=f.delegate('a');f.ledger.put('nativeBinding','protected-text-owner',{targets:{execution:{product:{botId:f.bot.botId,taskId:w.taskId},target:{id:'product-execution'}}}});f.ledger.put('nativeOperation','old',{operationId:'old',targetId:'product-execution',kind:'execution',state:'settled',native:{state:'settled',reservationHeld:true}});assert.equal(f.admit('a').unsupported,'legacy_work_unreconciled');await tick();assert.equal(f.port.query({}).held,0);});

// Fix round 1: missing observations cannot revoke trusted settlement or retarget another work item.
for(const state of ['waiting','completed','failed','archived'])for(const ending of ['null','reject'])test(`fix1 trusted ${state} survives later ${ending} observation byte-for-byte`,async t=>{
 const runtime=synthetic();let rejectRead=false;runtime.inspect=async b=>{if(rejectRead)throw Error('PRIVATE FAILURE');return runtime.answers.get(`${b.taskId}/${b.generation}`)??null;};const f=fixture(t,runtime);f.delegate('a');f.admit('a');await tick();const b=runtime.calls[0],k=`${b.taskId}/1`;runtime.answers.set(k,receipt(b,state,2,{summary:`trusted ${state}`}));await f.port.collect({task_id:'a',generation:1});const before=f.state('a');runtime.answers.delete(k);rejectRead=ending==='reject';assert.deepEqual(await f.port.collect({task_id:'a',generation:1}),before);assert.deepEqual(f.state('a'),before);assert.equal(f.port.query({}).held,0);if(state==='waiting')assert.equal(f.call('resume',{task_id:'a',generation:1}).result.generation,2);else assert.throws(()=>f.call('resume',{task_id:'a',generation:1}),{code:'work_resume_unconfirmed'});
});

for(const state of ['waiting','completed'])for(const ending of ['reject','timeout'])test(`fix1 running lookup pending then trusted ${state} then old ${ending} keeps exact result/lease`,async t=>{
 const start=deferred(),lookup=deferred(),runtime=synthetic();let b,reads=0;runtime.start=binding=>{b=binding;return start.promise;};runtime.inspect=async()=>++reads===1?receipt(b,'running',1):lookup.promise;const f=fixture(t,runtime);f.delegate('a');f.admit('a');await tick();await f.port.collect({task_id:'a',generation:1});assert.equal(f.state('a').state,'running');const pending=f.port.collect({task_id:'a',generation:1});await tick();start.resolve(receipt(b,state,2,{summary:'authoritative result'}));await tick();const trusted=f.state('a');assert.equal(trusted.state,state);assert.equal(f.port.query({}).held,0);if(ending==='reject')lookup.reject(Error('late old lookup'));assert.deepEqual(await pending,trusted);assert.deepEqual(f.state('a'),trusted);assert.equal(f.port.query({}).held,0);if(ending==='timeout'){lookup.reject(Error('quarantined late rejection'));await tick();assert.deepEqual(f.state('a'),trusted);}
});

for(const state of ['waiting','completed','failed','archived'])test(`fix1 trusted ${state} survives late start rejection`,async t=>{
 const start=deferred(),runtime=synthetic();let b;runtime.start=binding=>{b=binding;return start.promise;};runtime.inspect=async()=>receipt(b,state,2,{summary:'trusted before start response'});const f=fixture(t,runtime);f.delegate('a');f.admit('a');await tick();await f.port.collect({task_id:'a',generation:1});const before=f.state('a');start.reject(Error('late start failure'));await tick();assert.deepEqual(f.state('a'),before);assert.equal(f.port.query({}).held,0);
});

for(const ending of ['null','reject','receipt'])test(`fix1 detached collect target ignores A-to-B and generation mutation on ${ending}`,async t=>{
 const lookup=deferred(),runtime=synthetic();let observed;runtime.inspect=b=>{observed=b;return lookup.promise;};const f=fixture(t,runtime);for(const id of ['a','b']){f.delegate(id);f.admit(id);}await tick();const beforeB=f.state('b'),beforeA=f.state('a'),target={task_id:'a',generation:1},pending=f.port.collect(target);await tick();assert.equal(observed.taskId,beforeA.taskId);target.task_id='b';target.generation=999;if(ending==='reject')lookup.reject(Error('A-only failure'));else lookup.resolve(ending==='null'?null:receipt(observed,'completed',2,{summary:'A-only receipt'}));const value=await pending;assert.equal(value.taskId,beforeA.taskId);assert.equal(value.generation,1);assert.equal(value.state,ending==='receipt'?'completed':'unknown');assert.deepEqual(f.state('b'),beforeB);assert.deepEqual(f.state('a').slotLease,beforeA.slotLease);assert.equal(f.port.query({}).held,ending==='receipt'?1:2);
});

test('fix1 pending g1 failure after trusted release and resumed g2 never changes newer slot lease',async t=>{
 const start=deferred(),lookup=deferred(),runtime=synthetic();let first,reads=0;runtime.start=b=>{runtime.calls.push(b);if(b.generation===1){first=b;return start.promise;}return Promise.resolve(receipt(b,'running',1));};runtime.inspect=async b=>b.generation===1?(++reads===1?receipt(first,'running',1):reads===2?lookup.promise:receipt(first,'completed',3)):null;const f=fixture(t,runtime);f.delegate('a');f.admit('a');await tick();await f.port.collect({task_id:'a',generation:1});const pending=f.port.collect({task_id:'a',generation:1});await tick();start.resolve(receipt(first,'waiting',2));await tick();assert.equal(f.port.query({}).held,0);f.call('resume',{task_id:'a',generation:1});f.admit('a');await tick();const newer=f.state('a');assert.equal(newer.slotLease.generation,2);assert.equal(f.port.query({}).held,1);lookup.reject(Error('old generation observation failed'));assert.deepEqual(await pending,newer);assert.deepEqual(f.state('a'),newer);await f.port.collect({task_id:'a',generation:1});await f.port.collect({task_id:'a',generation:1});assert.deepEqual(f.state('a'),newer);assert.equal(f.port.query({}).held,1);
});

test('retained Bot scope rejects another Bot delegation receipt on operation and nonce replay',t=>{
 const f=fixture(t),a=f.call('delegate',{task_id:'shared-external-id',goal:'Goal',completion_condition:'Inspect evidence'}),other=f.legacy('createBot',{name:'Other Bot',config:{contact:{provider:'inert',model:'unused'}}});
 const b=f.host.openOwnedWorkSessionPort(f.caller,{botId:other.botId,botEpoch:1,authorityEpoch:1});t.after(()=>b.dispose());
 const replayErrors=[a.e,{...a.e,operationId:randomUUID()}].map(e=>{try{b.delegate(e,a.p);return null;}catch(error){return error.code;}});assert.deepEqual(replayErrors,['work_bot_conflict','work_bot_conflict']);
 assert.equal(b.query({}).work.length,0);assert.equal(f.port.query({}).work[0].taskId,a.result.taskId);assert.equal(f.ledger.list('task').length,1);
 const fresh=envelope('delegateWorkSession',a.p,null,{nativeOwner:1,bot:1}),made=b.delegate(fresh,a.p).result;assert.equal(made.botId,other.botId);assert.notEqual(made.taskId,a.result.taskId);assert.notEqual(made.sessionId,a.result.sessionId);
});
