/** Actual SDK parent ToolCall/child ownership; only the SSE transport is synthetic. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {scopeOf} from '@deepseek-ai/dsh-scope';
import {SessionCreationDriver} from '../src/session-creation.mjs';
import {installOwnedBotProducer} from '../src/bot-producer.mjs';
import {canonical} from '../src/errors.mjs';
import {createUserMessage} from '@deepseek-ai/dsh-llm';
import {generationFixture,syntheticResponse,observeUntil,route,envelope} from './work-generation-fixture.mjs';

function delegateResponse(task_id='native-child'){
 const events=[{type:'message_start',message:{usage:{input_tokens:5}}},{type:'content_block_start',index:0,content_block:{type:'tool_use',id:crypto.randomUUID(),name:'dsh_bot_delegate',input:{task_id,goal:'child-original-native-work',completion_condition:'Keep exact child binding'}}},{type:'content_block_stop',index:0},{type:'message_delta',delta:{stop_reason:'tool_use'},usage:{output_tokens:3}},{type:'message_stop'}];
 return new Response(events.map(event=>'data: '+JSON.stringify(event)+'\n\n').join(''));
}

test('actual original parent delegate creates a zero-tool child that remains held after parent returns',async t=>{
 const childResponse=Promise.withResolvers();let parentRequests=0,childPreparations=0,childRequested=false;
 t.after(()=>childResponse.resolve(syntheticResponse({finish:false})));const f=await generationFixture(t,(_url,init)=>{const body=JSON.parse(init.body),wire=JSON.stringify(body.messages),input=JSON.stringify(body.messages.find(m=>m.role==='user')?.content);if(input.includes('Goal: child-original-native-work')){childRequested=true;return childResponse.promise;}if(wire.includes('parent-original-native-work')&&!wire.includes('tool_result')&&parentRequests++===0)return delegateResponse();return syntheticResponse();});
 const i=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),mainPort=f.host.adapter.ownedGenerationCreationPort([i.sessionId],{scopeOf,role:'main',prepareGeneration:intent=>f.prepareGeneration(intent,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,i.operationId),main=f.ctx.agents.get(i.sessionId);
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:main,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'keyless-actual-parent-child',execution:{beforeExecute:async()=>{},generationControl:{bindMainDelegateTool:d=>f.host.adapter.bindOwnedMainGeneration(mainPort,created,d),prepareWorkGeneration:(intent,options)=>{assert.equal(options.delegateTool.name,'dsh_bot_delegate');return{route:route,prepared:f.Native.prepareOwnedGenerationSource({ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup('deepseek-official'),sessionId:intent.sessionId,role:'work',route:route,workDelegate:{plannedBinding:options.plannedBinding,delegateTool:options.delegateTool},isCurrent:()=>true})};},prepareChildGeneration:(intent,original)=>{childPreparations++;assert.equal(intent.workDepth,1);assert.equal(canonical(intent.parentBinding),canonical(original.parentBinding));assert.throws(()=>f.Native.prepareOwnedChildGenerationSource({...original.parentSource},original.parentGeneration,{ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup('deepseek-official'),sessionId:intent.sessionId,route:route,isCurrent:()=>true}));return{route:route,prepared:f.Native.prepareOwnedChildGenerationSource(original.parentSource,original.parentGeneration,{ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup('deepseek-official'),sessionId:intent.sessionId,route:route,plannedBinding:original.plannedBinding,isCurrent:()=>true})};}}}});t.after(()=>producer.dispose());
 const parent=await producer.delegate({operationId:'original-parent-delegate',nonce:'original-parent-delegate',task_id:'native-parent',goal:'parent-original-native-work',completion_condition:'Create one original child'});assert.equal(f.ctx.tools.schemas(main).length,1);assert.equal(f.ctx.tools.schemas(f.ctx.agents.get(parent.sessionId)).length,1);
 await producer.execute({task_id:parent.task_id,generation:1});await observeUntil(()=>childRequested,value=>value===true);
 const settled=await observeUntil(()=>producer.query({task_ids:['native-parent']}),value=>value.work[0].generationObservation.settlementVerified);assert.equal(settled.work[0].held,false);
 const child=producer.query({task_ids:['native-child']}).work[0],parentAgent=f.ctx.agents.get(parent.sessionId),childAgent=f.ctx.agents.get(child.sessionId);assert.equal(childPreparations,1);assert.equal(child.held,true);assert.equal(child.depth,1);assert.equal(child.parentGeneration,1);assert.equal(childAgent.session.header.parentSession,parent.sessionId);assert.equal(childAgent.session.header.origin,'subagent');assert.equal(childAgent.session.header.delegationDepth,1);assert.equal(f.ctx.agents.isOwnedBy(child.sessionId,parentAgent),true);assert.equal(f.ctx.tools.schemas(childAgent).length,0);assert.equal(producer.assertWorkAgentTools(parentAgent),true);assert.equal(producer.assertWorkAgentTools(childAgent),true);assert.equal(settled.held,1);assert.equal(f.ctx.tools.schemas().length,0);
 childResponse.resolve(syntheticResponse({finish:false}));await childAgent.whenIdle();const original=f.ledger.list('workGeneration').find(g=>g.taskId===child.taskId);assert.equal(original.binding.parentWorkBinding.sessionId,parent.sessionId);assert.equal(original.binding.parentWorkBinding.generation,1);assert.equal(original.slotLease.operationId,intentNonce(f,child));
 assert.equal(f.host.object('task',parent.taskId).responsibility,'open');
});
const intentNonce=(f,child)=>f.ledger.list('workChildAdmission').find(row=>row.taskId===child.taskId).operationId;

async function parentProducer(t,f,onChildPrepared=()=>{}){
 const intent=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),port=f.host.adapter.ownedGenerationCreationPort([intent.sessionId],{scopeOf,role:'main',prepareGeneration:i=>f.prepareGeneration(i,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port}).run(f.caller,intent.operationId);
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:f.ctx.agents.get(intent.sessionId),botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'actual-native-child-shared-capacity',execution:{beforeExecute:async()=>{},generationControl:{bindMainDelegateTool:d=>f.host.adapter.bindOwnedMainGeneration(port,created,d),prepareWorkGeneration:(i,o)=>({route,prepared:f.Native.prepareOwnedGenerationSource({ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup(route.provider),sessionId:i.sessionId,role:'work',route,workDelegate:{plannedBinding:o.plannedBinding,delegateTool:o.delegateTool},isCurrent:()=>true})}),prepareChildGeneration:(i,o)=>{onChildPrepared(i,o);return{route,prepared:f.Native.prepareOwnedChildGenerationSource(o.parentSource,o.parentGeneration,{ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup(route.provider),sessionId:i.sessionId,route,plannedBinding:o.plannedBinding,isCurrent:()=>true})};}}}});t.after(()=>producer.dispose());return producer;
}
function ordinaryPort(t,f){const port=f.host.openOwnedWorkSessionPort(f.caller,{botId:f.bot.botId,botEpoch:1,authorityEpoch:1,creation:{cwd:f.directory,portFor:i=>f.host.adapter.ownedGenerationCreationPort([i.sessionId],{scopeOf,role:'work',prepareGeneration:intent=>f.prepareGeneration(intent),isCurrent:()=>true})},producer:{execution:true,requireOwnedGeneration:true,provenance:{producerId:'actual-ordinary-fourteen',ingress:'owner',originSessionId:'capacity-main'},isCurrent:()=>true,createMessage:(binding,provenance,text)=>createUserMessage({source:{kind:'dsh-bot',...provenance,...binding},content:[{type:'text',text}]}),send:async()=>{throw Error('RAW_CAPACITY_SEND_DENIED');},inspect:async()=>false}});t.after(()=>port.dispose());const query=id=>port.query({task_ids:[id]}).work[0],call=(method,command,payload)=>port[method](envelope(command,payload,method==='delegate'?null:query(payload.task_id).revision,{nativeOwner:1,bot:1,...method==='delegate'?{}:{task:1}}),payload);return{port,query,call};}

test('fourteen real held native sessions plus parent use the shared fifteenth slot before child admission',async t=>{
 const firstResponse=Promise.withResolvers();t.after(()=>firstResponse.resolve(syntheticResponse()));let parentRequests=0,childPreparations=0;
 const f=await generationFixture(t,(_url,init)=>{const body=JSON.parse(init.body),input=JSON.stringify(body.messages.find(m=>m.role==='user')?.content);if(input.includes('capacity-held-0'))return firstResponse.promise;if(input.includes('capacity-held-'))return syntheticResponse({finish:false});if(input.includes('parent-original-native-work'))return parentRequests++%2===0?delegateResponse():syntheticResponse();if(input.includes('Goal: child-original-native-work'))return syntheticResponse({finish:false});return syntheticResponse();}),producer=await parentProducer(t,f,()=>{childPreparations++;assert.equal(producer.query({}).held,15);}),ordinary=ordinaryPort(t,f);
 for(let n=0;n<14;n++){const task_id='capacity-held-'+n;ordinary.call('delegate','delegateWorkSession',{task_id,goal:task_id,completion_condition:'Truthful original native UNKNOWN'});await ordinary.call('createSession','prepareWorkSessionCreation',{task_id,generation:1});await ordinary.call('executeMessage','prepareWorkSessionExecution',{task_id,generation:1});}await f.waitRequest(14);assert.equal(ordinary.port.query({}).held,14);assert.equal(new Set(f.ledger.list('workTask').map(w=>w.sessionId)).size,14);
 const parent=await producer.delegate({operationId:'capacity-parent',nonce:'capacity-parent',task_id:'capacity-parent',goal:'parent-original-native-work',completion_condition:'One child uses the same fifteen slots'});assert.equal(producer.query({}).held,15);await producer.execute({task_id:parent.task_id,generation:1});await observeUntil(()=>producer.query({task_ids:[parent.task_id]}),value=>value.work[0].nativeRuntimeVerified);assert.equal(childPreparations,0);assert.equal(f.ledger.list('workChildAdmission').length,0);assert.equal(f.ledger.list('workTask').length,15);assert.equal(producer.query({}).held,14);
 const original=f.ledger.list('workGeneration').find(g=>g.taskId===ordinary.query('capacity-held-0').taskId);firstResponse.resolve(syntheticResponse());const released=await observeUntil(()=>ordinary.port.collect({task_id:'capacity-held-0',generation:1}),value=>value.nativeRuntimeVerified);assert.equal(released.held,false);assert.deepEqual(f.ledger.list('workGeneration').find(g=>g.taskId===released.taskId).slotLease,original.slotLease);assert.equal(producer.query({}).held,13);
 const request={operationId:'capacity-parent-continue',nonce:'capacity-parent-continue',taskId:parent.taskId,sessionId:parent.sessionId,generation:1};await observeUntil(()=>producer.canContinueOriginalWork(request),v=>v===true);const continued=await producer.continueOriginalWork(request);assert.equal(continued.generation,2);await observeUntil(()=>producer.query({}),value=>value.work.some(w=>w.task_id==='native-child'&&w.sessionCreation.state==='created'&&w.generationObservation.local!=='unknown'));const child=producer.query({task_ids:['native-child']}).work[0];assert.equal(childPreparations,1);assert.equal(child.held,true);assert.equal(f.ctx.tools.schemas(f.ctx.agents.get(child.sessionId)).length,0);assert.equal(f.ctx.agents.isOwnedBy(child.sessionId,f.ctx.agents.get(parent.sessionId)),true);assert.equal(f.ledger.list('workTask').length,16);assert.equal(f.ledger.list('workChildAdmission')[0].parentBinding.generation,2);assert.equal(producer.query({}).held<=15,true);
});

test('stopping parent generation two also fences its still-held original generation-one child before exact abort',async t=>{
 let parentRequests=0,childRequested=false,aborts=0,fenceFacts=[];const f=await generationFixture(t,(_url,init)=>{const body=JSON.parse(init.body),input=JSON.stringify(body.messages.find(m=>m.role==='user')?.content);if(input.includes('Goal: child-original-native-work')){childRequested=true;return new Promise((_,reject)=>init.signal.addEventListener('abort',()=>{aborts++;const rows=f.ledger.list('workGeneration');fenceFacts.push([rows.find(g=>g.taskId===parent.taskId&&g.generation===2)?.fence?.reason,rows.find(g=>g.taskId===child.taskId&&g.generation===1)?.fence?.reason]);reject(init.signal.reason);},{once:true}));}if(input.includes('parent-original-native-work')&&parentRequests++===0)return delegateResponse();return syntheticResponse();}),producer=await parentProducer(t,f);
 const parent=await producer.delegate({operationId:'tree-original-parent',nonce:'tree-original-parent',task_id:'tree-parent',goal:'parent-original-native-work',completion_condition:'Stop original descendants without replacement'});await producer.execute({task_id:parent.task_id,generation:1});await observeUntil(()=>childRequested,value=>value);await observeUntil(()=>producer.query({task_ids:[parent.task_id]}),value=>value.work[0].nativeRuntimeVerified);const child=producer.query({task_ids:['native-child']}).work[0],originalChild=f.ledger.list('workGeneration').find(g=>g.taskId===child.taskId);await observeUntil(()=>producer.canContinueOriginalWork({taskId:parent.taskId,sessionId:parent.sessionId,generation:1}),v=>v===true);await producer.continueOriginalWork({operationId:'tree-parent-next',nonce:'tree-parent-next',taskId:parent.taskId,sessionId:parent.sessionId,generation:1});await observeUntil(()=>producer.query({task_ids:[parent.task_id]}),value=>value.work[0].nativeRuntimeVerified);
 const port=f.host.openOwnedWorkSessionPort(f.caller,{botId:f.bot.botId,botEpoch:1,authorityEpoch:1});t.after(()=>port.dispose());const target={task_id:parent.task_id,generation:2,reason:'terminate'},current=port.query({task_ids:[parent.task_id]}).work[0],stopEnvelope=envelope('fenceWorkSession',target,current.revision,{nativeOwner:1,bot:1,task:1});await port.stop(stopEnvelope,target);assert.equal(aborts,1);assert.deepEqual(fenceFacts,[['terminate','terminate']]);const stoppedChild=f.ledger.list('workGeneration').find(g=>g.taskId===child.taskId);assert.equal(stoppedChild.held,true);assert.deepEqual(stoppedChild.slotLease,originalChild.slotLease);assert.equal(stoppedChild.generationObservation.remote,'UNKNOWN');assert.equal(stoppedChild.generationObservation.local,'returned');assert.equal(f.ledger.list('workGeneration').find(g=>g.taskId===parent.taskId&&g.generation===1).fence.reason,'resumed');assert.equal(f.ledger.list('workStopTree')[0].generations.some(g=>g.taskId===child.taskId&&g.generation===1),true);await port.stop(stopEnvelope,target);assert.equal(aborts,1);assert.equal(producer.query({}).held,1);
});
