/** Actual SDK parent ToolCall/child ownership; only the SSE transport is synthetic. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {scopeOf} from '@deepseek-ai/dsh-scope';
import {SessionCreationDriver} from '../src/session-creation.mjs';
import {installOwnedBotProducer} from '../src/bot-producer.mjs';
import {canonical} from '../src/errors.mjs';
import {generationFixture,syntheticResponse,observeUntil,route} from './work-generation-fixture.mjs';

function delegateResponse(task_id='native-child'){
 const events=[{type:'message_start',message:{usage:{input_tokens:5}}},{type:'content_block_start',index:0,content_block:{type:'tool_use',id:crypto.randomUUID(),name:'dsh_bot_delegate',input:{task_id,goal:'child-original-native-work',completion_condition:'Keep exact child binding'}}},{type:'content_block_stop',index:0},{type:'message_delta',delta:{stop_reason:'tool_use'},usage:{output_tokens:3}},{type:'message_stop'}];
 return new Response(events.map(event=>'data: '+JSON.stringify(event)+'\n\n').join(''));
}

test('actual original parent delegate creates a zero-tool child that remains held after parent returns',async t=>{
 const childResponse=Promise.withResolvers();let parentRequests=0,childPreparations=0,childRequested=false;
 t.after(()=>childResponse.resolve(syntheticResponse({finish:false})));const f=await generationFixture(t,(_url,init)=>{const body=JSON.parse(init.body),wire=JSON.stringify(body.messages),input=JSON.stringify(body.messages.find(m=>m.role==='user')?.content);if(input.includes('Goal: child-original-native-work')){childRequested=true;return childResponse.promise;}if(wire.includes('parent-original-native-work')&&!wire.includes('tool_result')&&parentRequests++===0)return delegateResponse();return syntheticResponse();});
 const i=f.command('prepareContactSession',{botId:f.bot.botId,cwd:f.directory},f.bot.revision),mainPort=f.host.adapter.ownedGenerationCreationPort([i.sessionId],{scopeOf,role:'main',prepareGeneration:intent=>f.prepareGeneration(intent,'main'),isCurrent:()=>true}),created=await new SessionCreationDriver({host:f.host,caller:f.caller,port:mainPort}).run(f.caller,i.operationId),main=f.ctx.agents.get(i.sessionId);
 const producer=installOwnedBotProducer({ownerCtx:f.ctx,host:f.host,caller:f.caller,originAgent:main,botId:f.bot.botId,botEpoch:1,authorityEpoch:1,cwd:f.directory,rootInstructionRef:'keyless-actual-parent-child',execution:{beforeExecute:async()=>{},generationControl:{bindMainDelegateTool:d=>f.host.adapter.bindOwnedMainGeneration(mainPort,created,d),prepareWorkGeneration:(intent,options)=>{assert.equal(options.delegateTool.name,'dsh_bot_delegate');return{route:route,prepared:f.Native.prepareOwnedGenerationSource({ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup('deepseek-official'),sessionId:intent.sessionId,role:'work',route:route,workDelegate:{plannedBinding:options.plannedBinding,delegateTool:options.delegateTool},isCurrent:()=>true})};},prepareChildGeneration:(intent,original)=>{childPreparations++;assert.equal(intent.workDepth,1);assert.equal(canonical(intent.parentBinding),canonical(original.parentBinding));assert.throws(()=>f.Native.prepareOwnedChildGenerationSource({...original.parentSource},original.parentGeneration,{ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup('deepseek-official'),sessionId:intent.sessionId,route:route,isCurrent:()=>true}));return{route:route,prepared:f.Native.prepareOwnedChildGenerationSource(original.parentSource,original.parentGeneration,{ownerCtx:f.ctx,providerFactory:f.ctx.deepseekProtectedProviders.lookup('deepseek-official'),sessionId:intent.sessionId,route:route,plannedBinding:original.plannedBinding,isCurrent:()=>true})};}}}});t.after(()=>producer.dispose());
 const parent=await producer.delegate({operationId:'original-parent-delegate',nonce:'original-parent-delegate',task_id:'native-parent',goal:'parent-original-native-work',completion_condition:'Create one original child'});assert.equal(f.ctx.tools.schemas(main).length,1);assert.equal(f.ctx.tools.schemas(f.ctx.agents.get(parent.sessionId)).length,1);
 await producer.execute({task_id:parent.task_id,generation:1});await observeUntil(()=>childRequested,value=>value===true);
 const settled=await observeUntil(()=>producer.query({task_ids:['native-parent']}),value=>value.work[0].generationObservation.settlementVerified);assert.equal(settled.work[0].held,false);
 const child=producer.query({task_ids:['native-child']}).work[0],parentAgent=f.ctx.agents.get(parent.sessionId),childAgent=f.ctx.agents.get(child.sessionId);assert.equal(childPreparations,1);assert.equal(child.held,true);assert.equal(child.depth,1);assert.equal(child.parentGeneration,1);assert.equal(childAgent.session.header.parentSession,parent.sessionId);assert.equal(childAgent.session.header.origin,'subagent');assert.equal(childAgent.session.header.delegationDepth,1);assert.equal(f.ctx.agents.isOwnedBy(child.sessionId,parentAgent),true);assert.equal(f.ctx.tools.schemas(childAgent).length,0);assert.equal(producer.assertWorkAgentTools(parentAgent),true);assert.equal(producer.assertWorkAgentTools(childAgent),true);assert.equal(settled.held,1);assert.equal(f.ctx.tools.schemas().length,0);
 childResponse.resolve(syntheticResponse({finish:false}));await childAgent.whenIdle();const original=f.ledger.list('workGeneration').find(g=>g.taskId===child.taskId);assert.equal(original.binding.parentWorkBinding.sessionId,parent.sessionId);assert.equal(original.binding.parentWorkBinding.generation,1);assert.equal(original.slotLease.operationId,intentNonce(f,child));
 assert.equal(f.host.object('task',parent.taskId).responsibility,'open');
});
const intentNonce=(f,child)=>f.ledger.list('workChildAdmission').find(row=>row.taskId===child.taskId).operationId;
