import net from 'node:net';
import http from 'node:http';
import https from 'node:https';
import dns from 'node:dns';
import dgram from 'node:dgram';
import child from 'node:child_process';
const attempts = { network: 0, listener: 0, subprocess: 0, fetch: 0 };
const deny = name => () => { attempts[name]++; throw Error('OFFLINE_' + name); };
net.Socket.prototype.connect = deny('network'); net.Server.prototype.listen = deny('listener');
http.request = https.request = http.get = https.get = dns.lookup = dns.resolve = dgram.createSocket = deny('network');
for (const name of ['spawn', 'spawnSync', 'exec', 'execSync', 'execFile', 'execFileSync', 'fork']) child[name] = deny('subprocess');
globalThis.fetch = deny('fetch');
process.on('exit', () => process.stderr.write(JSON.stringify({ offlineIO: attempts }) + '\n'));
