// Every test and test-runner subtest inherits this guard. No native runtime imports.
import fs from 'node:fs';
import net from 'node:net';
import http from 'node:http';
import https from 'node:https';
import tls from 'node:tls';
import child from 'node:child_process';
import dgram from 'node:dgram';
import http2 from 'node:http2';
import { syncBuiltinESMExports } from 'node:module';
import { resolve } from 'node:path';
if (!process.env.DSH_BOT_TEST_ROOT || !process.permission?.has('fs.write', process.env.DSH_BOT_TEST_ROOT)) throw Error('Test safety guard requires isolated filesystem permissions');
if (!resolve(process.env.DSH_HOME).startsWith(resolve(process.env.DSH_BOT_TEST_ROOT) + '/')) throw Error('Production DSH_HOME forbidden');
for(const key of Object.keys(process.env)) if(!['DSH_HOME','DSH_BOT_TEST_ROOT','TMPDIR','TZ','LANG','NODE_TEST_CONTEXT'].includes(key)) delete process.env[key];
fs.mkdirSync(process.env.DSH_HOME, {recursive: true});
const deny = () => { throw Error('DSH_BOT_TEST_SIDE_EFFECT_DENIED'); };
globalThis.fetch = deny;
for (const [mod, names] of [[net,['connect','createConnection','createServer']], [http,['request','get','createServer']], [https,['request','get','createServer']], [tls,['connect','createServer']], [dgram,['createSocket']], [http2,['connect','createServer','createSecureServer']], [child,['spawn','spawnSync','exec','execSync','execFile','execFileSync','fork']]]) for (const name of names) mod[name] = deny;
net.Socket.prototype.connect=deny;
net.Server.prototype.listen=deny;
dgram.Socket.prototype.send=deny;
dgram.Socket.prototype.connect=deny;
syncBuiltinESMExports();
