import type {Host,CreationIntent,OwnedGenerationCreationPort} from './contracts.js';
import type {DshAdapter} from './adapter.mjs';
import type {ToolDefinition} from '@deepseek-ai/dsh-tools';
declare const restoreGrantBrand:unique symbol;
/** Exact private scope only. Actual SDK journals/selectors still require independent native branding. */
export interface OwnedBotLifecycleRestoreGrant {readonly [restoreGrantBrand]:true}
export interface OwnedBotLifecycleRequest {readonly operationId:string;readonly nonce:string;readonly botId:string;readonly botEpoch:number}
export interface OwnedBotLifecycleQuery {readonly botEpoch:number;readonly lifecycle:string;readonly canArchive:boolean;readonly canRestore:boolean}
export interface OwnedBotLifecycleReceipt extends OwnedBotLifecycleQuery {readonly operationId:string;readonly nonce:string;readonly botId:string;readonly state:'accepted'|'unknown';readonly nativeArchiveVerified:boolean;readonly nativeRestoreVerified:boolean}
export interface OwnedBotLifecycleRestoreDescription {readonly botId:string;readonly botEpoch:number;readonly authorityEpoch:number;readonly configVersion:string;readonly mainSessionId:string;readonly sessionId:string;readonly cold:boolean;readonly recovery:boolean;readonly taskId?:string;readonly taskEpoch?:number;readonly taskRevision?:number;readonly originalCreationIntent:Readonly<{binding:CreationIntent;operationId:string;nonce:string}>}
export interface OwnedBotLifecycleHistoryProof {readonly journal:unknown;readonly selectors:readonly Readonly<{binding:Readonly<Record<string,unknown>>;selector:unknown}>[]}
export type OwnedBotHistoryPurpose='archive-restore'|'active-recovery';
export interface OwnedBotLifecycleRestoreOptions {readonly purpose:OwnedBotHistoryPurpose;readonly grant:OwnedBotLifecycleRestoreGrant;readonly role:'main'|'work';readonly mainSessionId:string;readonly originalCreationIntent:Readonly<{binding:CreationIntent;operationId:string;nonce:string}>;readonly plannedBinding?:Readonly<Record<string,unknown>>;readonly historyProof?:OwnedBotLifecycleHistoryProof;readonly parentSource?:object;readonly parentGeneration?:object;readonly parentBinding?:Readonly<Record<string,unknown>>}
export interface OwnedBotOriginalHistoryOptions {readonly purpose:OwnedBotHistoryPurpose;readonly role:'main'|'work';readonly originalCreationIntent:Readonly<{binding:CreationIntent;operationId:string;nonce:string}>}
export interface OwnedBotOriginalHistory {readonly journal:unknown;readonly selectHistory:(binding:Readonly<Record<string,unknown>>)=>Promise<unknown>}
export interface OwnedBotRecoveryReceipt {readonly botId:string;readonly botEpoch:number;readonly lifecycle:'active';readonly state:'accepted';readonly nativeRecoveryVerified:true}
export interface OwnedBotLifecycleOptions {readonly botId:string;readonly botEpoch:number;readonly authorityEpoch:number;readonly isOwnerCurrent:()=>boolean;readonly mainCreationPort?:OwnedGenerationCreationPort;readonly mainCreationIntent?:CreationIntent;readonly readOriginalCreation?:(intent:CreationIntent)=>Readonly<{binding:CreationIntent;operationId:string;nonce:string}>|Promise<Readonly<{binding:CreationIntent;operationId:string;nonce:string}>>;readonly inspectOriginalHistory?:(intent:CreationIntent,options:OwnedBotOriginalHistoryOptions)=>Promise<OwnedBotOriginalHistory>;readonly inspectArchivedHistory?:(intent:CreationIntent,options:Omit<OwnedBotOriginalHistoryOptions,'purpose'>)=>Promise<OwnedBotOriginalHistory>;readonly releaseArchivedSessions?:(grant:OwnedBotLifecycleRestoreGrant)=>Promise<void>;readonly prepareRestore?:(intent:CreationIntent,options:OwnedBotLifecycleRestoreOptions)=>Promise<Readonly<{port:OwnedGenerationCreationPort;delegateTool?:ToolDefinition;bindDelegate?:()=>void}>>}
export interface OwnedBotLifecyclePort {readonly query:()=>OwnedBotLifecycleQuery;readonly archiveOriginalBot:(request:OwnedBotLifecycleRequest)=>Promise<OwnedBotLifecycleReceipt>;readonly restoreOriginalBot:(request:OwnedBotLifecycleRequest)=>Promise<OwnedBotLifecycleReceipt>;readonly inspectOriginalBotLifecycle:(request:Omit<OwnedBotLifecycleRequest,'botEpoch'>)=>Promise<OwnedBotLifecycleReceipt>;readonly recoverOriginalBot:()=>Promise<OwnedBotRecoveryReceipt>}
export declare function isOwnedBotLifecycleRestoreGrant(value:unknown,host:Host,caller:object,intent:CreationIntent):value is OwnedBotLifecycleRestoreGrant;
export declare function describeOwnedBotLifecycleRestore(grant:OwnedBotLifecycleRestoreGrant,host:Host,caller:object,intent:CreationIntent):OwnedBotLifecycleRestoreDescription;
export declare function isOwnedBotLifecycleRestoreGrantForPort(value:unknown,adapter:DshAdapter,port:OwnedGenerationCreationPort,intent:CreationIntent):boolean;
