/** Actual rc.2 Loader module. Owner controls are private RPC bindings, independent of read leases. */
window.__ModuleLoader__.load({id:'dsh-bot',factory:require=>{
 const{createElement:h,useState,useEffect,useRef}=require('react');const namespace='dsh.bot',panelId='dsh-bot',cancelledRead=Symbol('dsh-bot/cancelled');
 const en={nav:'Bots',title:'Bots',registration:'Client plugin mounted',connection:'Host connection',unstarted:'Not established',connecting:'Connecting',connected:'Connected',reconnecting:'Reconnecting',disconnected:'Disconnected',offline:'Offline',failed:'Failed',stopped:'Stopped',records:'Bots and tasks',bots:'Bots',tasks:'Tasks',empty:'No records in this authorized snapshot',waiting:'Waiting for a Host connection',loading:'Reading status',not_configured:'Read source not configured',access_denied:'This connection is not authorized to read these records',read_failed:'Status could not be read',selected_bot:'Selected Bot',main_goal:'Main goal',goal_hint:'Send a short text goal to the selected Bot. Its main model chooses whether to delegate work.',send:'Send goal',owner_unavailable:'Owner controls unavailable',reply:'Observed main reply',refresh:'Refresh replies and work',receipt:'Original message receipt',unknown:'Unknown — check the original receipt',sending:'Sending',durably_queued:'Original message durably queued',accepted:'Stop request accepted',reconcile:'Check original receipt',contact_stop:'Request contact stop',work:'Work Sessions',work_stop:'Request work stop',work_detail:'Work details',completion:'Completion condition',result:'Observed work result',state:'State',held:'Held work slots',held_hint:'Observed replies and accepted stop requests do not release held work slots or prove generation settlement.',planned:'Planned',user_bots:'User Bots',groups:'Group chat',autotasks:'Automatic tasks',scope:'Send controls require a current owner binding. A read lease alone grants no write access.'};
 const zh={...en,nav:'Bots',title:'Bots',connection:'宿主连接',connected:'已连接',disconnected:'已断开',waiting:'等待宿主连接',loading:'正在读取状态',selected_bot:'所选 Bot',main_goal:'主目标',goal_hint:'发送简短文本目标，由主模型决定是否分派工作。',send:'发送目标',owner_unavailable:'Owner 操作绑定不可用',reply:'已观察到的主回复',refresh:'刷新回复与工作',receipt:'原消息回执',unknown:'未知，请查询原回执',sending:'发送中',durably_queued:'原消息已持久入队',accepted:'停止请求已接受',reconcile:'查询原回执',contact_stop:'请求停止主会话',work:'工作 Sessions',work_stop:'请求停止工作',work_detail:'工作详情',completion:'完成条件',result:'已观察到的工作结果',state:'状态',held:'保留的工作槽位',held_hint:'回复和已接受的停止请求不代表原生代次已结束，也不会释放槽位。',planned:'规划中',user_bots:'User Bots',groups:'群聊',autotasks:'自动任务'};
 Object.assign(en,{create_bot:'Create Bot',bot_name:'Bot name',create_original:'Original create receipt',create_unknown:'Create outcome unknown — check the original receipt',create_created:'Bot and main Session created',model_disabled:'Model requests are disabled for this launch. Restart with --enable-model-requests to send goals.'});
 Object.assign(zh,{create_bot:'创建 Bot',bot_name:'Bot 名称',create_original:'原创建回执',create_unknown:'创建结果未知，请查询原回执',create_created:'Bot 与主 Session 已创建',model_disabled:'本次启动未启用模型请求。重启时添加 --enable-model-requests 才能发送目标。'});
 let operationStorage,operationLocks;try{operationStorage=globalThis.localStorage;operationLocks=globalThis.navigator?.locks;}catch{}
 const string=(v,max=200)=>typeof v==='string'&&v.length>0&&v.length<=max;
  function readView(result) {
   const value=result?.ok===true?result.value:undefined;
   if(value?.version!==1)return {status:'read_failed'};
   if(['not_configured','access_denied','read_failed'].includes(value.status))return {status:value.status};
   const string=(v,max)=>typeof v==='string' && v.length>0 && v.length<=max;
   const revision=v=>Number.isSafeInteger(v) && v>=1;
   if(value.status!=='ready' || !Array.isArray(value.bot) || !Array.isArray(value.task)
     || value.bot.length>500 || value.task.length>500)return {status:'read_failed'};
   if(!value.bot.every(b=>b && string(b.botId,200) && string(b.name,100) && string(b.lifecycle,64)
     && string(b.readiness,64) && revision(b.epoch) && revision(b.revision))
     || !value.task.every(q=>q && string(q.taskId,200) && string(q.ownerBotId,200) && string(q.title,500)
     && string(q.responsibility,64) && string(q.stop?.state,64) && revision(q.epoch) && revision(q.revision)))return {status:'read_failed'};
   return {status:'ready',bot:value.bot,task:value.task};
  }

 function ownerView(result,botId){const v=result?.ok===true?result.value:null;if(v?.version!==1||v.status!=='ready'||v.botId!==botId||!string(v.contact?.sessionId)||!['idle','running'].includes(v.contact.status)||!Array.isArray(v.work)||v.work.length>500||!Number.isSafeInteger(v.held)||v.held<0||v.limit!==15||v.preciseNativeSettlementVerified!==false)return{status:'owner_unavailable'};if(v.contact.reply!==null&&v.contact.reply!==undefined){const r=v.contact.reply;if(!string(r.messageId)||!string(r.text,4096)||!Number.isSafeInteger(r.turn)||r.turn<1||!string(r.inputMessageId)||!string(r.inputKind,64))return{status:'owner_unavailable'};}if(!v.work.every(w=>string(w.taskId)&&string(w.task_id)&&string(w.sessionId)&&Number.isSafeInteger(w.generation)&&w.generation>0&&string(w.goal,500)&&string(w.completion_condition,4000)&&string(w.state,64)&&typeof w.held==='boolean'&&['none','accepted'].includes(w.stop?.state)&&w.preciseNativeSettlementVerified===false&&(!w.result||string(w.result.text,4096)&&string(w.result.responseMessageId)&&Number.isSafeInteger(w.result.turn)&&w.result.turn>0)))return{status:'owner_unavailable'};return v;}
 function storageKey(botId){return 'dsh-bot/original-operations/'+botId;}
 function cleanOperation(value,botId,kind){if(!value||value.botId!==botId||value.kind!==kind||!string(value.operationId)||!string(value.nonce)||!(kind==='contact'?['unknown','durably-queued']:['unknown','accepted']).includes(value.state)||value.messageId!==undefined&&!string(value.messageId))throw cancelledRead;return{botId,kind,operationId:value.operationId,nonce:value.nonce,state:value.state,...(value.messageId?{messageId:value.messageId}:{})};}
 function loadOperations(botId){if(!operationStorage||typeof operationStorage.getItem!=='function'||typeof operationStorage.setItem!=='function'||typeof operationLocks?.request!=='function')throw cancelledRead;const raw=operationStorage.getItem(storageKey(botId));if(raw===null)return{version:1,botId,contact:null,stops:{}};if(raw.length>32768)throw cancelledRead;const value=JSON.parse(raw);if(value?.version!==1||value.botId!==botId||!value.stops||typeof value.stops!=='object'||Array.isArray(value.stops)||Object.keys(value.stops).length>64)throw cancelledRead;const stops={};for(const[key,v]of Object.entries(value.stops)){if(!string(key)||['__proto__','constructor','prototype'].includes(key))throw cancelledRead;stops[key]=cleanOperation(v,botId,'stop');}return{version:1,botId,contact:value.contact===null?null:cleanOperation(value.contact,botId,'contact'),stops};}
 function saveOperations(value){operationStorage.setItem(storageKey(value.botId),JSON.stringify(value));}
 function receiptView(result,operation){const r=result?.ok===true?result.value:null;if(r?.version!==1||r.operationId!==operation.operationId||r.nonce!==operation.nonce||r.botId!==operation.botId||!(operation.kind==='contact'?['unknown','durably-queued']:['unknown','accepted']).includes(r.state)||r.preciseNativeSettlementVerified!==false)return{...operation,state:'unknown'};return{...operation,...(r.messageId===null||r.messageId===undefined?{}:{messageId:r.messageId}),state:r.state};}
 function guiView(result){const v=result?.ok===true?result.value:null;if(v?.version!==1||v.status!=='ready'||!string(v.ledgerId)||!(v.selectedBotId===null||string(v.selectedBotId))||!(v.contactSessionId===null||string(v.contactSessionId))||typeof v.modelRequestsEnabled!=='boolean'||v.nativeGenerationTerminalSupported!==false)return{status:'owner_unavailable'};return v;}
 const createStorageKey=ledgerId=>'dsh-bot/gui-create/'+ledgerId;
 function loadCreate(ledgerId){if(!operationStorage||typeof operationLocks?.request!=='function')throw cancelledRead;const raw=operationStorage.getItem(createStorageKey(ledgerId));if(raw===null)return null;if(raw.length>4096)throw cancelledRead;const op=JSON.parse(raw);if(op?.version!==1||op.ledgerId!==ledgerId||!string(op.operationId,128)||!string(op.nonce,128)||!['unknown','created'].includes(op.state)||op.botId!==undefined&&!string(op.botId)||op.sessionId!==undefined&&!string(op.sessionId))throw cancelledRead;return op;}
 function createReceipt(result,op){const r=result?.ok===true?result.value:null;return r?.version===1&&r.operationId===op.operationId&&r.nonce===op.nonce&&r.preciseNativeSettlementVerified===false&&r.state==='created'&&string(r.botId)&&string(r.sessionId)?{...op,state:'created',botId:r.botId,sessionId:r.sessionId}:{...op,state:'unknown'};}
 function BotPanel({t,useConnection,useGeneration,read,ownerCall,guiCall}){
  const state=useConnection(v=>v),generation=useGeneration(v=>v)?.id,connected=state==='connected'&&Number.isSafeInteger(generation);
  const[view,setView]=useState({status:'waiting'}),[selectedId,setSelectedId]=useState(''),[owned,setOwned]=useState({status:'owner_unavailable'}),[goal,setGoal]=useState(''),[receipt,setReceipt]=useState(null),[stopReceipts,setStopReceipts]=useState({}),[refresh,setRefresh]=useState(0),[identityReady,setIdentityReady]=useState(false);
  const memory=useRef({controllers:new Set(),busy:false,epoch:null,operation:null,live:null});memory.current.live={connected,generation,botId:selectedId};
  const[gui,setGui]=useState({status:'owner_unavailable'}),[botName,setBotName]=useState('My Bot'),[createOp,setCreateOp]=useState(null),[creating,setCreating]=useState(false),[catalogRevision,setCatalogRevision]=useState(0),[guiRefresh,setGuiRefresh]=useState(0);
  useEffect(()=>{memory.current.epoch=generation;if(!connected){setView({status:'waiting'});return;}const controller=new AbortController();setView({status:'loading',generation});void read(controller.signal).then(result=>{if(controller.signal.aborted)return;const next=readView(result);setView({...next,generation});if(next.status==='ready')setSelectedId(id=>next.bot.some(b=>b.botId===id)?id:next.bot[0]?.botId??'');},()=>{if(!controller.signal.aborted)setView({status:'read_failed',generation});});return()=>{controller.abort();for(const c of memory.current.controllers)c.abort();memory.current.controllers.clear();memory.current.busy=false;const op=memory.current.operation;if(op?.state==='sending'){const unknown={...op,state:'unknown'};memory.current.operation=unknown;setReceipt(unknown);}};},[state,generation,read,catalogRevision]);
  useEffect(()=>{if(!guiCall||!connected){setGui({status:'owner_unavailable'});return;}const controller=new AbortController();void guiCall('bootstrap',{},controller.signal).then(result=>{if(controller.signal.aborted)return;const next=guiView(result);setGui({...next,generation});if(next.status==='ready'){try{setCreateOp(loadCreate(next.ledgerId));}catch{setGui({status:'owner_unavailable'});}setCatalogRevision(n=>n+1);}},()=>{if(!controller.signal.aborted)setGui({status:'owner_unavailable'});});return()=>controller.abort();},[state,generation,guiCall,guiRefresh]);
  useEffect(()=>{if(!connected||!selectedId){setOwned({status:'owner_unavailable'});return;}const controller=new AbortController();setOwned({status:'loading',generation,botId:selectedId});void ownerCall('selectedView',selectedId,{},controller.signal).then(result=>{if(!controller.signal.aborted)setOwned({...ownerView(result,selectedId),generation});},()=>{if(!controller.signal.aborted)setOwned({status:'owner_unavailable',generation,botId:selectedId});});return()=>controller.abort();},[state,generation,selectedId,refresh,ownerCall]);
  useEffect(()=>{try{if(!selectedId){setIdentityReady(false);return;}const value=loadOperations(selectedId);memory.current.operation=value.contact;setReceipt(value.contact);setStopReceipts(value.stops);setIdentityReady(true);}catch{setIdentityReady(false);setReceipt(null);setStopReceipts({});}},[selectedId,generation]);
  useEffect(()=>()=>{for(const c of memory.current.controllers)c.abort();memory.current.controllers.clear();},[]);
  const visible=connected&&view.generation===generation?view:{status:connected?'loading':'waiting'},current=connected&&owned.generation===generation&&owned.botId===selectedId&&owned.status==='ready',operationCurrent=receipt?.botId===selectedId,contactStopReceipt=stopReceipts['contact/'+receipt?.operationId];
  async function invoke(endpoint,payload,operation){const controller=new AbortController(),epoch=generation;memory.current.controllers.add(controller);try{const result=await ownerCall(endpoint,operation.botId,payload,controller.signal);if(controller.signal.aborted||memory.current.epoch!==epoch||memory.current.live.botId!==operation.botId||!memory.current.live.connected)return{...operation,state:'unknown'};return receiptView(result,operation);}catch{return{...operation,state:'unknown'};}finally{memory.current.controllers.delete(controller);}}
  const ids=(kind,botId)=>({operationId:globalThis.crypto.randomUUID(),nonce:globalThis.crypto.randomUUID(),botId,kind,state:'unknown'});
  async function storedAction(key,kind,endpoint,makePayload){if(!current||!identityReady||memory.current.busy)return;const controller=new AbortController(),botId=selectedId,epoch=generation;memory.current.controllers.add(controller);memory.current.busy=true;try{await operationLocks.request(storageKey(botId),{mode:'exclusive',signal:controller.signal},async()=>{const live=()=>!controller.signal.aborted&&memory.current.live.connected&&memory.current.live.generation===epoch&&memory.current.live.botId===botId;if(!live())return;const value=loadOperations(botId),previous=kind==='contact'?value.contact:value.stops[key],lookup=previous&&(kind==='stop'||previous.state==='unknown'||endpoint==='inspectContactReceipt');if(endpoint==='inspectContactReceipt'&&!previous)return;const op=lookup?previous:ids(kind,botId);if(kind==='contact'){value.contact=op;memory.current.operation=op;setReceipt({...op,state:lookup?op.state:'sending'});}else{if(!previous&&Object.keys(value.stops).length>=64)return;value.stops[key]=op;setStopReceipts({...value.stops,[key]:{...op,state:lookup?op.state:'sending'}});}saveOperations(value);if(!live())return;const next=await invoke(lookup?'inspectContactReceipt':endpoint,lookup?{operationId:op.operationId,nonce:op.nonce}:makePayload(op,value),op);const latest=loadOperations(botId),retained=kind==='contact'?latest.contact:latest.stops[key];if(retained?.operationId!==op.operationId||retained.nonce!==op.nonce)return;const safe=cleanOperation({...next,state:live()?next.state:'unknown'},botId,kind);if(kind==='contact')latest.contact=safe;else latest.stops[key]=safe;saveOperations(latest);if(!live())return;if(kind==='contact'){memory.current.operation=safe;setReceipt(safe);if(safe.state==='durably-queued'&&endpoint==='sendContactText')setGoal('');}else setStopReceipts(latest.stops);setRefresh(n=>n+1);});}catch{try{const value=loadOperations(botId);if(memory.current.live.botId===botId){memory.current.operation=value.contact;setReceipt(value.contact);setStopReceipts(value.stops);}}catch{setIdentityReady(false);}}finally{memory.current.controllers.delete(controller);memory.current.busy=false;}}
  async function submit(event){event.preventDefault();if(!goal.trim()||goal.length>500)return;const text=goal;await storedAction('contact','contact','sendContactText',op=>({operationId:op.operationId,nonce:op.nonce,text}));}
  async function reconcile(){await storedAction('contact','contact','inspectContactReceipt',()=>({}));}
  const workStopKey=w=>'work/'+w.taskId+'/'+w.generation;
  async function stopWork(w){await storedAction(workStopKey(w),'stop','requestWorkStop',op=>({operationId:op.operationId,nonce:op.nonce,taskId:w.taskId,generation:w.generation}));}
  async function stopContact(){if(!operationCurrent||!receipt.messageId)return;const target=receipt.operationId;await storedAction('contact/'+target,'stop','requestContactStop',(op,value)=>{if(value.contact?.operationId!==target)throw cancelledRead;return{operationId:op.operationId,nonce:op.nonce,contactOperationId:target};});}
  const guiCurrent=!!guiCall&&connected&&gui.status==='ready'&&gui.generation===generation;
  async function createBot(event,inspect=false){event?.preventDefault?.();if(!guiCurrent||creating||!inspect&&(!botName.trim()||botName.length>100||gui.selectedBotId))return;const controller=new AbortController(),ledgerId=gui.ledgerId,epoch=generation;memory.current.controllers.add(controller);setCreating(true);try{await operationLocks.request(createStorageKey(ledgerId),{mode:'exclusive',signal:controller.signal},async()=>{const live=()=>!controller.signal.aborted&&memory.current.live.connected&&memory.current.live.generation===epoch;if(!live())return;let op=loadCreate(ledgerId);if(inspect&&!op)return;if(!op)op={version:1,ledgerId,operationId:globalThis.crypto.randomUUID(),nonce:globalThis.crypto.randomUUID(),state:'unknown'};const lookup=inspect||loadCreate(ledgerId)!==null;operationStorage.setItem(createStorageKey(ledgerId),JSON.stringify(op));setCreateOp(op);let next;try{const result=await guiCall(lookup?'reconcileCreate':'createBot',lookup?{operationId:op.operationId,nonce:op.nonce}:{operationId:op.operationId,nonce:op.nonce,name:botName},controller.signal);next=live()?createReceipt(result,op):{...op,state:'unknown'};}catch{next={...op,state:'unknown'};}const retained=loadCreate(ledgerId);if(retained.operationId!==op.operationId||retained.nonce!==op.nonce)return;operationStorage.setItem(createStorageKey(ledgerId),JSON.stringify(next));if(live()){setCreateOp(next);setGuiRefresh(n=>n+1);}});}catch{setGui({status:'owner_unavailable'});}finally{memory.current.controllers.delete(controller);setCreating(false);}}
  const writeBlocked=!current||!identityReady||memory.current.busy||receipt?.state==='unknown'||!!guiCall&&(!guiCurrent||!gui.modelRequestsEnabled),label=s=>t(s==='durably-queued'?'durably_queued':s);
  const rows=(key,items,kind)=>h('div',null,h('h3',null,t(key)),items.length?h('ul',null,...items.map(item=>h('li',{key:kind==='bot'?item.botId:item.taskId},kind==='bot'?`${item.name} · ${item.lifecycle} · ${item.readiness}`:`${item.title} · ${item.responsibility} · ${item.stop.state}`))):h('p',null,t('empty')));
  return h('section',{'data-dsh-bot-panel':'','aria-label':t('title'),style:{padding:'28px',maxWidth:'1000px',margin:'0 auto',lineHeight:1.6}},
   h('h1',null,t('title')),h('p',{'data-dsh-bot-registration':''},t('registration')),h('p',{'data-dsh-bot-connection':''},t(Object.hasOwn(en,state)?state:'unstarted')),
   guiCurrent&&!gui.selectedBotId?h('form',{'data-dsh-bot-create-form':'',onSubmit:createBot},h('label',null,t('bot_name'),h('input',{'data-dsh-bot-create-name':'',value:botName,maxLength:100,disabled:creating,onChange:e=>setBotName(e.target.value)})),h('button',{'data-dsh-bot-create':'',type:'submit',disabled:creating||!botName.trim()||createOp?.state==='unknown'},t('create_bot'))):null,
   guiCurrent&&createOp?h('div',{'data-dsh-bot-create-receipt':createOp.state,role:'status'},h('p',null,t(createOp.state==='created'?'create_created':'create_unknown')),createOp.state==='unknown'?h('button',{'data-dsh-bot-create-reconcile':'',type:'button',disabled:creating,onClick:()=>createBot(null,true)},t('reconcile')):null):null,
   guiCurrent&&!gui.modelRequestsEnabled?h('p',{'data-dsh-bot-model-disabled':''},t('model_disabled')):null,
   visible.status==='ready'?h('div',{'data-dsh-bot-read-status':'ready'},rows('bots',visible.bot,'bot'),rows('tasks',visible.task,'task')):h('p',{'data-dsh-bot-read-status':visible.status,role:'status'},t(visible.status)),
   h('label',null,t('selected_bot'),h('select',{'data-dsh-bot-select':'',value:selectedId,disabled:!connected,onChange:e=>{for(const c of memory.current.controllers)c.abort();setSelectedId(e.target.value);}},...(visible.bot??[]).map(b=>h('option',{key:b.botId,value:b.botId},b.name)))),
   h('h2',null,t('main_goal')),h('p',null,t('goal_hint')),h('form',{'data-dsh-bot-goal-form':'',onSubmit:submit},h('textarea',{'data-dsh-bot-goal':'','aria-label':t('main_goal'),value:goal,maxLength:500,rows:3,disabled:writeBlocked,onChange:e=>setGoal(e.target.value),style:{width:'100%',boxSizing:'border-box'}}),h('button',{'data-dsh-bot-submit':'',type:'submit',disabled:writeBlocked||!goal.trim()},t('send'))),
   !current?h('p',{'data-dsh-bot-owner-status':owned.status},t('owner_unavailable')):h('button',{type:'button',onClick:()=>setRefresh(n=>n+1)},t('refresh')),
   operationCurrent?h('div',{'data-dsh-bot-receipt':receipt.state,role:'status'},h('h3',null,t('receipt')),h('p',null,label(receipt.state)),h('code',null,receipt.messageId??receipt.operationId),h('button',{'data-dsh-bot-reconcile':'',type:'button',disabled:!current||!identityReady||memory.current.busy,onClick:reconcile},t('reconcile')),h('button',{'data-dsh-bot-contact-stop':'',type:'button',disabled:!current||!identityReady||(contactStopReceipt?.state!=='unknown'&&(owned.contact?.status!=='running'||!receipt.messageId))||contactStopReceipt?.state==='sending'||contactStopReceipt?.state==='accepted',onClick:stopContact},contactStopReceipt?label(contactStopReceipt.state):t('contact_stop'))):null,
   current&&owned.contact.reply?h('article',{'data-dsh-bot-main-reply':owned.contact.reply.messageId},h('h3',null,t('reply')),h('p',null,owned.contact.reply.text),h('small',null,`Turn ${owned.contact.reply.turn} · ${owned.contact.reply.messageId} · ${owned.contact.reply.inputKind} ${owned.contact.reply.inputMessageId}`)):null,
   h('h2',null,t('work')),current?h('div',{'data-dsh-bot-work-list':''},h('p',null,`${t('held')}: ${owned.held}/${owned.limit}`),...(owned.work.length?owned.work.map(w=>h('details',{'data-dsh-bot-work-detail':w.taskId,key:w.taskId},h('summary',null,`${w.task_id} · ${w.state} · ${w.stop.state}`),h('p',null,w.goal),h('p',null,`${t('completion')}: ${w.completion_condition}`),h('p',null,`${t('state')}: ${w.state} · held ${w.held} · generation ${w.generation}`),h('small',null,w.sessionId),w.result?h('article',{'data-dsh-bot-work-result':w.result.responseMessageId},h('h4',null,t('result')),h('p',null,w.result.text),h('small',null,`Turn ${w.result.turn} · ${w.result.responseMessageId}`)):null,h('button',{'data-dsh-bot-work-stop':w.taskId,type:'button',disabled:!current||!identityReady||(w.stop.state==='accepted'&&stopReceipts[workStopKey(w)]?.state!=='unknown')||stopReceipts[workStopKey(w)]?.state==='sending'||stopReceipts[workStopKey(w)]?.state==='accepted',onClick:()=>stopWork(w)},stopReceipts[workStopKey(w)]?.state==='unknown'?t('reconcile'):t('work_stop')),stopReceipts[workStopKey(w)]?h('p',{role:'status'},label(stopReceipts[workStopKey(w)].state)):null)): [h('p',{key:'empty'},t('empty'))])):h('p',null,t('owner_unavailable')),
   h('p',null,t('held_hint')),h('p',null,t('scope')),h('hr'),...['user_bots','groups','autotasks'].map(key=>h('p',{key},`${t(key)} · ${t('planned')}`)));
 }
  function BotIcon({ size }) {
   return h('svg', { width: size, height: size, viewBox: '0 0 24 24', fill: 'none',
    stroke: 'currentColor', strokeWidth: 1.7, 'aria-hidden': true },
    h('rect', { x: 4, y: 6, width: 16, height: 14, rx: 4 }),
    h('path', { d: 'M12 2v4M8 15h8M8 10v2M16 10v2' }));
  }

 function apply(ctx,config={}){let closed=false;const pending=new Set();ctx.effect(()=>()=>{closed=true;for(const controller of pending)controller.abort();pending.clear();},'dsh-bot: RPC calls');
  async function rpc(channel,endpoint,payload,signal){if(closed||signal.aborted)throw cancelledRead;const controller=new AbortController(),abort=()=>controller.abort();pending.add(controller);signal.addEventListener('abort',abort,{once:true});try{const result=await ctx.connection.rpc.call(channel,endpoint,payload,controller.signal);if(closed||controller.signal.aborted)throw cancelledRead;return result;}finally{signal.removeEventListener('abort',abort);pending.delete(controller);}}
  const read=signal=>rpc('/dsh-bot','snapshot',{},signal),ownerCall=(endpoint,botId,payload,signal)=>rpc('/dsh-bot-owner',endpoint,{command:endpoint,botId,payload},signal);
  const guiCall=config.guiOwner===true?(endpoint,payload,signal)=>rpc('/dsh-bot-gui',endpoint,payload,signal):undefined;
  if(guiCall){
   const absent=Object.freeze({key:undefined,hooks:Object.freeze({session:undefined}),keyedHooks:Object.freeze({projection:undefined}),props:Object.freeze({sessionId:undefined})});
   const source=Object.freeze({getSnapshot:()=>absent,subscribe:()=>()=>{}});
   ctx.slots.installScope('session',{current:source,bindingSource:target=>{if(target!==undefined)throw Error('dsh-bot: ordinary Session UI unavailable');return source;},renderArea:(_binding,props)=>props.empty?.()??null});
  }
  ctx.effect(()=>ctx.locale.register(namespace,{en,zh}),'dsh-bot: dictionaries');const t=ctx.locale.bind(namespace);
  ctx.slots.inject('main',()=>{const remove=ctx.slots.register({name:'main',key:panelId,locale:namespace,inject:()=>({hooks:{connection:ctx.connection.state,generation:ctx.connection.generation},read,ownerCall,guiCall})},BotPanel);if(guiCall)ctx.layout.selectPanel(panelId);return remove;});
  ctx.slots.inject('sidebar.panellist',()=>ctx.slots.register({name:'sidebar.panellist',id:panelId,order:70,label:()=>t('nav'),locale:namespace},BotIcon));
 }
 return{name:'dsh-bot-client',inject:['slots','layout','locale','connection'],apply};
}});
