import { prepareCommand } from './command.mjs';
const token=document.querySelector('meta[name=dsh-token]').content,content=document.querySelector('#content'),receipt=document.querySelector('#receipt'),store=localStorage;
let state,view='management',busy=false;
const node=(tag,value,className)=>{const n=document.createElement(tag);if(value!==undefined)n.textContent=value;if(className)n.className=className;return n;};
const panel=(title,hint)=>{const n=node('section',undefined,'panel');n.append(node('h2',title));if(hint)n.append(node('p',hint,'hint'));content.append(n);return n;};
const json=value=>JSON.stringify(value,null,2);
function pending(){const p=store.getItem('dsh-bot-pending');document.querySelector('#pending').textContent=p?`待查回：${JSON.parse(p).envelope.operationId}`:'没有待查回操作';}
async function api(path,body){const res=await fetch(path,{method:body?'POST':'GET',headers:{'x-dsh-token':token,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await res.json();if(!res.ok){const e=Error(`${data.code}: ${data.message??'请求未完成'}`);e.data=data;throw e;}return data;}
async function refresh(){state=await api('/api/snapshot');render();pending();}
async function send(command,payload,expectedRevision=null,expectedEpochs={}){if(busy)return;busy=true;try{const body=await prepareCommand(store,{command,payload,expectedRevision,expectedEpochs});pending();const result=await api('/api/command',body);if(result.operationId!==body.envelope.operationId)throw Error('回执身份不同，保留原操作查回');receipt.textContent=json(result);store.removeItem('dsh-bot-pending');await refresh();}catch(e){receipt.textContent=e.message;pending();}finally{busy=false;}}
function field(form,name,label,{options,type='text',multiple=false,value=''}={}){const wrap=node('label',label),el=node(options?'select':type==='textarea'?'textarea':'input');el.name=name;if(el.tagName==='INPUT')el.type=type;if(options){el.multiple=multiple;for(const [id,label] of options){const o=node('option',label);o.value=id;el.append(o);}}else el.value=value;wrap.append(el);form.append(wrap);return el;}
function form(parent,title,build,submit){const f=node('form');f.append(node('h2',title));build(f);const b=node('button','保存控制记录');b.type='submit';f.append(b);f.addEventListener('submit',e=>{e.preventDefault();submit(f,new FormData(f));});parent.append(f);return f;}
const botOptions=()=>state.bot.map(b=>[b.botId,`${b.name} · ${b.lifecycle}`]);
const groupOptions=()=>state.group.map(g=>[g.groupId,g.name]);
function records(parent,items){if(!items.length)parent.append(node('p','尚无记录'));for(const item of items){const box=node('details');box.append(node('summary',`${item.name??item.title??item.topic??item.taskId??item.planId??item.botId} · ${item.state??item.responsibility??item.readiness??item.stage??item.lifecycle??''}`),node('pre',json(item)));parent.append(box);}}
function render(){content.replaceChildren();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 if(view==='management'){const p=panel('统一管理','本地持久对象；原生普通会话、子任务与归档的完整目录尚未接通。');records(p,[...state.bot,...state.task]);const c=panel('宿主能力','所有原生能力门当前关闭。冷读 adapter 也不声称归档或子任务覆盖完整。');c.append(node('pre',json(state.capabilities)));const a=panel('可恢复归档','仅归档 Bot 控制记录，原生 stop / archive / restore 仍 unsupported。');form(a,'归档 / 恢复',f=>{field(f,'id','Bot',{options:botOptions()});field(f,'action','操作',{options:[['archive','归档记录'],['restore','恢复记录']]});},(_,d)=>{const b=state.bot.find(b=>b.botId===d.get('id'));if(b)send(d.get('action'),{kind:'bot',id:b.botId},b.revision,{bot:b.epoch});});}
 if(view==='bots'){const p=panel('Bots','不同 Bot 保存独立模型路由版本；当前无真实模型请求或自然语言联络。');records(p,state.bot);form(p,'创建 Bot',f=>{field(f,'name','名字');field(f,'provider','Provider 标签');field(f,'model','模型标签');field(f,'reasoning','Reasoning 标签（可空）');},(_,d)=>send('createBot',{name:d.get('name'),config:{contact:{provider:d.get('provider'),model:d.get('model'),reasoning:d.get('reasoning')||null}}}));const c=panel('设置','会话模式等待需求澄清与 live catalog；计划和权限预设不会猜默认。');const mode=node('select');mode.disabled=true;mode.append(node('option','会话模式：unsupported / 待确认'));c.append(mode);form(c,'版本化模型与自主策略',f=>{field(f,'id','Bot',{options:botOptions()});field(f,'provider','新的 Provider 标签');field(f,'model','新的模型标签');field(f,'reasoning','Reasoning（可空）');field(f,'enabled','自主策略（仅记录）',{options:[['false','关闭'],['true','开启策略记录；原生执行仍阻断']]});field(f,'maxSteps','最多步骤',{type:'number',value:20});field(f,'maxRetries','最多重试',{type:'number',value:0});},(_,d)=>{const b=state.bot.find(b=>b.botId===d.get('id'));if(b)send('updateBotConfig',{botId:b.botId,config:{contact:{provider:d.get('provider'),model:d.get('model'),reasoning:d.get('reasoning')||null},autonomy:{enabled:d.get('enabled')==='true',maxSteps:Number(d.get('maxSteps')),maxRetries:Number(d.get('maxRetries')),observationDeadline:null,reportMilestonesOnly:true}}},b.revision,{bot:b.epoch});});const t=node('textarea');t.disabled=true;t.placeholder='真实自然语言联络等待独立原生 contact turn 和交互容量接口。';c.append(t);}
 if(view==='groups'){const p=panel('内部群','未指定接收者时只记录给协调者的 delivery；@ 文本不解析为路由。所有 delivery 当前 blocked_native。');records(p,state.group);form(p,'创建内部群',f=>{field(f,'name','群名');field(f,'namespace','资料命名空间');field(f,'members','成员（多选）',{options:botOptions(),multiple:true});field(f,'coordinator','协调者',{options:botOptions()});},(_,d)=>send('createGroup',{name:d.get('name'),namespace:d.get('namespace'),members:d.getAll('members'),coordinatorBotId:d.get('coordinator')}));form(p,'群消息',f=>{field(f,'groupId','群',{options:groupOptions()});field(f,'recipients','接收者（空选只到协调者）',{options:botOptions(),multiple:true});field(f,'content','内容',{type:'textarea'});},(_,d)=>{const g=state.group.find(g=>g.groupId===d.get('groupId'));if(g)send('sendMessage',{groupId:g.groupId,recipients:d.getAll('recipients'),content:d.get('content')},g.revision,{group:g.epoch});});const m=panel('会议记录','独立阶段公开视图隐藏所有意见；这里的意见由人类手动录入，不代表 Bot 独立思考。');records(m,state.meeting);form(m,'创建会议',f=>{field(f,'groupId','群',{options:groupOptions()});field(f,'topic','独立议题');field(f,'material','本群材料',{type:'textarea'});},(_,d)=>{const g=state.group.find(g=>g.groupId===d.get('groupId'));if(g)send('startMeeting',{groupId:g.groupId,topic:d.get('topic'),materials:d.get('material')?[{namespace:g.namespace,version:'human-record-v1',text:d.get('material')}]:[],maxOpinions:100},g.revision,{group:g.epoch});});form(m,'手动记录意见',f=>{field(f,'meetingId','会议',{options:state.meeting.map(m=>[m.meetingId,m.topic])});field(f,'botId','归属 Bot',{options:botOptions()});field(f,'content','人类录入的意见',{type:'textarea'});},(_,d)=>{const m=state.meeting.find(m=>m.meetingId===d.get('meetingId'));if(m)send('submitOpinion',{meetingId:m.meetingId,botId:d.get('botId'),content:d.get('content')},m.revision,{meeting:m.epoch});});for(const meeting of state.meeting.filter(m=>m.stage==='independent')){const b=node('button',`揭示：${meeting.topic}`);b.onclick=()=>send('revealOpinions',{meetingId:meeting.meetingId},meeting.revision,{meeting:meeting.epoch});m.append(b);}}
 if(view==='tasks'){const p=panel('任务','open / blocked / submitted / verified 是责任状态；原生 Attempt 执行与资源结算分别保留状态。');records(p,state.task);form(p,'创建目标',f=>{field(f,'owner','责任 Bot',{options:botOptions()});field(f,'title','目标');field(f,'namespace','资料命名空间');field(f,'acceptance','人类验收条件',{type:'textarea'});},(_,d)=>send('createTask',{ownerBotId:d.get('owner'),title:d.get('title'),scope:{namespace:d.get('namespace'),writeResources:[]},acceptance:d.get('acceptance')}));for(const task of state.task){const box=node('div',undefined,'actions');for(const [command,label] of [['startAttempt','记录准入检查'],['stopTask','请求停止（原生阻断）']]){const b=node('button',`${task.title} / ${label}`);b.onclick=()=>send(command,{taskId:task.taskId},task.revision,{task:task.epoch});box.append(b);}p.append(box);}const a=panel('Attempt 与持续计划','计划按事件推进控制记录，未知结果不重放；没有 cron 或自动模型调用。');records(a,[...state.attempt,...state.progress]);form(a,'拆解持久计划',f=>{field(f,'taskId','任务',{options:state.task.map(t=>[t.taskId,t.title])});field(f,'steps','每行：步骤标题 | 所需证据',{type:'textarea'});},(_,d)=>{const t=state.task.find(t=>t.taskId===d.get('taskId'));if(t)send('createProgressPlan',{taskId:t.taskId,steps:d.get('steps').split('\n').filter(x=>x.trim()).map(x=>{const [title,evidence]=x.split('|');return {title:title.trim(),evidence:evidence?.trim()||'人类检查'};})},t.revision,{task:t.epoch});});for(const plan of state.progress){const b=node('button',`继续记录 ${plan.planId.slice(0,8)}`);b.onclick=()=>send('advanceTask',{planId:plan.planId,eventId:crypto.randomUUID(),cursor:plan.eventCursor+1,trigger:'user'},plan.revision,{progress:plan.epoch});a.append(b);}const s=panel('人类验收','手动提交产物的 SHA256 和证据；仅通过准确验收版本与 digest 的人类检查才标 verified，不证明原生执行。');form(s,'提交 / 验收',f=>{field(f,'taskId','任务',{options:state.task.map(t=>[t.taskId,t.title])});field(f,'digest','产物 SHA256');field(f,'evidence','人工证据');field(f,'action','操作',{options:[['submitTask','手动提交'],['passed','验收通过'],['failed','验收失败'],['inconclusive','证据不足']]});},(_,d)=>{const t=state.task.find(t=>t.taskId===d.get('taskId'));if(!t)return;const action=d.get('action');send(action==='submitTask'?'submitTask':'acceptTask',action==='submitTask'?{taskId:t.taskId,artifactDigest:d.get('digest'),evidence:d.get('evidence'),expectedAuthorityEpoch:state.grant.find(g=>g.id==='root').epoch}:{taskId:t.taskId,artifactDigest:d.get('digest'),acceptanceVersion:t.acceptanceVersion,outcome:action},t.revision,{task:t.epoch});});}
}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});document.querySelector('#refresh').onclick=()=>refresh().catch(e=>receipt.textContent=e.message);
document.querySelector('#retry').onclick=async()=>{if(busy)return;const p=store.getItem('dsh-bot-pending');if(!p)return;const old=JSON.parse(p);await send(old.input.command,old.input.payload,old.input.expectedRevision,old.input.expectedEpochs);};
document.querySelector('#lookup').onclick=async()=>{const p=store.getItem('dsh-bot-pending');if(!p)return;try{const old=JSON.parse(p),r=await api(`/api/operation?id=${encodeURIComponent(old.envelope.operationId)}`);receipt.textContent=json(r);if(r.operationId===old.envelope.operationId){store.removeItem('dsh-bot-pending');await refresh();}}catch(e){receipt.textContent=`${e.message}\n保留原身份；查无记录不自动创建新 nonce。`;}};
refresh().catch(e=>receipt.textContent=e.message);
