import test from 'node:test';
import assert from 'node:assert/strict';
import {businessFixture} from './business-fixture.mjs';
const mod=await import('../../src/native/assistant.mjs').catch(()=>({}));
async function fixture(t,{at='2026-10-09T00:00:00Z',tasks,nativeOptions={}}={}) {
 assert.equal(typeof mod.AssistantController,'function','assistant controller is missing');
 const f=await businessFixture(t,nativeOptions), bot=await f.bot(), session=await f.sessions.create(f.human,{operationId:'contact',action:'session.create',input:{botId:bot.botId}});
 let now=Date.parse(at), active=new Map(),timerId=0;
 const clock={now:()=>now,setTimeout:(fn,ms)=>{const id=++timerId;active.set(id,{fn,ms});return id;},clearTimeout:id=>active.delete(id)};
 const assistant=new mod.AssistantController({...f,tasks:tasks??{},clock});f.beforeClose.push(()=>assistant.close());
 const schedule=(input={},operationId='schedule')=>assistant.createSchedule(f.human,{operationId,action:'schedule.create',input:{ownerBotId:bot.botId,kind:'reminder',message:'Remember',rule:{kind:'once',timezone:'UTC',date:'2026-10-09',time:'00:01'},...input}});
 return {...f,bot,session,assistant,clock,active,setNow(value){now=Date.parse(value)},schedule};
}
test('reminder is durable exactly once with original late identity and no native work',async t=>{
 const f=await fixture(t),s=await f.schedule();f.setNow('2026-10-09T00:05:00Z');await Promise.all([f.assistant.runDue(),f.assistant.runDue()]);
 const state=f.store.read();assert.equal(Object.keys(state.occurrences).length,1);assert.equal(Object.keys(state.notices).length,1);
 const n=Object.values(state.notices)[0];assert.equal(n.dueAt,s.nextDueAt);assert.equal(n.late,true);assert.equal(n.kind,'reminder');assert.equal(Object.keys(state.tasks).length,0);
 f.setNow('2026-10-08T00:00:00Z');await f.assistant.runDue();assert.equal(Object.keys(f.store.read().notices).length,1);
});
test('schedule edits require CAS and invalidate consent, pause closes gated admission',async t=>{
 const f=await fixture(t),s=await f.schedule();
 await assert.rejects(f.assistant.updateSchedule(f.human,{operationId:'bad',action:'schedule.update',input:{scheduleId:s.scheduleId,expectedVersion:0,message:'changed'}}),{code:'revision_conflict'});
 const updated=await f.assistant.updateSchedule(f.human,{operationId:'edit',action:'schedule.update',input:{scheduleId:s.scheduleId,expectedVersion:1,message:'changed'}});assert.equal(updated.consentVersion,2);
 await f.assistant.setScheduleState(f.human,{operationId:'pause',action:'schedule.state',input:{scheduleId:s.scheduleId,expectedVersion:2,enabled:false}});
 f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();assert.equal(Object.keys(f.store.read().occurrences).length,0);
});
test('serialized actor cannot confirm schedules, genuine owning Bot can schedule and acknowledge',async t=>{
 const f=await fixture(t);await assert.rejects(f.assistant.createSchedule({kind:'human'},{operationId:'fake',action:'schedule.create',input:{ownerBotId:f.bot.botId}}),{code:'access_denied'});
 const agent=f.ctx.agents.get(f.session.sessionId),actor=f.policy.fromAgent(agent);
 const s=await f.assistant.createSchedule(actor,{operationId:'bot-schedule',action:'schedule.create',input:{ownerBotId:f.bot.botId,kind:'reminder',message:'Own reminder',rule:{kind:'once',timezone:'UTC',date:'2026-10-09',time:'00:01'}}});
 f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();const notice=f.assistant.notices(actor,{botId:f.bot.botId})[0];
 await f.assistant.ackNotice(actor,{operationId:'bot-ack',action:'notice.ack',input:{noticeId:notice.noticeId,expectedVersion:notice.version}});assert.equal(f.store.read().notices[notice.noticeId].read,true);assert.ok(s.scheduleId);
});
test('long outage materializes bounded first and latest with saved recovery window',async t=>{
 const f=await fixture(t);await f.schedule({kind:'task',recipe:{botId:f.bot.botId,title:'Work',goal:'One response',criteria:['Done'],originSessionId:f.session.sessionId},missedPolicy:'latest',rule:{kind:'interval',timezone:'UTC',anchorAt:'2026-10-09T00:01:00Z',everyMinutes:15}});
 // Proved preadmission block: capacity must preserve selected original identity.
 f.assistant.tasks.createScheduled=async()=>{throw Object.assign(new Error('capacity'),{code:'capacity_exceeded'});};
 f.setNow('2036-10-09T00:02:00Z');await f.assistant.runDue({recovery:true});let rows=Object.values(f.store.read().occurrences);assert.equal(rows.length,2);
 const blocked=rows.find(row=>row.state==='blocked');assert.ok(blocked);const observed=blocked.recoveryObservedAt;assert.ok(observed);assert.ok(f.store.read().schedules[rows[0].scheduleId].missedRange);
 f.setNow('2036-10-09T00:03:01Z');await f.assistant.runDue({recovery:true});rows=Object.values(f.store.read().occurrences);assert.equal(rows.find(row=>row.occurrenceId===blocked.occurrenceId).recoveryObservedAt,observed);assert.equal(rows.find(row=>row.occurrenceId===blocked.occurrenceId).state,'missed');
});
test('lost admission receipt never automatically replays claimed original IDs on restart',async t=>{
 let creates=0;const f=await fixture(t,{tasks:{async createScheduled(){creates++;throw Object.assign(new Error('lost'),{code:'native_admission_unknown'});}}});
 await f.schedule({kind:'task',recipe:{botId:f.bot.botId,title:'Work',goal:'Response',criteria:[],originSessionId:f.session.sessionId}});f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();const row=Object.values(f.store.read().occurrences)[0];assert.equal(row.state,'UNKNOWN');assert.ok(row.createOperationId&&row.startOperationId);
 await f.assistant.runDue({recovery:true});await f.assistant.runDue();assert.equal(creates,1);assert.equal(Object.values(f.store.read().occurrences)[0].occurrenceId,row.occurrenceId);
});
test('configuration drift pauses a scheduled task before native admission',async t=>{
 let creates=0;const f=await fixture(t,{tasks:{async createScheduled(){creates++;}}});const s=await f.schedule({kind:'task',recipe:{botId:f.bot.botId,title:'Work',goal:'Response',criteria:[],originSessionId:f.session.sessionId}});
 await f.store.transact({operationId:'drift',action:'test.drift'},draft=>{draft.bots[f.bot.botId].configRevision++;return true;});f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();assert.equal(creates,0);assert.equal(f.store.read().schedules[s.scheduleId].enabled,false);assert.equal(f.store.read().schedules[s.scheduleId].pauseReason,'schedule_config_changed');
});
test('notice identity and CAS preserve new unread result, saved previews use codepoints',async t=>{
 const f=await fixture(t);await f.store.transact({operationId:'results',action:'test.result'},draft=>{
  const task={taskId:'task-notice',botId:f.bot.botId,title:'Notice',goal:'g',criteria:[],version:1,state:'completed',acceptance:'unknown',currentAttemptId:'attempt-new',origins:[],source:{kind:'human'}};draft.tasks[task.taskId]=task;
  for(const [id,epoch] of [['attempt-old',1],['attempt-new',2]]) {const attempt={attemptId:id,taskId:task.taskId,epoch,state:'completed',resultOutboxId:`out-${id}`,report:{text:'😀'.repeat(900),origins:[],source:{kind:'human'}}};draft.attempts[id]=attempt;const row={outboxId:attempt.resultOutboxId,kind:'result',taskId:task.taskId,attemptId:id,epoch,botId:task.botId,sessionId:f.session.sessionId,source:{kind:'human'},origins:[]};draft.outbox[row.outboxId]=row;f.assistant.recordResultNoticeInDraft(draft,task,attempt,row);}
  return true;
 });const notices=f.assistant.notices(f.human);assert.equal(notices.length,2);await f.assistant.ackNotice(f.human,{operationId:'ack-old',action:'notice.ack',input:{noticeId:notices[0].noticeId,expectedVersion:1}});
 assert.equal(f.assistant.briefing(f.human).unreadCount,1);assert.equal([...f.assistant.briefing(f.human).tasks[0].previews[0].text].length,800);
 await assert.rejects(f.assistant.ackNotice(f.human,{operationId:'stale-ack',action:'notice.ack',input:{noticeId:notices[0].noticeId,expectedVersion:1}}),{code:'revision_conflict'});
});
test('diagnostics allowlists primitives and never forwards injected data or errors',async t=>{
 const f=await fixture(t);const output=f.assistant.diagnostics(f.human,{operationIds:['safe-operation','https://secret.example/token'],error:{code:'safe_code',message:'/secret Authorization=abc'},versions:{plugin:'1.1.0',node:'/absolute/secret',model:'API_SECRET'},path:'/secret',url:'https://secret'});const text=JSON.stringify(output);
 assert.match(text,/1.1.0/);assert.doesNotMatch(text,/Authorization|secret|API_SECRET|absolute|https:/);assert.equal(output.counts.bots,1);
});
test('one lifecycle timer, close drains admitted work and old wakeup cannot admit',async t=>{
 const f=await fixture(t);await f.schedule();await f.assistant.start();assert.equal(f.active.size,1);const old=[...f.active.values()][0].fn;
 await f.assistant.close();assert.equal(f.active.size,0);f.setNow('2026-10-09T00:01:00Z');await old();assert.equal(Object.keys(f.store.read().occurrences).length,0);
});
test('occurrence cleanup needs human selection CAS and refuses UNKNOWN evidence',async t=>{
 const f=await fixture(t);const s=await f.schedule();f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();const row=Object.values(f.store.read().occurrences)[0];
 await assert.rejects(f.assistant.pruneOccurrences(f.human,{operationId:'stale-prune',action:'occurrence.prune',input:{occurrenceIds:[row.occurrenceId],expectedVersions:{[row.occurrenceId]:0},confirm:true}}),{code:'revision_conflict'});
 await f.store.transact({operationId:'unknown-ref',action:'test.ref'},draft=>{draft.outbox['unknown-ref']={state:'UNKNOWN',occurrenceId:row.occurrenceId};return true;});
 await assert.rejects(f.assistant.pruneOccurrences(f.human,{operationId:'prune-unknown',action:'occurrence.prune',input:{occurrenceIds:[row.occurrenceId],expectedVersions:{[row.occurrenceId]:row.version},confirm:true}}),{code:'occurrence_referenced'});
 await f.store.transact({operationId:'settle-ref',action:'test.ref'},draft=>{draft.outbox['unknown-ref'].state='settled';return true;});await f.assistant.pruneOccurrences(f.human,{operationId:'prune',action:'occurrence.prune',input:{occurrenceIds:[row.occurrenceId],expectedVersions:{[row.occurrenceId]:row.version},confirm:true}});assert.equal(f.store.read().occurrences[row.occurrenceId],undefined);assert.ok(f.store.read().schedules[s.scheduleId]);
});
test('real scheduled admission saves dedicated task and first attempt atomically and creates result notice',async t=>{
 const {TaskController}=await import('../../src/native/tasks.mjs'),{ConversationBroker}=await import('../../src/native/broker.mjs'),{BotService}=await import('../../src/native/service.mjs'),{eventually}=await import('./official-fixture.mjs');
 const f=await fixture(t),tasks=new TaskController(f),broker=new ConversationBroker({...f,tasks}),service=new BotService({...f,tasks,broker,assistant:f.assistant});f.assistant.tasks=tasks;tasks.setResultSink(broker);broker.setNoticeSink(f.assistant);f.adapter.setService(service);f.beforeClose.unshift(()=>broker.close(),()=>tasks.close());
 await f.schedule({kind:'task',recipe:{botId:f.bot.botId,title:'Scheduled response',goal:'One harmless response',criteria:['Response exists'],originSessionId:f.session.sessionId}});f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();
 const occurrence=Object.values(f.store.read().occurrences)[0];assert.ok(occurrence.taskId);assert.ok(occurrence.attemptId);const task=f.store.read().tasks[occurrence.taskId],attempt=f.store.read().attempts[occurrence.attemptId];assert.equal(task.createdBy.kind,'schedule');assert.equal(task.source.occurrenceId,occurrence.occurrenceId);assert.equal(attempt.taskId,task.taskId);
 await eventually(()=>!!f.store.read().attempts[attempt.attemptId].result);assert.ok(f.assistant.notices(f.human).some(n=>n.taskId===task.taskId&&n.attemptId===attempt.attemptId));await f.assistant.runDue();assert.equal(f.store.read().occurrences[occurrence.occurrenceId].state,'settled');
 const before=f.requests.length;await f.assistant.runDue({recovery:true});assert.equal(f.requests.length,before);
});
test('each result artifact keeps its own current source ACL instead of unioning hidden report into visible result',async t=>{
 const f=await fixture(t),foreign=await f.bots.create(f.human,{operationId:'create-hidden',action:'bot.create',input:{name:'Hidden',role:'Test',cwd:f.dir,contact:{provider:'controlled',model:'model-a'}}}),actor=f.policy.fromAgent(f.ctx.agents.get(f.session.sessionId));
 await f.store.transact({operationId:'artifact-source',action:'test.source'},draft=>{
  draft.bots[foreign.botId].share.enabled=false;draft.memories['secret-memory']={memoryId:'secret-memory',botId:foreign.botId,text:'TOP_SECRET'};
  const task={taskId:'mixed-artifacts',botId:f.bot.botId,title:'Visible task',version:1,state:'awaiting_acceptance',acceptance:'unknown',currentAttemptId:'mixed-attempt',source:{kind:'human'},origins:[]};draft.tasks[task.taskId]=task;
  const attempt={attemptId:'mixed-attempt',taskId:task.taskId,state:'returned',epoch:1,resultOutboxId:'mixed-outbox',report:{text:'TOP_SECRET',origins:[{kind:'memory',id:'secret-memory'}]},result:{content:[{type:'text',text:'Visible native result'}],origins:[]}};draft.attempts[attempt.attemptId]=attempt;
  const row={outboxId:'mixed-outbox',taskId:task.taskId,attemptId:attempt.attemptId,epoch:1,kind:'result',botId:task.botId,sessionId:f.session.sessionId,source:{kind:'human'},origins:[{kind:'memory',id:'secret-memory'}]};draft.outbox[row.outboxId]=row;f.assistant.recordResultNoticeInDraft(draft,task,attempt,row);return true;
 });const briefing=f.assistant.briefing(actor);assert.equal(briefing.tasks[0].previews.length,1);assert.equal(briefing.tasks[0].previews[0].kind,'result');assert.equal(briefing.unreadCount,1);assert.equal(briefing.notices[0].previews.length,1);assert.doesNotMatch(JSON.stringify(briefing),/TOP_SECRET/);
 await f.store.transact({operationId:'revoke-visible-result',action:'test.source'},draft=>{draft.attempts['mixed-attempt'].result.origins=[{kind:'memory',id:'secret-memory'}];return true;});assert.equal(f.assistant.briefing(actor).unreadCount,0);assert.equal(f.assistant.briefing(actor).tasks[0].previews.length,0);
});
test('schedule cap refuses new triggers until explicit settled history cleanup and never drops UNKNOWN',async t=>{
 const f=await fixture(t),s=await f.schedule();await f.store.transact({operationId:'full-occurrences',action:'test.full'},draft=>{for(let i=0;i<10000;i++)draft.occurrences[`historical-${i}`]={occurrenceId:`historical-${i}`,scheduleId:s.scheduleId,state:i===0?'UNKNOWN':'settled',version:1,dueAt:'2025-01-01T00:00:00.000Z'};return true;});f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();assert.equal(Object.keys(f.store.read().occurrences).length,10000);assert.equal(f.store.read().occurrences['historical-0'].state,'UNKNOWN');
 // The unknown occurrence prevents even reaching the cap check for this schedule.
 const second=await f.schedule({},'second-schedule');await f.assistant.runDue();assert.equal(f.store.read().schedules[second.scheduleId].pauseReason,'occurrence_capacity_exceeded');
 await f.assistant.pruneOccurrences(f.human,{operationId:'capacity-cleanup',action:'occurrence.prune',input:{occurrenceIds:['historical-1'],expectedVersions:{'historical-1':1},confirm:true}});await f.assistant.runDue();assert.equal(Object.keys(f.store.read().occurrences).length,10000);assert.ok(Object.values(f.store.read().occurrences).some(o=>o.scheduleId===second.scheduleId&&o.state==='settled'));
});
test('actual 15-slot capacity keeps original create task identity blocked and never creates parallel cycle',async t=>{
 const {TaskController}=await import('../../src/native/tasks.mjs');const f=await fixture(t),tasks=new TaskController(f);f.assistant.tasks=tasks;f.beforeClose.unshift(()=>tasks.close());
 await f.store.transact({operationId:'fill-capacity',action:'test.capacity'},draft=>{for(let i=0;i<15;i++)draft.attempts[`held-${i}`]={attemptId:`held-${i}`,botId:f.bot.botId,taskId:`held-task-${i}`,state:i===0?'UNKNOWN':'running',reservationHeld:true};return true;});
 await f.schedule({kind:'task',rule:{kind:'interval',timezone:'UTC',anchorAt:'2026-10-09T00:01:00Z',everyMinutes:15},recipe:{botId:f.bot.botId,title:'Capacity task',goal:'One response',criteria:[],originSessionId:f.session.sessionId}});f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();const occurrence=Object.values(f.store.read().occurrences)[0];assert.equal(occurrence.state,'blocked');assert.equal(occurrence.errorCode,'capacity_exhausted');assert.ok(occurrence.taskId);assert.equal(occurrence.attemptId,undefined);
 await f.assistant.runDue();assert.equal(Object.keys(f.store.read().tasks).length,1);assert.equal(Object.values(f.store.read().occurrences)[0].taskId,occurrence.taskId);f.setNow('2026-10-09T00:16:00Z');await f.assistant.runDue();assert.equal(Object.keys(f.store.read().occurrences).length,1);assert.equal(f.store.read().attempts['held-0'].reservationHeld,true);
});
test('handoff current task cannot expose old execution artifacts when original session read is revoked',async t=>{
 const f=await fixture(t),other=await f.bots.create(f.human,{operationId:'create-other',action:'bot.create',input:{name:'Other',role:'Test',cwd:f.dir,contact:{provider:'controlled',model:'model-a'}}}),viewerSession=await f.sessions.create(f.human,{operationId:'viewer-session',action:'session.create',input:{botId:other.botId}}),actor=f.policy.fromAgent(f.ctx.agents.get(viewerSession.sessionId));
 await f.store.transact({operationId:'handoff-fixture',action:'test.handoff'},draft=>{
 draft.bots[f.bot.botId].share.enabled=false;
 draft.tasks['handed-task']={taskId:'handed-task',botId:other.botId,title:'Current owned task',state:'awaiting_acceptance',acceptance:'unknown',version:1,currentAttemptId:'old-execution',origins:[],source:{kind:'human'}};
 draft.attempts['old-execution']={attemptId:'old-execution',taskId:'handed-task',botId:f.bot.botId,sessionId:f.session.sessionId,state:'returned',epoch:1,result:{content:[{type:'text',text:'OLD_PRIVATE_RESULT'}],origins:[]},report:{text:'OLD_PRIVATE_REPORT',origins:[]}};return true;
 });assert.equal(f.assistant.briefing(actor,{botId:other.botId}).tasks.length,1);assert.equal(f.assistant.briefing(actor,{botId:other.botId}).tasks[0].previews.length,0);assert.doesNotMatch(JSON.stringify(f.assistant.briefing(actor)),/OLD_PRIVATE/);
});
test('diagnostics versions come from actual runtime rather than caller-supplied version labels',async t=>{
 const f=await fixture(t);const output=f.assistant.diagnostics(f.human,{versions:{plugin:'9.9.9',service:'8.8.8',dsh:'7.7.7',node:'6.6.6'},error:{code:'my_secret_key'}});assert.equal(output.versions.plugin,'1.1.0');assert.equal(output.versions.node,process.version);assert.equal(output.versions.dsh,'0.2.0-rc.2');assert.equal(output.errorCode,'unknown_error');
});
test('editing frequency preserves recipe origins and independent meeting barriers for a prospective execution',async t=>{
 const f=await fixture(t);await f.store.transact({operationId:'independent-source',action:'test.meeting'},draft=>{draft.meetings['sealed-meeting']={meetingId:'sealed-meeting',epoch:1,phase:'independent',participants:[{botId:f.bot.botId,memberEpoch:1,active:true}]};draft.sessions[f.session.sessionId].lineage={meetingId:'sealed-meeting',epoch:1,phase:'independent',botId:f.bot.botId,memberEpoch:1,sessionId:f.session.sessionId};return true;});const actor=f.policy.fromAgent(f.ctx.agents.get(f.session.sessionId));
 const schedule=await f.assistant.createSchedule(actor,{operationId:'private-schedule',action:'schedule.create',input:{ownerBotId:f.bot.botId,kind:'task',recipe:{botId:f.bot.botId,title:'Private recipe',goal:'PRIVATE_MEETING_INPUT',criteria:[],originSessionId:f.session.sessionId},rule:{kind:'once',timezone:'UTC',date:'2026-10-09',time:'00:01'}}});
 const edited=await f.assistant.updateSchedule(f.human,{operationId:'edit-private-rule',action:'schedule.update',input:{scheduleId:schedule.scheduleId,expectedVersion:schedule.version,rule:{kind:'once',timezone:'UTC',date:'2026-10-09',time:'00:02'}}});assert.ok(edited.contentSources?.some(s=>s.meetingId==='sealed-meeting'));f.setNow('2026-10-09T00:02:00Z');await f.assistant.runDue();assert.equal(Object.keys(f.store.read().tasks).length,0);assert.equal(f.store.read().schedules[schedule.scheduleId].pauseReason,'access_denied');
});
test('native receiver archive pauses schedules before creating work even with stale ready ledger binding',async t=>{
 let creates=0;const f=await fixture(t,{tasks:{async createScheduled(){creates++;}}});const s=await f.schedule({kind:'task',recipe:{botId:f.bot.botId,title:'Work',goal:'Response',criteria:[],originSessionId:f.session.sessionId}});await f.ctx.workspaceRegistry.archiveSession(f.session.sessionId);assert.equal(f.store.read().sessions[f.session.sessionId].archived,false);f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();assert.equal(creates,0);assert.equal(f.store.read().schedules[s.scheduleId].pauseReason,'schedule_receiver_changed');
});
test('initial DST skipped local time is recorded, 100 active schedule limit has no silent overwrite',async t=>{
 const f=await fixture(t,{at:'2026-03-08T05:00:00Z'});const gap=await f.schedule({rule:{kind:'daily',timezone:'America/New_York',time:'02:30'}},'dst-gap');assert.equal(gap.nextDueAt,'2026-03-09T06:30:00.000Z');assert.equal(gap.lastSkippedLocalTimes?.reason,'nonexistent_local_time');
 for(let i=1;i<100;i++)await f.schedule({},`cap-schedule-${i}`);await assert.rejects(f.schedule({},'too-many-schedules'),{code:'schedule_capacity_exceeded'});assert.equal(Object.keys(f.store.read().schedules).length,100);
 const archived=await f.assistant.setScheduleState(f.human,{operationId:'cap-archive',action:'schedule.state',input:{scheduleId:gap.scheduleId,expectedVersion:gap.version,enabled:false,archived:true}});await f.schedule({},'replacement-schedule');await assert.rejects(f.assistant.setScheduleState(f.human,{operationId:'cap-restore',action:'schedule.state',input:{scheduleId:gap.scheduleId,expectedVersion:archived.version,enabled:true,archived:false}}),{code:'schedule_capacity_exceeded'});
});
test('archive and explicit restore retain original schedule identity and valid execution consent',async t=>{
 const f=await fixture(t),s=await f.schedule({kind:'task',recipe:{botId:f.bot.botId,title:'Work',goal:'One response',criteria:[],originSessionId:f.session.sessionId}});
 const archived=await f.assistant.setScheduleState(f.human,{operationId:'archive-schedule',action:'schedule.state',input:{scheduleId:s.scheduleId,expectedVersion:1,enabled:false,archived:true}});
 const restored=await f.assistant.setScheduleState(f.human,{operationId:'restore-schedule',action:'schedule.state',input:{scheduleId:s.scheduleId,expectedVersion:archived.version,enabled:true,archived:false}});assert.equal(restored.scheduleId,s.scheduleId);assert.equal(restored.consentVersion,s.consentVersion);assert.equal(restored.enabled,true);assert.equal(restored.archived,false);
});
test('deadline is checked again inside task admission after a queued boundary crosses 60 seconds',async t=>{
 const {TaskController}=await import('../../src/native/tasks.mjs');const f=await fixture(t),tasks=new TaskController(f);f.beforeClose.unshift(()=>tasks.close());f.assistant.tasks={async createScheduled(actor,command){f.setNow('2026-10-09T00:02:01Z');return tasks.createScheduled(actor,command);},startScheduled:(actor,command)=>tasks.startScheduled(actor,command)};
 await f.schedule({kind:'task',recipe:{botId:f.bot.botId,title:'Window',goal:'Response',criteria:[],originSessionId:f.session.sessionId}});f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();assert.equal(Object.keys(f.store.read().tasks).length,0);assert.equal(Object.values(f.store.read().occurrences)[0].state,'missed');assert.equal(f.requests.length,0);
});
test('pause racing a delayed model precheck prevents native task creation using the claimed fixed IDs',async t=>{
 const {deferred,eventually}=await import('./official-fixture.mjs');const gate=deferred();let creates=0;const f=await fixture(t,{tasks:{async createScheduled(){creates++;}}}),s=await f.schedule({kind:'task',recipe:{botId:f.bot.botId,title:'Pause',goal:'Response',criteria:[],originSessionId:f.session.sessionId}});
 const original=f.adapter.validateModel.bind(f.adapter);f.adapter.validateModel=async input=>{await gate.promise;return original(input);};f.setNow('2026-10-09T00:01:00Z');const admission=f.assistant.runDue();await eventually(()=>Object.values(f.store.read().occurrences)[0]?.state==='claimed');const claim=Object.values(f.store.read().occurrences)[0];
 await f.assistant.setScheduleState(f.human,{operationId:'pause-race',action:'schedule.state',input:{scheduleId:s.scheduleId,expectedVersion:f.store.read().schedules[s.scheduleId].version,enabled:false}});gate.resolve();await admission;assert.equal(creates,0);assert.equal(f.requests.length,0);assert.equal(f.store.read().occurrences[claim.occurrenceId].createOperationId,claim.createOperationId);assert.equal(f.store.read().occurrences[claim.occurrenceId].state,'blocked');
});
test('owning Bot foreign receiver consent rechecks control revocation rather than relying on a saved caller label',async t=>{
 const f=await fixture(t),receiverBot=await f.bots.create(f.human,{operationId:'create-receiver',action:'bot.create',input:{name:'Receiver',role:'Test',cwd:f.dir,contact:{provider:'controlled',model:'model-a'}}}),receiver=await f.sessions.create(f.human,{operationId:'receiver-session',action:'session.create',input:{botId:receiverBot.botId}}),actor=f.policy.fromAgent(f.ctx.agents.get(f.session.sessionId));
 const grantInput={grantId:'receiver-control',ownerBotId:receiverBot.botId,recipientBotId:f.bot.botId,level:'control',active:true,scope:{sessions:[receiver.sessionId]}};await f.policy.authorizeShare(f.human,{operationId:'receiver-grant',action:'grant.set',input:grantInput});
 const s=await f.assistant.createSchedule(actor,{operationId:'bot-task-schedule',action:'schedule.create',input:{ownerBotId:f.bot.botId,kind:'task',recipe:{botId:f.bot.botId,title:'Receiver work',goal:'Response',criteria:[],originSessionId:receiver.sessionId},rule:{kind:'once',timezone:'UTC',date:'2026-10-09',time:'00:01'}}});
 await f.policy.authorizeShare(f.human,{operationId:'receiver-revoke',action:'grant.set',input:{...grantInput,expectedVersion:1,active:false}});f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();assert.equal(Object.keys(f.store.read().tasks).length,0);assert.equal(f.store.read().schedules[s.scheduleId].enabled,false);assert.equal(f.store.read().schedules[s.scheduleId].pauseReason,'access_denied');
});
test('native settlement wakes the sole lifecycle timer to reconcile and schedule the following cycle',async t=>{
 const {TaskController}=await import('../../src/native/tasks.mjs'),{ConversationBroker}=await import('../../src/native/broker.mjs'),{BotService}=await import('../../src/native/service.mjs'),{deferred,eventually,textChunks}=await import('./official-fixture.mjs');const gate=deferred();t.after(()=>gate.resolve());
 const f=await fixture(t,{nativeOptions:{stream:async function*(){await gate.promise;yield* textChunks('Actual scheduled reply');}}}),tasks=new TaskController(f),broker=new ConversationBroker({...f,tasks}),service=new BotService({...f,tasks,broker,assistant:f.assistant});f.assistant.tasks=tasks;tasks.setResultSink(broker);broker.setNoticeSink(f.assistant);f.adapter.setService(service);f.beforeClose.unshift(()=>broker.close(),()=>tasks.close());
 await f.schedule({kind:'task',rule:{kind:'interval',timezone:'UTC',anchorAt:'2026-10-09T00:01:00Z',everyMinutes:15},recipe:{botId:f.bot.botId,title:'Recurring',goal:'Response',criteria:[],originSessionId:f.session.sessionId}});await f.assistant.start();f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();assert.equal(f.active.size,0);const occurrence=Object.values(f.store.read().occurrences)[0];gate.resolve();await eventually(()=>f.store.read().attempts[occurrence.attemptId].reservationHeld===false);await eventually(()=>f.active.size===1);assert.equal(f.requests.filter(r=>JSON.stringify(r.messages).includes('执行任务 Recurring')).length,1);
});
test('an alleged terminal attempt without settlement evidence cannot release an UNKNOWN occurrence',async t=>{
 const f=await fixture(t),s=await f.schedule();await f.store.transact({operationId:'alleged-terminal',action:'test.evidence'},draft=>{draft.attempts['alleged-attempt']={attemptId:'alleged-attempt',taskId:'alleged-task',state:'returned',reservationHeld:false};draft.occurrences['alleged-occurrence']={occurrenceId:'alleged-occurrence',scheduleId:s.scheduleId,consentVersion:1,dueAt:'2026-10-09T00:00:00.000Z',state:'UNKNOWN',version:1,attemptId:'alleged-attempt',taskId:'alleged-task'};return true;});await f.assistant.runDue({recovery:true});assert.equal(f.store.read().occurrences['alleged-occurrence'].state,'UNKNOWN');
});
test('cleanup keeps settled original occurrence when an UNKNOWN child still references its attempt',async t=>{
 const f=await fixture(t);await f.schedule();f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();const o=Object.values(f.store.read().occurrences)[0];await f.store.transact({operationId:'unknown-child-ref',action:'test.ref'},draft=>{draft.occurrences[o.occurrenceId].attemptId='old-parent';draft.attempts['unknown-child']={attemptId:'unknown-child',taskId:'child-task',parentAttemptId:'old-parent',state:'UNKNOWN',reservationHeld:true};return true;});await assert.rejects(f.assistant.pruneOccurrences(f.human,{operationId:'prune-with-unknown-child',action:'occurrence.prune',input:{occurrenceIds:[o.occurrenceId],expectedVersions:{[o.occurrenceId]:o.version},confirm:true}}),{code:'occurrence_referenced'});
});
test('a native UNKNOWN resource event wakes lifecycle reconciliation without automatic native replay',async t=>{
 const f=await fixture(t),s=await f.schedule({kind:'task',recipe:{botId:f.bot.botId,title:'Unknown work',goal:'Response',criteria:[],originSessionId:f.session.sessionId}});await f.assistant.start();await f.store.transact({operationId:'resource-unknown-event',action:'test.resource'},draft=>{draft.attempts['resource-attempt']={attemptId:'resource-attempt',taskId:'resource-task',state:'UNKNOWN',reservationHeld:true};draft.occurrences['resource-occurrence']={occurrenceId:'resource-occurrence',scheduleId:s.scheduleId,consentVersion:1,dueAt:s.nextDueAt,state:'running',version:1,attemptId:'resource-attempt',taskId:'resource-task'};return true;});assert.equal(f.active.size,1);const [id,timer]=[...f.active.entries()][0];f.active.delete(id);await timer.fn();assert.equal(f.store.read().occurrences['resource-occurrence'].state,'UNKNOWN');assert.equal(f.requests.length,0);assert.equal(f.active.size,0);
});
test('admitted scheduled dependency input survives unrelated private upstream edit and delivers its genuine result',async t=>{
 const {TaskController}=await import('../../src/native/tasks.mjs'),{ConversationBroker}=await import('../../src/native/broker.mjs'),{BotService}=await import('../../src/native/service.mjs'),{deferred,eventually,textChunks}=await import('./official-fixture.mjs');const gate=deferred();t.after(()=>gate.resolve());
 const f=await fixture(t,{nativeOptions:{stream:async function*(options){if(JSON.stringify(options.messages).includes('执行任务 Scheduled fixed'))await gate.promise;yield* textChunks('Original public input result');}}}),tasks=new TaskController(f),broker=new ConversationBroker({...f,tasks}),service=new BotService({...f,tasks,broker,assistant:f.assistant});f.assistant.tasks=tasks;tasks.setResultSink(broker);broker.setNoticeSink(f.assistant);f.adapter.setService(service);f.beforeClose.unshift(()=>broker.close(),()=>tasks.close());
 const upstreamBot=await f.bots.create(f.human,{operationId:'create-fixed-upstream-bot',action:'bot.create',input:{name:'Upstream Bot',role:'Test',cwd:f.dir,contact:{provider:'controlled',model:'model-a'}}});const upstream=await tasks.create(f.human,{operationId:'fixed-upstream-create',action:'task.create',input:{botId:upstreamBot.botId,title:'Upstream',goal:'Public result',criteria:['One result']}}),upstreamAttempt=await tasks.start(f.human,{operationId:'fixed-upstream-start',action:'task.start',input:{taskId:upstream.taskId,expectedVersion:upstream.version}});await eventually(()=>!f.store.read().attempts[upstreamAttempt.attemptId].reservationHeld);const latestUpstream=f.store.read().tasks[upstream.taskId];await tasks.accept(f.human,{operationId:'fixed-upstream-accept',action:'task.accept',input:{taskId:upstream.taskId,attemptId:upstreamAttempt.attemptId,expectedVersion:latestUpstream.version,outcome:'passed',evidence:'Native saved public result'}});
 await f.schedule({kind:'task',recipe:{botId:f.bot.botId,title:'Scheduled fixed',goal:'Use admitted public upstream',criteria:[],dependsOn:[upstream.taskId],originSessionId:f.session.sessionId}});f.setNow('2026-10-09T00:01:00Z');await f.assistant.runDue();const occurrence=Object.values(f.store.read().occurrences)[0],admitted=f.store.read().attempts[occurrence.attemptId];assert.ok(admitted.prerequisiteInputs[0].inputId);
 await f.store.transact({operationId:'private-upstream-edit',action:'test.edit'},draft=>{draft.bots['private-bot']={botId:'private-bot',lifecycle:'active',share:{enabled:false,receivers:[],scope:{sessions:[],tasks:[],memories:[],materials:[]}}};draft.memories['private-upstream-memory']={memoryId:'private-upstream-memory',botId:'private-bot',text:'NEW_PRIVATE_SOURCE'};draft.tasks[upstream.taskId].goal='NEW_PRIVATE_SOURCE';draft.tasks[upstream.taskId].definitionVersion++;draft.tasks[upstream.taskId].origins=[{kind:'memory',id:'private-upstream-memory'}];return true;});
 const principal=f.policy.fromScheduleOccurrence(occurrence.occurrenceId);assert.equal(principal.occurrenceId,occurrence.occurrenceId);gate.resolve();await eventually(()=>!f.store.read().attempts[admitted.attemptId].reservationHeld);await eventually(()=>f.store.read().outbox[admitted.resultOutboxId].state==='accepted');assert.ok(f.assistant.notices(f.human).some(n=>n.attemptId===admitted.attemptId));assert.doesNotMatch(JSON.stringify(admitted.prerequisiteInputs),/NEW_PRIVATE_SOURCE/);await f.store.transact({operationId:'revoke-fixed-upstream-sharing',action:'test.revoke'},draft=>{draft.bots[upstreamBot.botId].share.enabled=false;return true;});assert.throws(()=>f.policy.fromScheduleOccurrence(occurrence.occurrenceId),{code:'access_denied'});
});
